# coding: utf-8

"""
    QAnswer 2.0

    QAnswer 2.0 API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from freetext-sdk.models.feedback_response import FeedbackResponse

class TestFeedbackResponse(unittest.TestCase):
    """FeedbackResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FeedbackResponse:
        """Test FeedbackResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FeedbackResponse`
        """
        model = FeedbackResponse()
        if include_optional:
            return FeedbackResponse(
                status = True,
                message = '',
                feedback = freetext-sdk.models.feedback_model.FeedbackModel(
                    question = '', 
                    completion = '', 
                    rate = '', 
                    conversation_id = '', 
                    message_id = '', 
                    parent_message_id = '', 
                    comment = '', 
                    task_category = '', 
                    approved = True, 
                    origin = '', 
                    creation_date = '', )
            )
        else:
            return FeedbackResponse(
                message = '',
                feedback = freetext-sdk.models.feedback_model.FeedbackModel(
                    question = '', 
                    completion = '', 
                    rate = '', 
                    conversation_id = '', 
                    message_id = '', 
                    parent_message_id = '', 
                    comment = '', 
                    task_category = '', 
                    approved = True, 
                    origin = '', 
                    creation_date = '', ),
        )
        """

    def testFeedbackResponse(self):
        """Test FeedbackResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
