from typing import Any, Dict, Optional, Union

HAS_JS: bool

class Node:
    def to_html(self, indent: int = 0, _in_raw_text: bool = False) -> str: ...
    def to_dom(self, parent_js: Any | None = None): ...
    def mount(self, target: str | Any | None = None): ...

class Text(Node):
    def __init__(self, text: str) -> None: ...

class Comment(Node):
    def __init__(self, text: str) -> None: ...

class Fragment(Node):
    def __init__(self, *children: Node | str): ...
    def add(self, child: Node | str | None) -> Node | None: ...

class Element(Node):
    def __init__(self, *children: Node | str, **attrs: Any) -> None: ...
    def __call__(self, *children: Node | str, **attrs: Any) -> "Element": ...
    def set_attr(self, **attrs: Any) -> "Element": ...
    def add_class(self, *classes: Any) -> "Element": ...
    def classes(self, *classes: Any) -> "Element": ...
    def set_style(self, style: Union[str, Dict[str, Any]]) -> "Element": ...
    def style(self, **props: Any) -> "Element": ...
    def data(self, **ds: Any) -> "Element": ...
    def aria(self, **props: Any) -> "Element": ...

def create(tag: str, *children: Any, **attrs: Any) -> Element: ...
def custom(tag_name: str, *children: Any, **attrs: Any) -> Element: ...
def html_string(node: Node) -> str: ...
def element_class_for_tag(tag: str) -> type: ...
def tag_for_element_class_name(class_name: str) -> str: ...
def rebuild_html_classes(overrides: dict[str, str] | None = None) -> None: ...

# CSS API (re-exported)
class CSSStyleRule: ...
class AtRule: ...
class KeyframesRule: ...
class PageRule: ...
class FontFaceRule: ...

class Stylesheet:
    def rule(self, selector: str, **props: Any) -> CSSStyleRule: ...

def css_string(sheet: Stylesheet) -> str: ...

# ----- HTML element classes for type checkers -----
# Document metadata
class Html(Element): ...
class Head(Element): ...
class Title(Element): ...
class Base(Element): ...
class Link(Element): ...
class Meta(Element): ...
class Style(Element): ...

# Sections
class Body(Element): ...
class Address(Element): ...
class Article(Element): ...
class Aside(Element): ...
class Footer(Element): ...
class Header(Element): ...
class Heading1(Element): ...
class Heading2(Element): ...
class Heading3(Element): ...
class Heading4(Element): ...
class Heading5(Element): ...
class Heading6(Element): ...
class HeadingGroup(Element): ...
class Main(Element): ...
class Navigation(Element): ...
class Section(Element): ...

# Grouping
class BlockQuote(Element): ...
class DescriptionDetails(Element): ...
class Division(Element): ...
class DescriptionList(Element): ...
class DescriptionTerm(Element): ...
class FigureCaption(Element): ...
class Figure(Element): ...
class HorizontalRule(Element): ...
class ListItem(Element): ...
class Menu(Element): ...
class OrderedList(Element): ...
class Paragraph(Element): ...
class PreformattedText(Element): ...
class UnorderedList(Element): ...

# Text-level
class Anchor(Element): ...
class Abbreviation(Element): ...
class Bold(Element): ...
class BidirectionalIsolation(Element): ...
class BidirectionalOverride(Element): ...
class LineBreak(Element): ...
class Citation(Element): ...
class Code(Element): ...
class Data(Element): ...
class Definition(Element): ...
class Emphasis(Element): ...
class Italic(Element): ...
class KeyboardInput(Element): ...
class Mark(Element): ...
class Quotation(Element): ...
class RubyParenthesis(Element): ...
class RubyText(Element): ...
class RubyAnnotation(Element): ...
class Strikethrough(Element): ...
class SampleOutput(Element): ...
class Small(Element): ...
class Span(Element): ...
class Strong(Element): ...
class Subscript(Element): ...
class Superscript(Element): ...
class Time(Element): ...
class Underline(Element): ...
class Variable(Element): ...
class WordBreakOpportunity(Element): ...

# Edits
class Deletion(Element): ...
class Insertion(Element): ...

# Embedded
class MapArea(Element): ...
class Audio(Element): ...
class Image(Element): ...
class ImageMap(Element): ...
class Track(Element): ...
class Video(Element): ...
class Embed(Element): ...
class InlineFrame(Element): ...
class Object(Element): ...
class Parameter(Element): ...
class Picture(Element): ...
class Source(Element): ...

# Scripting
class Canvas(Element): ...
class NoScript(Element): ...
class Script(Element): ...
class Slot(Element): ...
class Template(Element): ...

# Table
class TableCaption(Element): ...
class TableColumn(Element): ...
class TableColumnGroup(Element): ...
class Table(Element): ...
class TableBody(Element): ...
class TableDataCell(Element): ...
class TableFooter(Element): ...
class TableHeaderCell(Element): ...
class TableHead(Element): ...
class TableRow(Element): ...

# Forms
class Button(Element): ...
class DataList(Element): ...
class FieldSet(Element): ...
class Form(Element): ...
class Input(Element): ...
class Label(Element): ...
class Legend(Element): ...
class Meter(Element): ...
class OptionGroup(Element): ...
class Option(Element): ...
class Output(Element): ...
class Progress(Element): ...
class Select(Element): ...
class TextArea(Element): ...

# Interactive
class Details(Element): ...
class Dialog(Element): ...
class Summary(Element): ...

# Non-standard
class Portal(Element): ...
