# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Annotated, List, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel


class GetMultipleProductsForCollectionSync(BaseModel):
    nodes: List[
        Optional[
            Annotated[
                Union[
                    "GetMultipleProductsForCollectionSyncNodesNode",
                    "GetMultipleProductsForCollectionSyncNodesProduct",
                ],
                Field(discriminator="typename__"),
            ]
        ]
    ]


class GetMultipleProductsForCollectionSyncNodesNode(BaseModel):
    typename__: Literal[
        "AbandonedCheckout",
        "AbandonedCheckoutLineItem",
        "Abandonment",
        "AddAllProductsOperation",
        "AdditionalFee",
        "App",
        "AppCatalog",
        "AppCredit",
        "AppInstallation",
        "AppPurchaseOneTime",
        "AppRevenueAttributionRecord",
        "AppSubscription",
        "AppUsageRecord",
        "Article",
        "BasicEvent",
        "Blog",
        "BulkOperation",
        "BusinessEntity",
        "CalculatedOrder",
        "CartTransform",
        "CashTrackingAdjustment",
        "CashTrackingSession",
        "CatalogCsvOperation",
        "Channel",
        "ChannelDefinition",
        "ChannelInformation",
        "CheckoutProfile",
        "Collection",
        "Comment",
        "CommentEvent",
        "Company",
        "CompanyAddress",
        "CompanyContact",
        "CompanyContactRole",
        "CompanyContactRoleAssignment",
        "CompanyLocation",
        "CompanyLocationCatalog",
        "CompanyLocationStaffMemberAssignment",
        "Customer",
        "CustomerAccountAppExtensionPage",
        "CustomerAccountNativePage",
        "CustomerPaymentMethod",
        "CustomerSegmentMembersQuery",
        "CustomerVisit",
        "DeliveryCarrierService",
        "DeliveryCondition",
        "DeliveryCountry",
        "DeliveryCustomization",
        "DeliveryLocationGroup",
        "DeliveryMethod",
        "DeliveryMethodDefinition",
        "DeliveryParticipant",
        "DeliveryProfile",
        "DeliveryProfileItem",
        "DeliveryPromiseProvider",
        "DeliveryProvince",
        "DeliveryRateDefinition",
        "DeliveryZone",
        "DiscountAutomaticBxgy",
        "DiscountAutomaticNode",
        "DiscountCodeNode",
        "DiscountNode",
        "DiscountRedeemCodeBulkCreation",
        "Domain",
        "DraftOrder",
        "DraftOrderLineItem",
        "DraftOrderTag",
        "Duty",
        "ExchangeLineItem",
        "ExchangeV2",
        "ExternalVideo",
        "Fulfillment",
        "FulfillmentConstraintRule",
        "FulfillmentEvent",
        "FulfillmentHold",
        "FulfillmentLineItem",
        "FulfillmentOrder",
        "FulfillmentOrderDestination",
        "FulfillmentOrderLineItem",
        "FulfillmentOrderMerchantRequest",
        "GenericFile",
        "GiftCard",
        "GiftCardCreditTransaction",
        "GiftCardDebitTransaction",
        "InventoryAdjustmentGroup",
        "InventoryItem",
        "InventoryItemMeasurement",
        "InventoryLevel",
        "InventoryQuantity",
        "LineItem",
        "LineItemGroup",
        "Location",
        "MailingAddress",
        "Market",
        "MarketCatalog",
        "MarketRegionCountry",
        "MarketWebPresence",
        "MarketingActivity",
        "MarketingEvent",
        "MediaImage",
        "Menu",
        "Metafield",
        "MetafieldDefinition",
        "MetafieldStorefrontVisibility",
        "Metaobject",
        "MetaobjectDefinition",
        "Model3d",
        "Node",
        "OnlineStoreTheme",
        "Order",
        "OrderAdjustment",
        "OrderDisputeSummary",
        "OrderTransaction",
        "Page",
        "PaymentCustomization",
        "PaymentMandate",
        "PaymentSchedule",
        "PaymentTerms",
        "PaymentTermsTemplate",
        "PriceList",
        "PriceRule",
        "PriceRuleDiscountCode",
        "PrivateMetafield",
        "ProductBundleOperation",
        "ProductDeleteOperation",
        "ProductDuplicateOperation",
        "ProductFeed",
        "ProductOption",
        "ProductOptionValue",
        "ProductSetOperation",
        "ProductTaxonomyNode",
        "ProductVariant",
        "ProductVariantComponent",
        "Publication",
        "PublicationResourceOperation",
        "QuantityPriceBreak",
        "Refund",
        "RefundShippingLine",
        "Return",
        "ReturnLineItem",
        "ReturnableFulfillment",
        "ReverseDelivery",
        "ReverseDeliveryLineItem",
        "ReverseFulfillmentOrder",
        "ReverseFulfillmentOrderDisposition",
        "ReverseFulfillmentOrderLineItem",
        "SaleAdditionalFee",
        "SavedSearch",
        "ScriptTag",
        "Segment",
        "SellingPlan",
        "SellingPlanGroup",
        "ServerPixel",
        "Shop",
        "ShopAddress",
        "ShopPolicy",
        "ShopifyPaymentsAccount",
        "ShopifyPaymentsBalanceTransaction",
        "ShopifyPaymentsBankAccount",
        "ShopifyPaymentsDispute",
        "ShopifyPaymentsDisputeEvidence",
        "ShopifyPaymentsDisputeFileUpload",
        "ShopifyPaymentsDisputeFulfillment",
        "ShopifyPaymentsPayout",
        "StaffMember",
        "StandardMetafieldDefinitionTemplate",
        "StoreCreditAccount",
        "StoreCreditAccountCreditTransaction",
        "StoreCreditAccountDebitRevertTransaction",
        "StoreCreditAccountDebitTransaction",
        "StorefrontAccessToken",
        "SubscriptionBillingAttempt",
        "SubscriptionContract",
        "SubscriptionDraft",
        "TaxonomyAttribute",
        "TaxonomyCategory",
        "TaxonomyChoiceListAttribute",
        "TaxonomyMeasurementAttribute",
        "TaxonomyValue",
        "TenderTransaction",
        "TransactionFee",
        "UnverifiedReturnLineItem",
        "UrlRedirect",
        "UrlRedirectImport",
        "Validation",
        "Video",
        "WebPixel",
        "WebhookSubscription",
    ] = Field(alias="__typename")


class GetMultipleProductsForCollectionSyncNodesProduct(BaseModel):
    typename__: Literal["Product"] = Field(alias="__typename")
    id: str
    collections: "GetMultipleProductsForCollectionSyncNodesProductCollections"
    variants: "GetMultipleProductsForCollectionSyncNodesProductVariants"


class GetMultipleProductsForCollectionSyncNodesProductCollections(BaseModel):
    edges: List["GetMultipleProductsForCollectionSyncNodesProductCollectionsEdges"]


class GetMultipleProductsForCollectionSyncNodesProductCollectionsEdges(BaseModel):
    node: "GetMultipleProductsForCollectionSyncNodesProductCollectionsEdgesNode"


class GetMultipleProductsForCollectionSyncNodesProductCollectionsEdgesNode(BaseModel):
    id: str
    handle: str


class GetMultipleProductsForCollectionSyncNodesProductVariants(BaseModel):
    edges: List["GetMultipleProductsForCollectionSyncNodesProductVariantsEdges"]


class GetMultipleProductsForCollectionSyncNodesProductVariantsEdges(BaseModel):
    node: "GetMultipleProductsForCollectionSyncNodesProductVariantsEdgesNode"


class GetMultipleProductsForCollectionSyncNodesProductVariantsEdgesNode(BaseModel):
    id: str
    position: int


GetMultipleProductsForCollectionSync.model_rebuild()
GetMultipleProductsForCollectionSyncNodesProduct.model_rebuild()
GetMultipleProductsForCollectionSyncNodesProductCollections.model_rebuild()
GetMultipleProductsForCollectionSyncNodesProductCollectionsEdges.model_rebuild()
GetMultipleProductsForCollectionSyncNodesProductVariants.model_rebuild()
GetMultipleProductsForCollectionSyncNodesProductVariantsEdges.model_rebuild()
