from enum import Enum


class PlayerErrorReasons(str, Enum):
    ALREADY_PAUSED = "ALREADY_PAUSED"
    ALREADY_PLAYING = "ALREADY_PLAYING"
    CONTEXT_DISALLOW = "CONTEXT_DISALLOW"
    DEVICE_NOT_CONTROLLABLE = "DEVICE_NOT_CONTROLLABLE"
    ENDLESS_CONTEXT = "ENDLESS_CONTEXT"
    NOT_PAUSED = "NOT_PAUSED"
    NOT_PLAYING_CONTEXT = "NOT_PLAYING_CONTEXT"
    NOT_PLAYING_LOCALLY = "NOT_PLAYING_LOCALLY"
    NOT_PLAYING_TRACK = "NOT_PLAYING_TRACK"
    NO_ACTIVE_DEVICE = "NO_ACTIVE_DEVICE"
    NO_NEXT_TRACK = "NO_NEXT_TRACK"
    NO_PREV_TRACK = "NO_PREV_TRACK"
    NO_SPECIFIC_TRACK = "NO_SPECIFIC_TRACK"
    PREMIUM_REQUIRED = "PREMIUM_REQUIRED"
    RATE_LIMITED = "RATE_LIMITED"
    REMOTE_CONTROL_DISALLOW = "REMOTE_CONTROL_DISALLOW"
    UNKNOWN = "UNKNOWN"
    VOLUME_CONTROL_DISALLOW = "VOLUME_CONTROL_DISALLOW"

    def __str__(self) -> str:
        return str(self.value)
