
#                     !!! WARNING !!!
#             This is an auto-generated file!
#                 Generated by [Builder].
# Any manual modifications will be lost upon regeneration.
#             DO NOT EDIT THIS FILE DIRECTLY.

from .chats import TypeMessagesChats, Chats, ChatsSlice
from .bot_app import BotApp, TypeMessagesBotApp
from .dialogs import Dialogs, DialogsSlice, TypeMessagesDialogs, DialogsNotModified
from .web_page import WebPage, TypeMessagesWebPage
from .stickers import StickersNotModified, Stickers, TypeMessagesStickers
from .messages import MessagesSlice, TypeMessagesMessages, MessagesNotModified, ChannelMessages, Messages
from .chat_full import ChatFull, TypeMessagesChatFull
from .dh_config import DhConfigNotModified, DhConfig, TypeMessagesDhConfig
from .reactions import Reactions, ReactionsNotModified, TypeMessagesReactions
from .votes_list import TypeMessagesVotesList, VotesList
from .saved_gifs import SavedGifsNotModified, SavedGifs, TypeMessagesSavedGifs
from .bot_results import TypeMessagesBotResults, BotResults
from .high_scores import TypeMessagesHighScores, HighScores
from .my_stickers import TypeMessagesMyStickers, MyStickers
from .sticker_set import StickerSet, TypeMessagesStickerSet, StickerSetNotModified
from .peer_dialogs import TypeMessagesPeerDialogs, PeerDialogs
from .forum_topics import ForumTopics, TypeMessagesForumTopics
from .all_stickers import AllStickersNotModified, TypeMessagesAllStickers, AllStickers
from .emoji_groups import EmojiGroupsNotModified, TypeMessagesEmojiGroups, EmojiGroups
from .message_views import TypeMessagesMessageViews, MessageViews
from .peer_settings import PeerSettings, TypeMessagesPeerSettings
from .invited_users import TypeMessagesInvitedUsers, InvitedUsers
from .quick_replies import QuickRepliesNotModified, QuickReplies, TypeMessagesQuickReplies
from .saved_dialogs import SavedDialogsNotModified, TypeMessagesSavedDialogs, SavedDialogs, SavedDialogsSlice
from .search_counter import TypeMessagesSearchCounter, SearchCounter
from .inactive_chats import InactiveChats, TypeMessagesInactiveChats
from .history_import import TypeMessagesHistoryImport, HistoryImport
from .dialog_filters import DialogFilters, TypeMessagesDialogFilters
from .faved_stickers import FavedStickersNotModified, TypeMessagesFavedStickers, FavedStickers
from .found_stickers import TypeMessagesFoundStickers, FoundStickersNotModified, FoundStickers
from .translated_text import TypeMessagesTranslatedText, TranslateResult
from .recent_stickers import RecentStickersNotModified, TypeMessagesRecentStickers, RecentStickers
from .affected_history import TypeMessagesAffectedHistory, AffectedHistory
from .web_page_preview import WebPagePreview, TypeMessagesWebPagePreview
from .affected_messages import AffectedMessages, TypeMessagesAffectedMessages
from .message_edit_data import TypeMessagesMessageEditData, MessageEditData
from .archived_stickers import TypeMessagesArchivedStickers, ArchivedStickers
from .transcribed_audio import TypeMessagesTranscribedAudio, TranscribedAudio
from .featured_stickers import FeaturedStickers, TypeMessagesFeaturedStickers, FeaturedStickersNotModified
from .available_effects import TypeMessagesAvailableEffects, AvailableEffects, AvailableEffectsNotModified
from .discussion_message import TypeMessagesDiscussionMessage, DiscussionMessage
from .found_sticker_sets import FoundStickerSets, FoundStickerSetsNotModified, TypeMessagesFoundStickerSets
from .sponsored_messages import SponsoredMessagesEmpty, TypeMessagesSponsoredMessages, SponsoredMessages
from .bot_callback_answer import BotCallbackAnswer, TypeMessagesBotCallbackAnswer
from .available_reactions import TypeMessagesAvailableReactions, AvailableReactionsNotModified, AvailableReactions
from .saved_reaction_tags import TypeMessagesSavedReactionTags, SavedReactionTags, SavedReactionTagsNotModified
from .exported_chat_invite import ExportedChatInvite, TypeMessagesExportedChatInvite, ExportedChatInviteReplaced
from .history_import_parsed import HistoryImportParsed, TypeMessagesHistoryImportParsed
from .exported_chat_invites import ExportedChatInvites, TypeMessagesExportedChatInvites
from .chat_invite_importers import TypeMessagesChatInviteImporters, ChatInviteImporters
from .message_reactions_list import TypeMessagesMessageReactionsList, MessageReactionsList
from .sent_encrypted_message import TypeMessagesSentEncryptedMessage, SentEncryptedFile, SentEncryptedMessage
from .affected_found_messages import TypeMessagesAffectedFoundMessages, AffectedFoundMessages
from .search_results_calendar import TypeMessagesSearchResultsCalendar, SearchResultsCalendar
from .prepared_inline_message import TypeMessagesPreparedInlineMessage, PreparedInlineMessage
from .chat_admins_with_invites import TypeMessagesChatAdminsWithInvites, ChatAdminsWithInvites
from .search_results_positions import TypeMessagesSearchResultsPositions, SearchResultsPositions
from .sticker_set_install_result import StickerSetInstallResultSuccess, TypeMessagesStickerSetInstallResult, StickerSetInstallResultArchive
from .checked_history_import_peer import CheckedHistoryImportPeer, TypeMessagesCheckedHistoryImportPeer
from .bot_prepared_inline_message import TypeMessagesBotPreparedInlineMessage, BotPreparedInlineMessage

__all__ = [
    'InactiveChats',
    'TypeMessagesAffectedFoundMessages',
    'TypeMessagesWebPagePreview',
    'SavedReactionTagsNotModified',
    'Chats',
    'ChatAdminsWithInvites',
    'TypeMessagesDialogs',
    'TypeMessagesAffectedMessages',
    'DhConfigNotModified',
    'SavedDialogsNotModified',
    'TypeMessagesHistoryImport',
    'TypeMessagesAffectedHistory',
    'DialogsNotModified',
    'MessagesSlice',
    'TypeMessagesArchivedStickers',
    'BotPreparedInlineMessage',
    'MessageEditData',
    'AvailableEffectsNotModified',
    'ExportedChatInvites',
    'TypeMessagesRecentStickers',
    'ForumTopics',
    'TypeMessagesMyStickers',
    'TypeMessagesDhConfig',
    'AllStickers',
    'TypeMessagesInactiveChats',
    'TypeMessagesFavedStickers',
    'FoundStickersNotModified',
    'RecentStickersNotModified',
    'TypeMessagesDiscussionMessage',
    'FoundStickerSets',
    'TypeMessagesChatFull',
    'TypeMessagesVotesList',
    'HistoryImportParsed',
    'PreparedInlineMessage',
    'TypeMessagesSavedReactionTags',
    'QuickReplies',
    'SponsoredMessagesEmpty',
    'MyStickers',
    'Stickers',
    'StickerSetNotModified',
    'ChatInviteImporters',
    'TypeMessagesMessageReactionsList',
    'TypeMessagesTranslatedText',
    'TypeMessagesChats',
    'ReactionsNotModified',
    'RecentStickers',
    'TypeMessagesBotApp',
    'TypeMessagesMessageEditData',
    'TypeMessagesFoundStickerSets',
    'AllStickersNotModified',
    'TypeMessagesAllStickers',
    'AvailableReactionsNotModified',
    'TypeMessagesBotPreparedInlineMessage',
    'SentEncryptedFile',
    'FavedStickers',
    'TypeMessagesHighScores',
    'HistoryImport',
    'VotesList',
    'CheckedHistoryImportPeer',
    'InvitedUsers',
    'TypeMessagesSearchResultsCalendar',
    'AffectedHistory',
    'TypeMessagesTranscribedAudio',
    'TypeMessagesChatAdminsWithInvites',
    'DiscussionMessage',
    'TypeMessagesHistoryImportParsed',
    'EmojiGroups',
    'BotCallbackAnswer',
    'TranscribedAudio',
    'FoundStickers',
    'EmojiGroupsNotModified',
    'SearchCounter',
    'TypeMessagesSavedGifs',
    'ExportedChatInvite',
    'Reactions',
    'ChannelMessages',
    'TypeMessagesAvailableEffects',
    'ChatFull',
    'TypeMessagesStickerSetInstallResult',
    'SentEncryptedMessage',
    'TypeMessagesSearchResultsPositions',
    'SearchResultsPositions',
    'AvailableReactions',
    'TypeMessagesStickers',
    'BotResults',
    'TypeMessagesReactions',
    'TypeMessagesExportedChatInvites',
    'AvailableEffects',
    'TypeMessagesMessageViews',
    'DialogsSlice',
    'TranslateResult',
    'TypeMessagesAvailableReactions',
    'SavedGifs',
    'StickerSetInstallResultArchive',
    'WebPage',
    'TypeMessagesStickerSet',
    'TypeMessagesWebPage',
    'StickerSet',
    'AffectedFoundMessages',
    'StickerSetInstallResultSuccess',
    'MessagesNotModified',
    'SearchResultsCalendar',
    'QuickRepliesNotModified',
    'FeaturedStickers',
    'FoundStickerSetsNotModified',
    'Messages',
    'SavedReactionTags',
    'MessageReactionsList',
    'TypeMessagesBotCallbackAnswer',
    'Dialogs',
    'TypeMessagesMessages',
    'TypeMessagesSavedDialogs',
    'SavedDialogsSlice',
    'AffectedMessages',
    'TypeMessagesPeerDialogs',
    'TypeMessagesFeaturedStickers',
    'TypeMessagesExportedChatInvite',
    'TypeMessagesDialogFilters',
    'TypeMessagesCheckedHistoryImportPeer',
    'TypeMessagesBotResults',
    'TypeMessagesQuickReplies',
    'TypeMessagesPeerSettings',
    'TypeMessagesSentEncryptedMessage',
    'SponsoredMessages',
    'ExportedChatInviteReplaced',
    'TypeMessagesPreparedInlineMessage',
    'SavedGifsNotModified',
    'TypeMessagesSearchCounter',
    'SavedDialogs',
    'TypeMessagesEmojiGroups',
    'WebPagePreview',
    'TypeMessagesForumTopics',
    'ArchivedStickers',
    'TypeMessagesFoundStickers',
    'TypeMessagesSponsoredMessages',
    'BotApp',
    'TypeMessagesChatInviteImporters',
    'ChatsSlice',
    'TypeMessagesInvitedUsers',
    'HighScores',
    'PeerDialogs',
    'DialogFilters',
    'StickersNotModified',
    'FavedStickersNotModified',
    'MessageViews',
    'PeerSettings',
    'DhConfig',
    'FeaturedStickersNotModified'
]