
#                     !!! WARNING !!!
#             This is an auto-generated file!
#                 Generated by [Builder].
# Any manual modifications will be lost upon regeneration.
#             DO NOT EDIT THIS FILE DIRECTLY.

from typing import TYPE_CHECKING
from ....gadgets.tlobject import TLRequest
from ....gadgets.byteutils import Writer


if TYPE_CHECKING:
    from ...types.input_store_payment_purpose import TypeInputStorePaymentPurpose


class CanPurchasePremium(TLRequest[bool]):
    """
    Checks whether Telegram Premium purchase is possible. Must be called before in-store Premium purchase, official apps only.

    Raises:
        `406`PremiumCurrentlyUnavailableError: You cannot currently purchase a Premium subscription.

    """

    _id = 0X9FC19EB6
    _result_id = 0X43B904E1

    def __init__(
        self,
        purpose: 'TypeInputStorePaymentPurpose'
    ):

        """
        Checks whether Telegram Premium purchase is possible. Must be called before in-store Premium purchase, official apps only.

        Args:
            purpose ('TypeInputStorePaymentPurpose'): Payment purpose
        """

        self.purpose = purpose

    def to_bytes(self, boxed: bool=True):
        with Writer(b'\xb6\x9e\xc1\x9f' if boxed else b'') as writer:
            writer.object(
                self.purpose,
                group_id=0XECBAD07B
            )

            return writer.getvalue()