
#                     !!! WARNING !!!
#             This is an auto-generated file!
#                 Generated by [Builder].
# Any manual modifications will be lost upon regeneration.
#             DO NOT EDIT THIS FILE DIRECTLY.

from .chats import ChatsSlice, TypeMessagesChats, Chats
from .bot_app import BotApp, TypeMessagesBotApp
from .dialogs import DialogsSlice, TypeMessagesDialogs, Dialogs, DialogsNotModified
from .web_page import TypeMessagesWebPage, WebPage
from .stickers import Stickers, TypeMessagesStickers, StickersNotModified
from .messages import ChannelMessages, TypeMessagesMessages, Messages, MessagesNotModified, MessagesSlice
from .chat_full import ChatFull, TypeMessagesChatFull
from .dh_config import DhConfig, DhConfigNotModified, TypeMessagesDhConfig
from .reactions import TypeMessagesReactions, ReactionsNotModified, Reactions
from .votes_list import VotesList, TypeMessagesVotesList
from .saved_gifs import TypeMessagesSavedGifs, SavedGifs, SavedGifsNotModified
from .bot_results import BotResults, TypeMessagesBotResults
from .high_scores import HighScores, TypeMessagesHighScores
from .my_stickers import MyStickers, TypeMessagesMyStickers
from .sticker_set import StickerSetNotModified, TypeMessagesStickerSet, StickerSet
from .peer_dialogs import TypeMessagesPeerDialogs, PeerDialogs
from .forum_topics import TypeMessagesForumTopics, ForumTopics
from .all_stickers import AllStickers, AllStickersNotModified, TypeMessagesAllStickers
from .emoji_groups import EmojiGroups, EmojiGroupsNotModified, TypeMessagesEmojiGroups
from .message_views import MessageViews, TypeMessagesMessageViews
from .peer_settings import PeerSettings, TypeMessagesPeerSettings
from .invited_users import InvitedUsers, TypeMessagesInvitedUsers
from .quick_replies import TypeMessagesQuickReplies, QuickRepliesNotModified, QuickReplies
from .saved_dialogs import SavedDialogsSlice, TypeMessagesSavedDialogs, SavedDialogsNotModified, SavedDialogs
from .search_counter import SearchCounter, TypeMessagesSearchCounter
from .inactive_chats import TypeMessagesInactiveChats, InactiveChats
from .history_import import TypeMessagesHistoryImport, HistoryImport
from .dialog_filters import TypeMessagesDialogFilters, DialogFilters
from .faved_stickers import FavedStickers, FavedStickersNotModified, TypeMessagesFavedStickers
from .found_stickers import FoundStickers, TypeMessagesFoundStickers, FoundStickersNotModified
from .translated_text import TranslateResult, TypeMessagesTranslatedText
from .recent_stickers import RecentStickers, TypeMessagesRecentStickers, RecentStickersNotModified
from .affected_history import AffectedHistory, TypeMessagesAffectedHistory
from .web_page_preview import TypeMessagesWebPagePreview, WebPagePreview
from .affected_messages import AffectedMessages, TypeMessagesAffectedMessages
from .message_edit_data import TypeMessagesMessageEditData, MessageEditData
from .archived_stickers import TypeMessagesArchivedStickers, ArchivedStickers
from .transcribed_audio import TranscribedAudio, TypeMessagesTranscribedAudio
from .featured_stickers import TypeMessagesFeaturedStickers, FeaturedStickersNotModified, FeaturedStickers
from .available_effects import AvailableEffectsNotModified, AvailableEffects, TypeMessagesAvailableEffects
from .discussion_message import TypeMessagesDiscussionMessage, DiscussionMessage
from .found_sticker_sets import FoundStickerSetsNotModified, TypeMessagesFoundStickerSets, FoundStickerSets
from .sponsored_messages import SponsoredMessagesEmpty, SponsoredMessages, TypeMessagesSponsoredMessages
from .bot_callback_answer import BotCallbackAnswer, TypeMessagesBotCallbackAnswer
from .available_reactions import AvailableReactions, AvailableReactionsNotModified, TypeMessagesAvailableReactions
from .saved_reaction_tags import TypeMessagesSavedReactionTags, SavedReactionTags, SavedReactionTagsNotModified
from .exported_chat_invite import TypeMessagesExportedChatInvite, ExportedChatInviteReplaced, ExportedChatInvite
from .history_import_parsed import HistoryImportParsed, TypeMessagesHistoryImportParsed
from .exported_chat_invites import TypeMessagesExportedChatInvites, ExportedChatInvites
from .chat_invite_importers import ChatInviteImporters, TypeMessagesChatInviteImporters
from .message_reactions_list import MessageReactionsList, TypeMessagesMessageReactionsList
from .sent_encrypted_message import TypeMessagesSentEncryptedMessage, SentEncryptedFile, SentEncryptedMessage
from .affected_found_messages import TypeMessagesAffectedFoundMessages, AffectedFoundMessages
from .search_results_calendar import SearchResultsCalendar, TypeMessagesSearchResultsCalendar
from .prepared_inline_message import TypeMessagesPreparedInlineMessage, PreparedInlineMessage
from .chat_admins_with_invites import ChatAdminsWithInvites, TypeMessagesChatAdminsWithInvites
from .search_results_positions import TypeMessagesSearchResultsPositions, SearchResultsPositions
from .sticker_set_install_result import StickerSetInstallResultArchive, StickerSetInstallResultSuccess, TypeMessagesStickerSetInstallResult
from .checked_history_import_peer import CheckedHistoryImportPeer, TypeMessagesCheckedHistoryImportPeer
from .bot_prepared_inline_message import TypeMessagesBotPreparedInlineMessage, BotPreparedInlineMessage

__all__ = [
    'SearchCounter',
    'TypeMessagesTranslatedText',
    'TypeMessagesRecentStickers',
    'ChatsSlice',
    'DhConfigNotModified',
    'AvailableReactions',
    'TypeMessagesMessageEditData',
    'TypeMessagesFeaturedStickers',
    'FavedStickers',
    'TypeMessagesInvitedUsers',
    'ArchivedStickers',
    'TypeMessagesMyStickers',
    'AllStickers',
    'TypeMessagesMessageViews',
    'EmojiGroups',
    'TypeMessagesAvailableReactions',
    'BotCallbackAnswer',
    'TypeMessagesHighScores',
    'TypeMessagesWebPage',
    'TypeMessagesWebPagePreview',
    'Stickers',
    'MessageEditData',
    'TypeMessagesFoundStickerSets',
    'HistoryImport',
    'SponsoredMessagesEmpty',
    'TypeMessagesMessages',
    'BotResults',
    'TypeMessagesArchivedStickers',
    'TranscribedAudio',
    'TypeMessagesExportedChatInvite',
    'HistoryImportParsed',
    'SearchResultsPositions',
    'TypeMessagesInactiveChats',
    'TypeMessagesForumTopics',
    'TypeMessagesExportedChatInvites',
    'ExportedChatInvites',
    'WebPage',
    'StickersNotModified',
    'DiscussionMessage',
    'SearchResultsCalendar',
    'TypeMessagesQuickReplies',
    'Reactions',
    'SentEncryptedMessage',
    'TypeMessagesSentEncryptedMessage',
    'RecentStickers',
    'TypeMessagesDialogs',
    'TypeMessagesStickerSet',
    'TypeMessagesAllStickers',
    'BotApp',
    'MessageReactionsList',
    'DhConfig',
    'SponsoredMessages',
    'PreparedInlineMessage',
    'TypeMessagesBotPreparedInlineMessage',
    'TypeMessagesAffectedHistory',
    'MessagesSlice',
    'TypeMessagesSavedDialogs',
    'MessageViews',
    'ChatInviteImporters',
    'DialogFilters',
    'TypeMessagesSavedGifs',
    'TypeMessagesDialogFilters',
    'DialogsSlice',
    'Dialogs',
    'AllStickersNotModified',
    'TypeMessagesChatInviteImporters',
    'TypeMessagesBotCallbackAnswer',
    'TypeMessagesChatAdminsWithInvites',
    'AvailableEffectsNotModified',
    'ChatAdminsWithInvites',
    'AvailableEffects',
    'FoundStickerSets',
    'StickerSetInstallResultSuccess',
    'TypeMessagesReactions',
    'VotesList',
    'FavedStickersNotModified',
    'TypeMessagesCheckedHistoryImportPeer',
    'TranslateResult',
    'SavedGifs',
    'StickerSet',
    'QuickReplies',
    'TypeMessagesAffectedMessages',
    'CheckedHistoryImportPeer',
    'FoundStickerSetsNotModified',
    'Messages',
    'QuickRepliesNotModified',
    'ReactionsNotModified',
    'SavedDialogs',
    'TypeMessagesBotResults',
    'InactiveChats',
    'TypeMessagesFoundStickers',
    'TypeMessagesHistoryImportParsed',
    'EmojiGroupsNotModified',
    'RecentStickersNotModified',
    'TypeMessagesAvailableEffects',
    'DialogsNotModified',
    'TypeMessagesVotesList',
    'TypeMessagesSponsoredMessages',
    'FeaturedStickers',
    'PeerDialogs',
    'TypeMessagesDhConfig',
    'TypeMessagesStickerSetInstallResult',
    'AvailableReactionsNotModified',
    'WebPagePreview',
    'TypeMessagesTranscribedAudio',
    'TypeMessagesSearchResultsCalendar',
    'TypeMessagesSearchResultsPositions',
    'BotPreparedInlineMessage',
    'SavedDialogsNotModified',
    'InvitedUsers',
    'AffectedFoundMessages',
    'ChatFull',
    'TypeMessagesPreparedInlineMessage',
    'TypeMessagesChats',
    'Chats',
    'TypeMessagesPeerSettings',
    'TypeMessagesSearchCounter',
    'TypeMessagesEmojiGroups',
    'ExportedChatInviteReplaced',
    'ExportedChatInvite',
    'StickerSetNotModified',
    'TypeMessagesSavedReactionTags',
    'PeerSettings',
    'SavedReactionTags',
    'AffectedMessages',
    'SavedDialogsSlice',
    'TypeMessagesStickers',
    'TypeMessagesChatFull',
    'TypeMessagesHistoryImport',
    'TypeMessagesFavedStickers',
    'TypeMessagesDiscussionMessage',
    'FoundStickers',
    'TypeMessagesAffectedFoundMessages',
    'StickerSetInstallResultArchive',
    'TypeMessagesMessageReactionsList',
    'SavedReactionTagsNotModified',
    'HighScores',
    'MyStickers',
    'FoundStickersNotModified',
    'AffectedHistory',
    'ChannelMessages',
    'FeaturedStickersNotModified',
    'ForumTopics',
    'TypeMessagesBotApp',
    'SavedGifsNotModified',
    'SentEncryptedFile',
    'TypeMessagesPeerDialogs',
    'MessagesNotModified'
]