# Generated by Django 5.2.4 on 2025-08-28 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from oauth2_provider.settings import oauth2_settings

class Migration(migrations.Migration):

    dependencies = [
        ('mad_oauth2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='throttle',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=oauth2_settings.APPLICATION_MODEL),
        ),
        migrations.AddField(
            model_name='throttle',
            name='scopes',
            field=models.ManyToManyField(help_text='Scopes that this throttle rate applies to.', related_name='throttles', to='mad_oauth2.scope'),
        ),
        migrations.AlterField(
            model_name='throttle',
            name='scope',
            field=models.CharField(blank=True, help_text="If you have scope 'user:read' and 'user:write', scope here should be 'user' and it will throttle both.", max_length=255, null=True, unique=True),
        ),
    ]
