from enum import StrEnum


class Code(StrEnum):
    ANY_DATA = "MAL-RES-ADT-001"
    NO_DATA = "MAL-RES-NDT-001"
    SINGLE_DATA = "MAL-RES-SGD-001"
    CREATE_SINGLE_DATA = "MAL-RES-SGD-002"
    UPDATE_SINGLE_DATA = "MAL-RES-SGD-003"
    OPTIONAL_SINGLE_DATA = "MAL-RES-OSD-001"
    READ_SINGLE_DATA = "MAL-RES-OSD-002"
    DELETE_SINGLE_DATA = "MAL-RES-OSD-003"
    MULTIPLE_DATA = "MAL-RES-MTD-001"
    CREATE_MULTIPLE_DATA = "MAL-RES-MTD-002"
    UPDATE_MULTIPLE_DATA = "MAL-RES-MTD-003"
    OPTIONAL_MULTIPLE_DATA = "MAL-RES-OMD-001"
    READ_MULTIPLE_DATA = "MAL-RES-OMD-002"
    DELETE_MULTIPLE_DATA = "MAL-RES-OMD-003"
