from enum import StrEnum


class Code(StrEnum):
    ANY_DATA = "MAL-SCS-ADT-001"
    NO_DATA = "MAL-SCS-NDT-001"
    SINGLE_DATA = "MAL-SCS-SGD-001"
    CREATE_SINGLE_DATA = "MAL-SCS-SGD-002"
    UPDATE_SINGLE_DATA = "MAL-SCS-SGD-003"
    OPTIONAL_SINGLE_DATA = "MAL-SCS-OSD-001"
    READ_SINGLE_DATA = "MAL-SCS-OSD-002"
    DELETE_SINGLE_DATA = "MAL-SCS-OSD-003"
    MULTIPLE_DATA = "MAL-SCS-MTD-001"
    CREATE_MULTIPLE_DATA = "MAL-SCS-MTD-002"
    UPDATE_MULTIPLE_DATA = "MAL-SCS-MTD-003"
    OPTIONAL_MULTIPLE_DATA = "MAL-SCS-OMD-001"
    READ_MULTIPLE_DATA = "MAL-SCS-OMD-002"
    DELETE_MULTIPLE_DATA = "MAL-SCS-OMD-003"
