from __future__ import annotations

from typing import Protocol, Any


class ChartProtocol(Protocol):
    async def initialize(self) -> None: ...

    async def next(self) -> None: ...

    async def on_tick(self, tick: Any) -> None: ...

    @property
    def df(self) -> Any: ...

    @property
    def data(self) -> Any: ...

    @property
    def ltp(self) -> float: ...

    async def add_indicator(self, *, key: str, indicator: Any) -> Any: ...
