// This file was generated. DO NOT EDIT.
use crate::icons;
use pyo3::prelude::*;

pub(super) fn bind_part_32(m: &Bound<PyModule>) -> PyResult<()> {
    m.add("STORE_CHECK_OUTLINE", icons::STORE_CHECK_OUTLINE)?;
    m.add("STORE_CHECK", icons::STORE_CHECK)?;
    m.add("STORE_CLOCK_OUTLINE", icons::STORE_CLOCK_OUTLINE)?;
    m.add("STORE_CLOCK", icons::STORE_CLOCK)?;
    m.add("STORE_COG_OUTLINE", icons::STORE_COG_OUTLINE)?;
    m.add("STORE_COG", icons::STORE_COG)?;
    m.add("STORE_EDIT_OUTLINE", icons::STORE_EDIT_OUTLINE)?;
    m.add("STORE_EDIT", icons::STORE_EDIT)?;
    m.add("STORE_MARKER_OUTLINE", icons::STORE_MARKER_OUTLINE)?;
    m.add("STORE_MARKER", icons::STORE_MARKER)?;
    m.add("STORE_MINUS_OUTLINE", icons::STORE_MINUS_OUTLINE)?;
    m.add("STORE_MINUS", icons::STORE_MINUS)?;
    m.add("STORE_OFF_OUTLINE", icons::STORE_OFF_OUTLINE)?;
    m.add("STORE_OFF", icons::STORE_OFF)?;
    m.add("STORE_OUTLINE", icons::STORE_OUTLINE)?;
    m.add("STORE_PLUS_OUTLINE", icons::STORE_PLUS_OUTLINE)?;
    m.add("STORE_PLUS", icons::STORE_PLUS)?;
    m.add("STORE_REMOVE_OUTLINE", icons::STORE_REMOVE_OUTLINE)?;
    m.add("STORE_REMOVE", icons::STORE_REMOVE)?;
    m.add("STORE_SEARCH_OUTLINE", icons::STORE_SEARCH_OUTLINE)?;
    m.add("STORE_SEARCH", icons::STORE_SEARCH)?;
    m.add("STORE_SETTINGS_OUTLINE", icons::STORE_SETTINGS_OUTLINE)?;
    m.add("STORE_SETTINGS", icons::STORE_SETTINGS)?;
    m.add("STORE", icons::STORE)?;
    m.add("STOREFRONT_CHECK_OUTLINE", icons::STOREFRONT_CHECK_OUTLINE)?;
    m.add("STOREFRONT_CHECK", icons::STOREFRONT_CHECK)?;
    m.add("STOREFRONT_EDIT_OUTLINE", icons::STOREFRONT_EDIT_OUTLINE)?;
    m.add("STOREFRONT_EDIT", icons::STOREFRONT_EDIT)?;
    m.add("STOREFRONT_MINUS_OUTLINE", icons::STOREFRONT_MINUS_OUTLINE)?;
    m.add("STOREFRONT_MINUS", icons::STOREFRONT_MINUS)?;
    m.add("STOREFRONT_OUTLINE", icons::STOREFRONT_OUTLINE)?;
    m.add("STOREFRONT_PLUS_OUTLINE", icons::STOREFRONT_PLUS_OUTLINE)?;
    m.add("STOREFRONT_PLUS", icons::STOREFRONT_PLUS)?;
    m.add(
        "STOREFRONT_REMOVE_OUTLINE",
        icons::STOREFRONT_REMOVE_OUTLINE,
    )?;
    m.add("STOREFRONT_REMOVE", icons::STOREFRONT_REMOVE)?;
    m.add("STOREFRONT", icons::STOREFRONT)?;
    m.add("STOVE", icons::STOVE)?;
    m.add("STRATEGY", icons::STRATEGY)?;
    m.add("STRETCH_TO_PAGE_OUTLINE", icons::STRETCH_TO_PAGE_OUTLINE)?;
    m.add("STRETCH_TO_PAGE", icons::STRETCH_TO_PAGE)?;
    m.add("STRING_LIGHTS_OFF", icons::STRING_LIGHTS_OFF)?;
    m.add("STRING_LIGHTS", icons::STRING_LIGHTS)?;
    m.add("SUBDIRECTORY_ARROW_LEFT", icons::SUBDIRECTORY_ARROW_LEFT)?;
    m.add("SUBDIRECTORY_ARROW_RIGHT", icons::SUBDIRECTORY_ARROW_RIGHT)?;
    m.add("SUBMARINE", icons::SUBMARINE)?;
    m.add("SUBTITLES_OUTLINE", icons::SUBTITLES_OUTLINE)?;
    m.add("SUBTITLES", icons::SUBTITLES)?;
    m.add("SUBWAY_ALERT_VARIANT", icons::SUBWAY_ALERT_VARIANT)?;
    m.add("SUBWAY_VARIANT", icons::SUBWAY_VARIANT)?;
    m.add("SUBWAY", icons::SUBWAY)?;
    m.add("SUMMIT", icons::SUMMIT)?;
    m.add("SUN_ANGLE_OUTLINE", icons::SUN_ANGLE_OUTLINE)?;
    m.add("SUN_ANGLE", icons::SUN_ANGLE)?;
    m.add("SUN_CLOCK_OUTLINE", icons::SUN_CLOCK_OUTLINE)?;
    m.add("SUN_CLOCK", icons::SUN_CLOCK)?;
    m.add("SUN_COMPASS", icons::SUN_COMPASS)?;
    m.add("SUN_SNOWFLAKE_VARIANT", icons::SUN_SNOWFLAKE_VARIANT)?;
    m.add("SUN_SNOWFLAKE", icons::SUN_SNOWFLAKE)?;
    m.add("SUN_THERMOMETER_OUTLINE", icons::SUN_THERMOMETER_OUTLINE)?;
    m.add("SUN_THERMOMETER", icons::SUN_THERMOMETER)?;
    m.add("SUN_WIRELESS_OUTLINE", icons::SUN_WIRELESS_OUTLINE)?;
    m.add("SUN_WIRELESS", icons::SUN_WIRELESS)?;
    m.add("SUNGLASSES", icons::SUNGLASSES)?;
    m.add("SURFING", icons::SURFING)?;
    m.add("SURROUND_SOUND_2_0", icons::SURROUND_SOUND_2_0)?;
    m.add("SURROUND_SOUND_2_1", icons::SURROUND_SOUND_2_1)?;
    m.add("SURROUND_SOUND_3_1", icons::SURROUND_SOUND_3_1)?;
    m.add("SURROUND_SOUND_5_1_2", icons::SURROUND_SOUND_5_1_2)?;
    m.add("SURROUND_SOUND_5_1", icons::SURROUND_SOUND_5_1)?;
    m.add("SURROUND_SOUND_7_1", icons::SURROUND_SOUND_7_1)?;
    m.add("SURROUND_SOUND", icons::SURROUND_SOUND)?;
    #[allow(deprecated)]
    m.add("SVG", icons::SVG)?;
    m.add("SWAP_HORIZONTAL_BOLD", icons::SWAP_HORIZONTAL_BOLD)?;
    m.add(
        "SWAP_HORIZONTAL_CIRCLE_OUTLINE",
        icons::SWAP_HORIZONTAL_CIRCLE_OUTLINE,
    )?;
    m.add("SWAP_HORIZONTAL_CIRCLE", icons::SWAP_HORIZONTAL_CIRCLE)?;
    m.add("SWAP_HORIZONTAL_HIDDEN", icons::SWAP_HORIZONTAL_HIDDEN)?;
    m.add("SWAP_HORIZONTAL_VARIANT", icons::SWAP_HORIZONTAL_VARIANT)?;
    m.add("SWAP_HORIZONTAL", icons::SWAP_HORIZONTAL)?;
    m.add("SWAP_VERTICAL_BOLD", icons::SWAP_VERTICAL_BOLD)?;
    m.add(
        "SWAP_VERTICAL_CIRCLE_OUTLINE",
        icons::SWAP_VERTICAL_CIRCLE_OUTLINE,
    )?;
    m.add("SWAP_VERTICAL_CIRCLE", icons::SWAP_VERTICAL_CIRCLE)?;
    m.add("SWAP_VERTICAL_VARIANT", icons::SWAP_VERTICAL_VARIANT)?;
    m.add("SWAP_VERTICAL", icons::SWAP_VERTICAL)?;
    m.add("SWIM", icons::SWIM)?;
    m.add("SWITCH", icons::SWITCH)?;
    m.add("SWORD_CROSS", icons::SWORD_CROSS)?;
    m.add("SWORD", icons::SWORD)?;
    m.add("SYLLABARY_HANGUL", icons::SYLLABARY_HANGUL)?;
    m.add("SYLLABARY_HIRAGANA", icons::SYLLABARY_HIRAGANA)?;
    m.add(
        "SYLLABARY_KATAKANA_HALFWIDTH",
        icons::SYLLABARY_KATAKANA_HALFWIDTH,
    )?;
    m.add("SYLLABARY_KATAKANA", icons::SYLLABARY_KATAKANA)?;
    m.add("SYMBOL", icons::SYMBOL)?;
    #[allow(deprecated)]
    m.add("SYMFONY", icons::SYMFONY)?;
    m.add("SYNAGOGUE_OUTLINE", icons::SYNAGOGUE_OUTLINE)?;
    m.add("SYNAGOGUE", icons::SYNAGOGUE)?;
    m.add("SYNC_ALERT", icons::SYNC_ALERT)?;
    m.add("SYNC_CIRCLE", icons::SYNC_CIRCLE)?;
    m.add("SYNC_OFF", icons::SYNC_OFF)?;
    m.add("SYNC", icons::SYNC)?;
    m.add("TAB_MINUS", icons::TAB_MINUS)?;
    m.add("TAB_PLUS", icons::TAB_PLUS)?;
    m.add("TAB_REMOVE", icons::TAB_REMOVE)?;
    m.add("TAB_SEARCH", icons::TAB_SEARCH)?;
    m.add("TAB_UNSELECTED", icons::TAB_UNSELECTED)?;
    m.add("TAB", icons::TAB)?;
    m.add("TABLE_ACCOUNT", icons::TABLE_ACCOUNT)?;
    m.add("TABLE_ALERT", icons::TABLE_ALERT)?;
    m.add("TABLE_ARROW_DOWN", icons::TABLE_ARROW_DOWN)?;
    m.add("TABLE_ARROW_LEFT", icons::TABLE_ARROW_LEFT)?;
    m.add("TABLE_ARROW_RIGHT", icons::TABLE_ARROW_RIGHT)?;
    m.add("TABLE_ARROW_UP", icons::TABLE_ARROW_UP)?;
    m.add("TABLE_BORDER", icons::TABLE_BORDER)?;
    m.add("TABLE_CANCEL", icons::TABLE_CANCEL)?;
    m.add("TABLE_CHAIR", icons::TABLE_CHAIR)?;
    m.add("TABLE_CHECK", icons::TABLE_CHECK)?;
    m.add("TABLE_CLOCK", icons::TABLE_CLOCK)?;
    m.add("TABLE_COG", icons::TABLE_COG)?;
    m.add("TABLE_COLUMN_PLUS_AFTER", icons::TABLE_COLUMN_PLUS_AFTER)?;
    m.add("TABLE_COLUMN_PLUS_BEFORE", icons::TABLE_COLUMN_PLUS_BEFORE)?;
    m.add("TABLE_COLUMN_REMOVE", icons::TABLE_COLUMN_REMOVE)?;
    m.add("TABLE_COLUMN_WIDTH", icons::TABLE_COLUMN_WIDTH)?;
    m.add("TABLE_COLUMN", icons::TABLE_COLUMN)?;
    m.add("TABLE_EDIT", icons::TABLE_EDIT)?;
    m.add("TABLE_EYE_OFF", icons::TABLE_EYE_OFF)?;
    m.add("TABLE_EYE", icons::TABLE_EYE)?;
    m.add("TABLE_FILTER", icons::TABLE_FILTER)?;
    m.add("TABLE_FURNITURE", icons::TABLE_FURNITURE)?;
    m.add("TABLE_HEADERS_EYE_OFF", icons::TABLE_HEADERS_EYE_OFF)?;
    m.add("TABLE_HEADERS_EYE", icons::TABLE_HEADERS_EYE)?;
    m.add("TABLE_HEART", icons::TABLE_HEART)?;
    m.add("TABLE_KEY", icons::TABLE_KEY)?;
    m.add("TABLE_LARGE_PLUS", icons::TABLE_LARGE_PLUS)?;
    m.add("TABLE_LARGE_REMOVE", icons::TABLE_LARGE_REMOVE)?;
    m.add("TABLE_LARGE", icons::TABLE_LARGE)?;
    m.add("TABLE_LOCK", icons::TABLE_LOCK)?;
    m.add("TABLE_MERGE_CELLS", icons::TABLE_MERGE_CELLS)?;
    m.add("TABLE_MINUS", icons::TABLE_MINUS)?;
    m.add("TABLE_MULTIPLE", icons::TABLE_MULTIPLE)?;
    m.add("TABLE_NETWORK", icons::TABLE_NETWORK)?;
    m.add("TABLE_OF_CONTENTS", icons::TABLE_OF_CONTENTS)?;
    m.add("TABLE_OFF", icons::TABLE_OFF)?;
    m.add("TABLE_PICNIC", icons::TABLE_PICNIC)?;
    m.add("TABLE_PIVOT", icons::TABLE_PIVOT)?;
    m.add("TABLE_PLUS", icons::TABLE_PLUS)?;
    m.add("TABLE_QUESTION", icons::TABLE_QUESTION)?;
    m.add("TABLE_REFRESH", icons::TABLE_REFRESH)?;
    m.add("TABLE_REMOVE", icons::TABLE_REMOVE)?;
    m.add("TABLE_ROW_HEIGHT", icons::TABLE_ROW_HEIGHT)?;
    m.add("TABLE_ROW_PLUS_AFTER", icons::TABLE_ROW_PLUS_AFTER)?;
    m.add("TABLE_ROW_PLUS_BEFORE", icons::TABLE_ROW_PLUS_BEFORE)?;
    m.add("TABLE_ROW_REMOVE", icons::TABLE_ROW_REMOVE)?;
    m.add("TABLE_ROW", icons::TABLE_ROW)?;
    m.add("TABLE_SEARCH", icons::TABLE_SEARCH)?;
    m.add("TABLE_SETTINGS", icons::TABLE_SETTINGS)?;
    m.add("TABLE_SPLIT_CELL", icons::TABLE_SPLIT_CELL)?;
    m.add("TABLE_STAR", icons::TABLE_STAR)?;
    m.add("TABLE_SYNC", icons::TABLE_SYNC)?;
    m.add("TABLE_TENNIS", icons::TABLE_TENNIS)?;
    m.add("TABLE", icons::TABLE)?;
    m.add("TABLET_CELLPHONE", icons::TABLET_CELLPHONE)?;
    m.add("TABLET_DASHBOARD", icons::TABLET_DASHBOARD)?;
    m.add("TABLET", icons::TABLET)?;
    m.add("TACO", icons::TACO)?;
    m.add("TAG_ARROW_DOWN_OUTLINE", icons::TAG_ARROW_DOWN_OUTLINE)?;
    m.add("TAG_ARROW_DOWN", icons::TAG_ARROW_DOWN)?;
    m.add("TAG_ARROW_LEFT_OUTLINE", icons::TAG_ARROW_LEFT_OUTLINE)?;
    m.add("TAG_ARROW_LEFT", icons::TAG_ARROW_LEFT)?;
    m.add("TAG_ARROW_RIGHT_OUTLINE", icons::TAG_ARROW_RIGHT_OUTLINE)?;
    m.add("TAG_ARROW_RIGHT", icons::TAG_ARROW_RIGHT)?;
    m.add("TAG_ARROW_UP_OUTLINE", icons::TAG_ARROW_UP_OUTLINE)?;
    m.add("TAG_ARROW_UP", icons::TAG_ARROW_UP)?;
    m.add("TAG_CHECK_OUTLINE", icons::TAG_CHECK_OUTLINE)?;
    m.add("TAG_CHECK", icons::TAG_CHECK)?;
    m.add("TAG_EDIT_OUTLINE", icons::TAG_EDIT_OUTLINE)?;
    m.add("TAG_EDIT", icons::TAG_EDIT)?;
    m.add("TAG_FACES", icons::TAG_FACES)?;
    m.add("TAG_HEART_OUTLINE", icons::TAG_HEART_OUTLINE)?;
    m.add("TAG_HEART", icons::TAG_HEART)?;
    m.add("TAG_HIDDEN", icons::TAG_HIDDEN)?;
    m.add("TAG_MINUS_OUTLINE", icons::TAG_MINUS_OUTLINE)?;
    m.add("TAG_MINUS", icons::TAG_MINUS)?;
    m.add("TAG_MULTIPLE_OUTLINE", icons::TAG_MULTIPLE_OUTLINE)?;
    m.add("TAG_MULTIPLE", icons::TAG_MULTIPLE)?;
    m.add("TAG_OFF_OUTLINE", icons::TAG_OFF_OUTLINE)?;
    m.add("TAG_OFF", icons::TAG_OFF)?;
    m.add("TAG_OUTLINE", icons::TAG_OUTLINE)?;
    m.add("TAG_PLUS_OUTLINE", icons::TAG_PLUS_OUTLINE)?;
    m.add("TAG_PLUS", icons::TAG_PLUS)?;
    m.add("TAG_REMOVE_OUTLINE", icons::TAG_REMOVE_OUTLINE)?;
    m.add("TAG_REMOVE", icons::TAG_REMOVE)?;
    m.add("TAG_SEARCH_OUTLINE", icons::TAG_SEARCH_OUTLINE)?;
    m.add("TAG_SEARCH", icons::TAG_SEARCH)?;
    m.add("TAG_TEXT_OUTLINE", icons::TAG_TEXT_OUTLINE)?;
    m.add("TAG_TEXT", icons::TAG_TEXT)?;
    m.add("TAG", icons::TAG)?;
    #[allow(deprecated)]
    m.add("TAILWIND", icons::TAILWIND)?;
    m.add("TALLY_MARK_1", icons::TALLY_MARK_1)?;
    m.add("TALLY_MARK_2", icons::TALLY_MARK_2)?;
    m.add("TALLY_MARK_3", icons::TALLY_MARK_3)?;
    m.add("TALLY_MARK_4", icons::TALLY_MARK_4)?;
    Ok(())
}
