
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-08-30T20:06:28+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "82d7c0f226cec44992cb7c28f3502092d8456342",
 "version": "1.9.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
