# coding: utf-8

"""
    QAnswer: Api Documentation

    APIs provided by QAnswer

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qanswer-sdk.api.task_rdf_linker_api import TaskRDFLinkerApi


class TestTaskRDFLinkerApi(unittest.TestCase):
    """TaskRDFLinkerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TaskRDFLinkerApi()

    def tearDown(self) -> None:
        pass

    def test_aggregate(self) -> None:
        """Test case for aggregate

        Aggregate the link dataset for a given Knowledge graph.
        """
        pass

    def test_analyze(self) -> None:
        """Test case for analyze

        Analyze a linker of an RDF connector.
        """
        pass

    def test_delete1(self) -> None:
        """Test case for delete1

        Delete the linkers of an RDF dataset connector.
        """
        pass

    def test_evaluate_csv(self) -> None:
        """Test case for evaluate_csv

        Get back all links that were asked in CSV
        """
        pass

    def test_evaluate_skos(self) -> None:
        """Test case for evaluate_skos

        Get back all links that were asked in CSV
        """
        pass

    def test_link1(self) -> None:
        """Test case for link1

        """
        pass

    def test_list(self) -> None:
        """Test case for list

        List all the linkers of an RDF dataset connector.
        """
        pass

    def test_order_evaluate(self) -> None:
        """Test case for order_evaluate

        Evaluate the link dataset for a given Knowledge graph.
        """
        pass

    def test_post_aggregate(self) -> None:
        """Test case for post_aggregate

        """
        pass

    def test_post_order_evaluate(self) -> None:
        """Test case for post_order_evaluate

        """
        pass

    def test_put_aggregate(self) -> None:
        """Test case for put_aggregate

        """
        pass

    def test_train(self) -> None:
        """Test case for train

        """
        pass

    def test_upload_labels(self) -> None:
        """Test case for upload_labels

        Upload a new list of labels to link.
        """
        pass

    def test_upload_labels1(self) -> None:
        """Test case for upload_labels1

        Upload a new list of labels to link.
        """
        pass


if __name__ == '__main__':
    unittest.main()
