"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from uai_annotation_requests.types import BaseModel


class ClipReferenceIDSelectionTypedDict(TypedDict):
    r"""Selects the clips to perform an operation on, omitting the array means all clips of
    the annotation request should be processed.
    """

    clip_reference_ids: NotRequired[List[str]]


class ClipReferenceIDSelection(BaseModel):
    r"""Selects the clips to perform an operation on, omitting the array means all clips of
    the annotation request should be processed.
    """

    clip_reference_ids: Annotated[
        Optional[List[str]], pydantic.Field(alias="clipReferenceIds")
    ] = None
