from crawlo.items import Item, Field

class RadioApprovalItem(Item):
    approval_number = Field()
    device_name = Field()
    device_model = Field()
    applicant = Field()
    remarks = Field()
    validity_period = Field()
    frequency_tolerance = Field()
    frequency_range = Field()
    transmit_power = Field()
    occupied_bandwidth = Field()
    spurious_emission_limit = Field()
    issue_date = Field()
    approval_code = Field()
    cmiit_id = Field()
    modulation_mode = Field()
    technology_system = Field()
    mid = Field()

class TelecomLicenseItem(Item):
    license_number = Field()
    device_name = Field()
    device_model = Field()
    applicant = Field()
    manufacturer = Field()
    issue_date = Field()
    expiry_date = Field()
    certificate_type = Field()
    remarks = Field()
    certificate_status = Field()
    origin = Field()
    article_id = Field()
    article_edit_date = Field()
    create_time = Field()