"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class ClipBusinessState(str, Enum):
    DATA_INTAKE = "Data Intake"
    IMPORT = "Import"
    ANNOTATION = "Annotation"
    DELIVERED = "Delivered"
    ACCEPTED = "Accepted"
    REJECTED = "Rejected"
    EXPORTED = "Exported"
