# coding: utf-8

"""
    QAnswer: Api Documentation

    APIs provided by QAnswer

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qanswer-sdk.models.report_copilot_template import ReportCopilotTemplate

class TestReportCopilotTemplate(unittest.TestCase):
    """ReportCopilotTemplate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReportCopilotTemplate:
        """Test ReportCopilotTemplate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReportCopilotTemplate`
        """
        model = ReportCopilotTemplate()
        if include_optional:
            return ReportCopilotTemplate(
                id = 56,
                username = '',
                template_name = '',
                creation_date = '',
                last_updated = '',
                template_with_slots = '',
                slots = [
                    qanswer-sdk.models.slot.Slot(
                        id = 56, 
                        node_id = '', 
                        prompt = '', 
                        completion = '', 
                        sources = [
                            qanswer-sdk.models.source.Source(
                                title = '', 
                                document = '', 
                                document_with_highlights = '', 
                                from_page = 56, 
                                to_page = 56, 
                                source_url = '', 
                                source_type = '', 
                                file_type = '', 
                                file_id = '', 
                                display_name = '', 
                                file_name = '', 
                                original_file_name = '', 
                                connector_type = '', 
                                connector_id = 56, 
                                additional_fields = qanswer-sdk.models.additional_fields.additional_fields(), 
                                ref_id = '', 
                                favicon = '', 
                                username = '', 
                                dataset = '', 
                                last_updated_at = '', )
                            ], 
                        metadata_filters = [
                            [
                                qanswer-sdk.models.search_metadata_filter.SearchMetadataFilter(
                                    key = '', 
                                    value = qanswer-sdk.models.value.value(), )
                                ]
                            ], 
                        mode = 'rag', 
                        is_input_data_cropped = True, 
                        task_settings = qanswer-sdk.models.report_copilot_slot_task_settings.ReportCopilotSlotTaskSettings(
                            prompt = '', 
                            llm_choice = '', 
                            bot_seed = 56, 
                            bot_temperature = 1.337, 
                            bot_answer_length = 'short', 
                            number_of_references = 56, 
                            stream_speed = 1.337, 
                            context_window = 56, 
                            max_tokens = 56, 
                            bot_name = '', 
                            bot_description = '', 
                            llm_details = qanswer-sdk.models.llm_details.LLMDetails(
                                onpremise = True, 
                                description = '', 
                                display_name = '', 
                                name = '', 
                                sensitivity_label = '', 
                                min_context_window = 56, 
                                max_context_window = 56, 
                                modality = 'text', ), 
                            id = 56, ), )
                    ]
            )
        else:
            return ReportCopilotTemplate(
                id = 56,
                username = '',
                template_name = '',
                creation_date = '',
                last_updated = '',
                template_with_slots = '',
                slots = [
                    qanswer-sdk.models.slot.Slot(
                        id = 56, 
                        node_id = '', 
                        prompt = '', 
                        completion = '', 
                        sources = [
                            qanswer-sdk.models.source.Source(
                                title = '', 
                                document = '', 
                                document_with_highlights = '', 
                                from_page = 56, 
                                to_page = 56, 
                                source_url = '', 
                                source_type = '', 
                                file_type = '', 
                                file_id = '', 
                                display_name = '', 
                                file_name = '', 
                                original_file_name = '', 
                                connector_type = '', 
                                connector_id = 56, 
                                additional_fields = qanswer-sdk.models.additional_fields.additional_fields(), 
                                ref_id = '', 
                                favicon = '', 
                                username = '', 
                                dataset = '', 
                                last_updated_at = '', )
                            ], 
                        metadata_filters = [
                            [
                                qanswer-sdk.models.search_metadata_filter.SearchMetadataFilter(
                                    key = '', 
                                    value = qanswer-sdk.models.value.value(), )
                                ]
                            ], 
                        mode = 'rag', 
                        is_input_data_cropped = True, 
                        task_settings = qanswer-sdk.models.report_copilot_slot_task_settings.ReportCopilotSlotTaskSettings(
                            prompt = '', 
                            llm_choice = '', 
                            bot_seed = 56, 
                            bot_temperature = 1.337, 
                            bot_answer_length = 'short', 
                            number_of_references = 56, 
                            stream_speed = 1.337, 
                            context_window = 56, 
                            max_tokens = 56, 
                            bot_name = '', 
                            bot_description = '', 
                            llm_details = qanswer-sdk.models.llm_details.LLMDetails(
                                onpremise = True, 
                                description = '', 
                                display_name = '', 
                                name = '', 
                                sensitivity_label = '', 
                                min_context_window = 56, 
                                max_context_window = 56, 
                                modality = 'text', ), 
                            id = 56, ), )
                    ],
        )
        """

    def testReportCopilotTemplate(self):
        """Test ReportCopilotTemplate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
