# coding: utf-8

"""
    QAnswer 2.0

    QAnswer 2.0 API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from freetext-sdk.api.pinecone_connector_api import PineconeConnectorApi


class TestPineconeConnectorApi(unittest.TestCase):
    """PineconeConnectorApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PineconeConnectorApi()

    def tearDown(self) -> None:
        pass

    def test_create_pinecone_connector(self) -> None:
        """Test case for create_pinecone_connector

        Create Pinecone Connector
        """
        pass

    def test_fetch_indexes_from_pinecone(self) -> None:
        """Test case for fetch_indexes_from_pinecone

        Fetch Indexes From Pinecone
        """
        pass

    def test_register_pinecone_connector(self) -> None:
        """Test case for register_pinecone_connector

        Register Pinecone Connector
        """
        pass


if __name__ == '__main__':
    unittest.main()
