# coding: utf-8

"""
    QAnswer 2.0

    QAnswer 2.0 API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from freetext-sdk.models.llm_endpoint_update import LLMEndpointUpdate

class TestLLMEndpointUpdate(unittest.TestCase):
    """LLMEndpointUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LLMEndpointUpdate:
        """Test LLMEndpointUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LLMEndpointUpdate`
        """
        model = LLMEndpointUpdate()
        if include_optional:
            return LLMEndpointUpdate(
                modality = 'text',
                provider = 'openai',
                api_version = '',
                aws_access_key_id = '',
                aws_secret_access_key = '',
                aws_region_name = '',
                description = '',
                onpremise = True,
                sensitivity_label = '',
                guardrail = freetext-sdk.models.guardrail_endpoint.GuardrailEndpoint(
                    disabled = True, 
                    io_guardrail_disabled = True, 
                    io_guardrail_mode = 'in', 
                    io_guardrail_level = 'warning', 
                    io_guardrail_prompt = '', 
                    jailbreak_guardrail_disabled = True, 
                    jailbreak_guardrail_prompt = '', 
                    endpoint_id = 56, ),
                retry_params = freetext-sdk.models.retry_params.RetryParams(
                    max_retries = 56, 
                    exp_multiplier = 1.337, ),
                extra_body = freetext-sdk.models.extra_body.ExtraBody(
                    provider = freetext-sdk.models.provider.Provider(
                        order = [
                            ''
                            ], ), ),
                tags = [
                    ''
                    ],
                display_name = '',
                engine = '',
                api_key = '',
                endpoint_url = '',
                rag_params = freetext-sdk.models.rag_params.RAGParams(
                    context_window = 56, 
                    min_context_window = 56, ),
                generation_params = freetext-sdk.models.generation_params.GenerationParams(
                    max_new_tokens = 56, 
                    max_context_window = 56, )
            )
        else:
            return LLMEndpointUpdate(
        )
        """

    def testLLMEndpointUpdate(self):
        """Test LLMEndpointUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
