# coding: utf-8

"""
    QAnswer 2.0

    QAnswer 2.0 API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from freetext-sdk.api.e_consilium_search_connector_api import EConsiliumSearchConnectorApi


class TestEConsiliumSearchConnectorApi(unittest.TestCase):
    """EConsiliumSearchConnectorApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EConsiliumSearchConnectorApi()

    def tearDown(self) -> None:
        pass

    def test_create_econsilium_search_connector(self) -> None:
        """Test case for create_econsilium_search_connector

        Create Econsilium Search Connector
        """
        pass


if __name__ == '__main__':
    unittest.main()
