
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-09-01T12:18:51-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "e3824eb40447960779a3455f5f3f01a07920a74c",
 "version": "0.4.30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
