"""GDSFactoryplus python library."""

from __future__ import annotations

import lazy_loader

__getattr__, __dir__, __all__ = lazy_loader.attach_stub(__name__, __file__)

__all__ = [
    "ComponentRecord",
    "F",
    "FactoryRecord",
    "FrozenPdk",
    "LogMessage",
    "Logger",
    "ReloadFactoriesMessage",
    "ReloadLayoutMessage",
    "ReloadSchematicMessage",
    "RestartServerMessage",
    "User",
    "__version__",
    "add_components",
    "add_factories",
    "build_by_names",
    "clear_cells_from_cache",
    "create_callgraph",
    "deduplicate",
    "extract_function_arguments",
    "find_partial_definition",
    "find_project_dir",
    "find_source_path",
    "generate_multipolygon",
    "generate_svg",
    "get_all_factories",
    "get_all_factory_names",
    "get_base_pdk",
    "get_base_schema",
    "get_cells_from_regex",
    "get_components_by_factories",
    "get_factories_by_components",
    "get_factories_by_idxs",
    "get_factories_by_name",
    "get_factory_sources_by_name",
    "get_logger",
    "get_netlist_schema",
    "get_pdk",
    "get_pdk_import_name",
    "get_ports",
    "get_runtime_factories_dependency_graph",
    "get_runtime_factory_dependencies",
    "get_settings",
    "get_static_factory_dependencies",
    "get_static_records",
    "get_static_records_by_path",
    "get_svg",
    "get_tags",
    "get_ws_port",
    "import_modules",
    "import_path",
    "import_picyml",
    "import_reload",
    "lazy_import",
    "lazy_setattr",
    "maybe_find_project_dir",
    "merge_rdb_strings",
    "patch_kcl",
    "plot_callgraph",
    "register_cells",
    "remove_components",
    "remove_components_by_factories",
    "remove_factories",
    "resolve_modname",
    "send_message",
    "try_func",
    "unlazy",
    "validate_access",
]
