# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: action.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'action.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import enums_pb2 as enums__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61\x63tion.proto\x1a\x0b\x65nums.proto\"o\n\x12SwitchActiveAction\x12!\n\x0c\x63haracter_id\x18\x02 \x01(\x11R\x0b\x63haracterId\x12\x36\n\x17\x63haracter_definition_id\x18\x03 \x01(\rR\x15\x63haracterDefinitionId\"\xa4\x01\n\x0ePlayCardAction\x12\x17\n\x07\x63\x61rd_id\x18\x02 \x01(\x11R\x06\x63\x61rdId\x12,\n\x12\x63\x61rd_definition_id\x18\x05 \x01(\rR\x10\x63\x61rdDefinitionId\x12\x1d\n\ntarget_ids\x18\x03 \x03(\x11R\ttargetIds\x12,\n\x12will_be_effectless\x18\x04 \x01(\x08R\x10willBeEffectless\"\xb1\x01\n\x0eUseSkillAction\x12.\n\x13skill_definition_id\x18\x02 \x01(\x05R\x11skillDefinitionId\x12\x1d\n\ntarget_ids\x18\x03 \x03(\x11R\ttargetIds\x12\x36\n\x15main_damage_target_id\x18\x04 \x01(\x11H\x00R\x12mainDamageTargetId\x88\x01\x01\x42\x18\n\x16_main_damage_target_id\"k\n\x15\x45lementalTuningAction\x12&\n\x0fremoved_card_id\x18\x02 \x01(\x11R\rremovedCardId\x12*\n\x0btarget_dice\x18\x03 \x01(\x0e\x32\t.DiceTypeR\ntargetDice\"\x12\n\x10\x44\x65\x63lareEndActionB\x1d\x42\x0b\x41\x63tionProtoP\x01\xaa\x02\x0bGiTcg.Protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'action_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\013ActionProtoP\001\252\002\013GiTcg.Proto'
  _globals['_SWITCHACTIVEACTION']._serialized_start=29
  _globals['_SWITCHACTIVEACTION']._serialized_end=140
  _globals['_PLAYCARDACTION']._serialized_start=143
  _globals['_PLAYCARDACTION']._serialized_end=307
  _globals['_USESKILLACTION']._serialized_start=310
  _globals['_USESKILLACTION']._serialized_end=487
  _globals['_ELEMENTALTUNINGACTION']._serialized_start=489
  _globals['_ELEMENTALTUNINGACTION']._serialized_end=596
  _globals['_DECLAREENDACTION']._serialized_start=598
  _globals['_DECLAREENDACTION']._serialized_end=616
# @@protoc_insertion_point(module_scope)
