# Generated by Django 5.2.5 on 2025-08-19 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_scrapyd_manager', '0002_alter_project_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='spider',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='django_scrapyd_manager.spider', verbose_name='爬虫'),
        ),
        migrations.AlterField(
            model_name='project',
            name='node',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='django_scrapyd_manager.node', verbose_name='节点'),
        ),
        migrations.AlterField(
            model_name='spider',
            name='name',
            field=models.CharField(max_length=255, verbose_name='爬虫名称'),
        ),
        migrations.AlterField(
            model_name='spider',
            name='project',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='django_scrapyd_manager.project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='spidergroup',
            name='spiders',
            field=models.ManyToManyField(db_constraint=False, to='django_scrapyd_manager.spider', verbose_name='爬虫'),
        ),
    ]
