from __future__ import annotations

from typing import Protocol


class ILogger(Protocol):
    def info(self, message: str) -> None: ...
    def warning(self, message: str) -> None: ...
    def error(self, message: str) -> None: ...
    def debug(self, message: str) -> None: ...
    def critical(self, message: str) -> None: ...
    def exception(self, message: str, exc: Exception | None = None) -> None: ...
    def fatal(self, message: str) -> None: ...
    def log(self, level: int, message: str) -> None: ...
    def isEnabledFor(self, level: int) -> bool: ...
