
#                     !!! WARNING !!!
#             This is an auto-generated file!
#                 Generated by [Builder].
# Any manual modifications will be lost upon regeneration.
#             DO NOT EDIT THIS FILE DIRECTLY.

from .chats import TypeMessagesChats, ChatsSlice, Chats
from .bot_app import BotApp, TypeMessagesBotApp
from .dialogs import DialogsNotModified, Dialogs, DialogsSlice, TypeMessagesDialogs
from .web_page import TypeMessagesWebPage, WebPage
from .stickers import Stickers, TypeMessagesStickers, StickersNotModified
from .messages import TypeMessagesMessages, ChannelMessages, Messages, MessagesNotModified, MessagesSlice
from .chat_full import ChatFull, TypeMessagesChatFull
from .dh_config import DhConfig, TypeMessagesDhConfig, DhConfigNotModified
from .reactions import Reactions, ReactionsNotModified, TypeMessagesReactions
from .votes_list import VotesList, TypeMessagesVotesList
from .saved_gifs import SavedGifs, SavedGifsNotModified, TypeMessagesSavedGifs
from .bot_results import BotResults, TypeMessagesBotResults
from .high_scores import TypeMessagesHighScores, HighScores
from .my_stickers import TypeMessagesMyStickers, MyStickers
from .sticker_set import StickerSetNotModified, TypeMessagesStickerSet, StickerSet
from .peer_dialogs import PeerDialogs, TypeMessagesPeerDialogs
from .forum_topics import TypeMessagesForumTopics, ForumTopics
from .all_stickers import AllStickers, AllStickersNotModified, TypeMessagesAllStickers
from .emoji_groups import EmojiGroups, EmojiGroupsNotModified, TypeMessagesEmojiGroups
from .message_views import MessageViews, TypeMessagesMessageViews
from .peer_settings import TypeMessagesPeerSettings, PeerSettings
from .invited_users import TypeMessagesInvitedUsers, InvitedUsers
from .quick_replies import TypeMessagesQuickReplies, QuickRepliesNotModified, QuickReplies
from .saved_dialogs import SavedDialogsSlice, TypeMessagesSavedDialogs, SavedDialogs, SavedDialogsNotModified
from .search_counter import SearchCounter, TypeMessagesSearchCounter
from .inactive_chats import TypeMessagesInactiveChats, InactiveChats
from .history_import import HistoryImport, TypeMessagesHistoryImport
from .dialog_filters import TypeMessagesDialogFilters, DialogFilters
from .faved_stickers import TypeMessagesFavedStickers, FavedStickers, FavedStickersNotModified
from .found_stickers import FoundStickersNotModified, FoundStickers, TypeMessagesFoundStickers
from .translated_text import TranslateResult, TypeMessagesTranslatedText
from .recent_stickers import TypeMessagesRecentStickers, RecentStickersNotModified, RecentStickers
from .affected_history import TypeMessagesAffectedHistory, AffectedHistory
from .web_page_preview import TypeMessagesWebPagePreview, WebPagePreview
from .affected_messages import AffectedMessages, TypeMessagesAffectedMessages
from .message_edit_data import MessageEditData, TypeMessagesMessageEditData
from .archived_stickers import ArchivedStickers, TypeMessagesArchivedStickers
from .transcribed_audio import TypeMessagesTranscribedAudio, TranscribedAudio
from .featured_stickers import FeaturedStickers, TypeMessagesFeaturedStickers, FeaturedStickersNotModified
from .available_effects import AvailableEffects, TypeMessagesAvailableEffects, AvailableEffectsNotModified
from .discussion_message import TypeMessagesDiscussionMessage, DiscussionMessage
from .found_sticker_sets import TypeMessagesFoundStickerSets, FoundStickerSetsNotModified, FoundStickerSets
from .sponsored_messages import SponsoredMessagesEmpty, SponsoredMessages, TypeMessagesSponsoredMessages
from .bot_callback_answer import BotCallbackAnswer, TypeMessagesBotCallbackAnswer
from .available_reactions import TypeMessagesAvailableReactions, AvailableReactions, AvailableReactionsNotModified
from .saved_reaction_tags import SavedReactionTagsNotModified, SavedReactionTags, TypeMessagesSavedReactionTags
from .exported_chat_invite import TypeMessagesExportedChatInvite, ExportedChatInvite, ExportedChatInviteReplaced
from .history_import_parsed import TypeMessagesHistoryImportParsed, HistoryImportParsed
from .exported_chat_invites import ExportedChatInvites, TypeMessagesExportedChatInvites
from .chat_invite_importers import ChatInviteImporters, TypeMessagesChatInviteImporters
from .message_reactions_list import TypeMessagesMessageReactionsList, MessageReactionsList
from .sent_encrypted_message import SentEncryptedFile, SentEncryptedMessage, TypeMessagesSentEncryptedMessage
from .affected_found_messages import AffectedFoundMessages, TypeMessagesAffectedFoundMessages
from .search_results_calendar import SearchResultsCalendar, TypeMessagesSearchResultsCalendar
from .prepared_inline_message import TypeMessagesPreparedInlineMessage, PreparedInlineMessage
from .chat_admins_with_invites import ChatAdminsWithInvites, TypeMessagesChatAdminsWithInvites
from .search_results_positions import SearchResultsPositions, TypeMessagesSearchResultsPositions
from .sticker_set_install_result import TypeMessagesStickerSetInstallResult, StickerSetInstallResultArchive, StickerSetInstallResultSuccess
from .checked_history_import_peer import TypeMessagesCheckedHistoryImportPeer, CheckedHistoryImportPeer
from .bot_prepared_inline_message import BotPreparedInlineMessage, TypeMessagesBotPreparedInlineMessage

__all__ = [
    'SearchResultsPositions',
    'FavedStickers',
    'SentEncryptedMessage',
    'CheckedHistoryImportPeer',
    'TypeMessagesFoundStickerSets',
    'AvailableEffects',
    'AllStickers',
    'SentEncryptedFile',
    'SearchCounter',
    'HistoryImport',
    'TypeMessagesChats',
    'EmojiGroups',
    'TypeMessagesPeerSettings',
    'TypeMessagesChatInviteImporters',
    'TypeMessagesEmojiGroups',
    'Dialogs',
    'DhConfigNotModified',
    'TypeMessagesForumTopics',
    'InvitedUsers',
    'SavedReactionTags',
    'TypeMessagesRecentStickers',
    'TypeMessagesInvitedUsers',
    'TypeMessagesHistoryImportParsed',
    'TypeMessagesFoundStickers',
    'SearchResultsCalendar',
    'VotesList',
    'AffectedMessages',
    'SavedGifs',
    'TypeMessagesPreparedInlineMessage',
    'BotPreparedInlineMessage',
    'TypeMessagesMessageEditData',
    'StickerSetInstallResultArchive',
    'DialogsSlice',
    'TypeMessagesSentEncryptedMessage',
    'TypeMessagesStickers',
    'ChatAdminsWithInvites',
    'TypeMessagesDiscussionMessage',
    'MessageEditData',
    'QuickReplies',
    'DialogFilters',
    'TypeMessagesAvailableEffects',
    'PreparedInlineMessage',
    'MessagesSlice',
    'TypeMessagesArchivedStickers',
    'FeaturedStickersNotModified',
    'TypeMessagesSavedReactionTags',
    'TypeMessagesMessages',
    'QuickRepliesNotModified',
    'WebPagePreview',
    'TypeMessagesDialogs',
    'AvailableEffectsNotModified',
    'TypeMessagesTranslatedText',
    'TypeMessagesWebPagePreview',
    'ExportedChatInvite',
    'RecentStickersNotModified',
    'StickerSet',
    'TypeMessagesSearchResultsCalendar',
    'TypeMessagesWebPage',
    'TypeMessagesMessageReactionsList',
    'SavedDialogsNotModified',
    'TypeMessagesChatAdminsWithInvites',
    'MessagesNotModified',
    'SponsoredMessages',
    'TypeMessagesExportedChatInvite',
    'TypeMessagesSavedDialogs',
    'TypeMessagesCheckedHistoryImportPeer',
    'WebPage',
    'TypeMessagesSavedGifs',
    'TypeMessagesChatFull',
    'AffectedHistory',
    'ExportedChatInviteReplaced',
    'ChatFull',
    'BotCallbackAnswer',
    'SavedDialogsSlice',
    'FavedStickersNotModified',
    'BotApp',
    'HighScores',
    'BotResults',
    'StickerSetNotModified',
    'InactiveChats',
    'TranscribedAudio',
    'ArchivedStickers',
    'SavedDialogs',
    'TypeMessagesSponsoredMessages',
    'ChatInviteImporters',
    'TypeMessagesMyStickers',
    'TranslateResult',
    'StickerSetInstallResultSuccess',
    'MessageViews',
    'FoundStickersNotModified',
    'HistoryImportParsed',
    'TypeMessagesBotCallbackAnswer',
    'FoundStickerSets',
    'TypeMessagesDhConfig',
    'TypeMessagesReactions',
    'ChannelMessages',
    'FoundStickerSetsNotModified',
    'TypeMessagesSearchResultsPositions',
    'SavedGifsNotModified',
    'TypeMessagesBotPreparedInlineMessage',
    'TypeMessagesMessageViews',
    'TypeMessagesSearchCounter',
    'TypeMessagesQuickReplies',
    'TypeMessagesAffectedHistory',
    'TypeMessagesInactiveChats',
    'TypeMessagesTranscribedAudio',
    'EmojiGroupsNotModified',
    'TypeMessagesAvailableReactions',
    'Chats',
    'ForumTopics',
    'TypeMessagesAffectedMessages',
    'MessageReactionsList',
    'MyStickers',
    'SponsoredMessagesEmpty',
    'FeaturedStickers',
    'AvailableReactionsNotModified',
    'PeerDialogs',
    'AffectedFoundMessages',
    'TypeMessagesDialogFilters',
    'TypeMessagesAffectedFoundMessages',
    'TypeMessagesAllStickers',
    'ReactionsNotModified',
    'TypeMessagesStickerSet',
    'TypeMessagesPeerDialogs',
    'TypeMessagesFeaturedStickers',
    'PeerSettings',
    'TypeMessagesHistoryImport',
    'TypeMessagesExportedChatInvites',
    'TypeMessagesBotApp',
    'DhConfig',
    'FoundStickers',
    'ExportedChatInvites',
    'TypeMessagesBotResults',
    'TypeMessagesStickerSetInstallResult',
    'AvailableReactions',
    'Reactions',
    'Messages',
    'DiscussionMessage',
    'DialogsNotModified',
    'SavedReactionTagsNotModified',
    'AllStickersNotModified',
    'TypeMessagesHighScores',
    'RecentStickers',
    'TypeMessagesFavedStickers',
    'Stickers',
    'ChatsSlice',
    'TypeMessagesVotesList',
    'StickersNotModified'
]