class ConfigField:
    APPLICATION_PORT = "application_port"
    CONNECTION_TIMEOUT = "connection_timeout"
    EMERGENCY_PRESET = "emergency_preset"
    GATEWAY = "gateway"
    IP = "ip"
    MUTE_INPUT = "mute_input"
    MUTE_PRESET = "mute_preset"
    NETMASK = "netmask"
    PASSWORD = "password"
    NETCONFIG = "netconfig"
    PORT_PROVISIONING_TIMEOUT = "port_provisioning_timeout"
    PULSE_INTERVAL = "pulse_interval"
    RECOVERY_PRESET = "recovery_preset"
    SERVICE_USERNAME = "service_username"
    SERVICE_PASSWORD = "service_password"
    USERNAME = "username"
