from _typeshed import Incomplete
from collections.abc import Callable, Iterator
from typing import Never, TypeVar, overload

__all__ = ['Box']

T = TypeVar('T')

class Box[T]:
    __match_args__: Incomplete
    T = TypeVar('T')
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, item: T) -> None: ...
    def __bool__(self) -> bool: ...
    def __iter__(self) -> Iterator[T]: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    @overload
    def get(self) -> T | Never: ...
    @overload
    def get(self, alt: T) -> T: ...
    def pop(self) -> T | Never: ...
    def push(self, item: T) -> None | Never: ...
    def put(self, item: T) -> None: ...
    def exchange(self, new_item: T) -> T | Never: ...
    def map[U](self, f: Callable[[T], U]) -> Box[U]: ...
    def bind[U](self, f: Callable[[T], 'Box[U]']) -> Box[U]: ...
