# coding: utf-8

"""
    QAnswer: Api Documentation

    APIs provided by QAnswer

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qanswer-sdk.models.socket_data_extraction import SocketDataExtraction

class TestSocketDataExtraction(unittest.TestCase):
    """SocketDataExtraction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SocketDataExtraction:
        """Test SocketDataExtraction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SocketDataExtraction`
        """
        model = SocketDataExtraction()
        if include_optional:
            return SocketDataExtraction(
                username = '',
                dataset = '',
                jwt = '',
                api_key = '',
                subject = qanswer-sdk.models.subject_model.SubjectModel(
                    label = '', 
                    value = '', 
                    filter_by = '', ),
                subject_relations = [
                    qanswer-sdk.models.entity_model.EntityModel(
                        relation_name = '', 
                        object_entity = '', 
                        sources = [
                            qanswer-sdk.models.source.Source(
                                title = '', 
                                document = '', 
                                document_with_highlights = '', 
                                from_page = 56, 
                                to_page = 56, 
                                source_url = '', 
                                source_type = '', 
                                file_type = '', 
                                file_id = '', 
                                display_name = '', 
                                file_name = '', 
                                original_file_name = '', 
                                connector_type = '', 
                                connector_id = 56, 
                                additional_fields = qanswer-sdk.models.additional_fields.additional_fields(), 
                                ref_id = '', 
                                favicon = '', 
                                username = '', 
                                dataset = '', 
                                last_updated_at = '', )
                            ], )
                    ]
            )
        else:
            return SocketDataExtraction(
                username = '',
                dataset = '',
                jwt = '',
                subject = qanswer-sdk.models.subject_model.SubjectModel(
                    label = '', 
                    value = '', 
                    filter_by = '', ),
                subject_relations = [
                    qanswer-sdk.models.entity_model.EntityModel(
                        relation_name = '', 
                        object_entity = '', 
                        sources = [
                            qanswer-sdk.models.source.Source(
                                title = '', 
                                document = '', 
                                document_with_highlights = '', 
                                from_page = 56, 
                                to_page = 56, 
                                source_url = '', 
                                source_type = '', 
                                file_type = '', 
                                file_id = '', 
                                display_name = '', 
                                file_name = '', 
                                original_file_name = '', 
                                connector_type = '', 
                                connector_id = 56, 
                                additional_fields = qanswer-sdk.models.additional_fields.additional_fields(), 
                                ref_id = '', 
                                favicon = '', 
                                username = '', 
                                dataset = '', 
                                last_updated_at = '', )
                            ], )
                    ],
        )
        """

    def testSocketDataExtraction(self):
        """Test SocketDataExtraction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
