from .models import EntityLinkingConfig, MatchCondition, MatchType, FieldCondition, OrCondition, AndCondition


# Create a custom config with dictionary matching
default_config = EntityLinkingConfig(
    quick_creation_config=AndCondition(
        conditions=[
            OrCondition(
                conditions=[
                    FieldCondition(
                        field="canonical_name",
                        condition=MatchCondition(
                            match_type=MatchType.LEXICAL_SIMILARITY,
                            threshold=60
                        )
                    ),
                    FieldCondition(
                        field="canonical_name",
                        condition=MatchCondition(
                            match_type=MatchType.SEMANTIC_SIMILARITY,
                            threshold=80
                        )
                    ),
                ]
            ),
            OrCondition(
                conditions=[
                    FieldCondition(
                        field="aliases",
                        condition=MatchCondition(
                            match_type=MatchType.LEXICAL_SIMILARITY_LIST,
                            threshold=60
                        )
                    ),
                    FieldCondition(
                        field="metadata",
                        condition=MatchCondition(
                            match_type=MatchType.DICT_MATCH,
                            threshold=65,
                        ),
                        dict_mappings=[]
                    )
                ]
            ),
        ]
    ),
    quick_linking_config=AndCondition(
        conditions=[
            OrCondition(
                conditions=[
                    FieldCondition(
                        field="canonical_name",
                        condition=MatchCondition(
                            match_type=MatchType.LEXICAL_SIMILARITY,
                            threshold=90
                        )
                    ),
                    FieldCondition(
                        field="canonical_name",
                        condition=MatchCondition(
                            match_type=MatchType.SEMANTIC_SIMILARITY,
                            threshold=90
                        )
                    ),
                    FieldCondition(
                        field="aliases",
                        condition=MatchCondition(
                            match_type=MatchType.LEXICAL_SIMILARITY_LIST,
                            threshold=90
                        )
                    ),
                ]
            ),
            FieldCondition(
                field="metadata",
                condition=MatchCondition(
                    match_type=MatchType.DICT_MATCH,
                    threshold=60,
                ),
                dict_mappings=[]
            ),
        ]
    ),
    llm_linking_config=OrCondition(
        conditions=[
            FieldCondition(
                field="canonical_name",
                condition=MatchCondition(
                    match_type=MatchType.LEXICAL_SIMILARITY,
                    threshold=20,
                    weight=1.0
                )
            ),
            FieldCondition(
                field="canonical_name",
                condition=MatchCondition(
                    match_type=MatchType.SEMANTIC_SIMILARITY,
                    threshold=20,
                    weight=1.0
                )
            ),
            FieldCondition(
                field="aliases",
                condition=MatchCondition(
                    match_type=MatchType.LEXICAL_SIMILARITY_LIST,
                    threshold=20,
                    weight=0.6
                )
            ),
            FieldCondition(
                field="metadata",
                condition=MatchCondition(
                    match_type=MatchType.DICT_MATCH,
                    threshold=20,
                    weight=0.1
                ),
                dict_mappings=[]
            )
        ]
    ),
    llm_top_k=5
)
