class KafkaTopics:
    USER_REGISTERED = "user.registered"
    USER_VERIFICATION_REQUEST = "user.verification_request"
    USER_PASSWORD_RESET_REQUEST = "user.password_reset_request"
    USER_EMAIL_VERIFICATION_REQUEST = "user.email_verification_request"
    USER_KYC_VERIFIED = "user.kyc_verified"
    RESERVATION_RECORD = "reservation.record"
    RESERVATION_SUCCEEDED = "reservation.suceeded"
    SLOT_RESERVED_NOTIFICATION = "slot.reserved_notification"
    SUBSLOT_ACCEPTED_NOTIFICATION = "subslot.accepted_notification"
    SUBSLOT_REJECTED_NOTIFICATION = "subslot.rejected_notification"
    FACE_MATCHING_REQUEST = "ai.face_matching_request"
