# coding: utf-8

"""
    QAnswer 2.0

    QAnswer 2.0 API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class InterfaceOrigin(str, Enum):
    """
    The different interfaces or platforms from which the queries originate. This helps in tracking and analyzing the source of interactions for performance monitoring.  - Search: search interface. - Chat: chat interface. - Widget: embedded widget interface. - Microsoft Teams: the Microsoft Teams platform. - Discord: the Discord platform. - Slack: the Slack platform.
    """

    """
    allowed enum values
    """
    SEARCH = 'search'
    CHAT = 'chat'
    WIDGET = 'widget'
    MICROSOFT_TEAMS = 'microsoft_teams'
    DISCORD = 'discord'
    SLACK = 'slack'
    CHATBOT_PLAYGROUND = 'chatbot_playground'
    UNDEFINED = 'undefined'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of InterfaceOrigin from a JSON string"""
        return cls(json.loads(json_str))


