# This file was auto-generated by Fern from our API Definition.

from .......core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from .......core.pydantic_utilities import IS_PYDANTIC_V2


class LookupDetails(UniversalBaseModel):
    forward_ip: typing.Optional[str] = pydantic.Field(alias="forwardIp", default=None)
    reverse_ptrs: typing.Optional[typing.List[str]] = pydantic.Field(alias="reversePtrs", default=None)

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            extra = pydantic.Extra.allow
