// This file was generated. DO NOT EDIT.
use crate::{Icon, icons};

#[cfg(feature = "pyo3")]
use pyo3::exceptions::PyDeprecationWarning;

#[cfg(feature = "pyo3")]
use pyo3::prelude::*;

pub(super) fn find_part_19(#[cfg(feature = "pyo3")] py: Python, slug: &str) -> Option<Icon> {
    match slug {
        "home-minus" => Some(icons::HOME_MINUS),
        "home-modern" => Some(icons::HOME_MODERN),
        "home-off-outline" => Some(icons::HOME_OFF_OUTLINE),
        "home-off" => Some(icons::HOME_OFF),
        "home-outline" => Some(icons::HOME_OUTLINE),
        "home-percent-outline" => Some(icons::HOME_PERCENT_OUTLINE),
        "home-percent" => Some(icons::HOME_PERCENT),
        "home-plus-outline" => Some(icons::HOME_PLUS_OUTLINE),
        "home-plus" => Some(icons::HOME_PLUS),
        "home-remove-outline" => Some(icons::HOME_REMOVE_OUTLINE),
        "home-remove" => Some(icons::HOME_REMOVE),
        "home-roof" => Some(icons::HOME_ROOF),
        "home-search-outline" => Some(icons::HOME_SEARCH_OUTLINE),
        "home-search" => Some(icons::HOME_SEARCH),
        "home-silo-outline" => Some(icons::HOME_SILO_OUTLINE),
        "home-silo" => Some(icons::HOME_SILO),
        "home-sound-in-outline" => Some(icons::HOME_SOUND_IN_OUTLINE),
        "home-sound-in" => Some(icons::HOME_SOUND_IN),
        "home-sound-out-outline" => Some(icons::HOME_SOUND_OUT_OUTLINE),
        "home-sound-out" => Some(icons::HOME_SOUND_OUT),
        "home-switch-outline" => Some(icons::HOME_SWITCH_OUTLINE),
        "home-switch" => Some(icons::HOME_SWITCH),
        "home-thermometer-outline" => Some(icons::HOME_THERMOMETER_OUTLINE),
        "home-thermometer" => Some(icons::HOME_THERMOMETER),
        "home-variant-outline" => Some(icons::HOME_VARIANT_OUTLINE),
        "home-variant" => Some(icons::HOME_VARIANT),
        "home" => Some(icons::HOME),
        "hook-off" => Some(icons::HOOK_OFF),
        "hook" => Some(icons::HOOK),
        "hoop-house" => Some(icons::HOOP_HOUSE),
        "hops" => Some(icons::HOPS),
        "horizontal-rotate-clockwise" => Some(icons::HORIZONTAL_ROTATE_CLOCKWISE),
        "horizontal-rotate-counterclockwise" => Some(icons::HORIZONTAL_ROTATE_COUNTERCLOCKWISE),
        "horse-human" => Some(icons::HORSE_HUMAN),
        "horse-variant-fast" => Some(icons::HORSE_VARIANT_FAST),
        "horse-variant" => Some(icons::HORSE_VARIANT),
        "horse" => Some(icons::HORSE),
        "horseshoe" => Some(icons::HORSESHOE),
        "hospital-box-outline" => Some(icons::HOSPITAL_BOX_OUTLINE),
        "hospital-box" => Some(icons::HOSPITAL_BOX),
        "hospital-building" => Some(icons::HOSPITAL_BUILDING),
        "hospital-marker" => Some(icons::HOSPITAL_MARKER),
        "hospital" => Some(icons::HOSPITAL),
        "hot-tub" => Some(icons::HOT_TUB),
        "hours-12" => Some(icons::HOURS_12),
        "hours-24" => Some(icons::HOURS_24),
        "hub-outline" => Some(icons::HUB_OUTLINE),
        "hub" => Some(icons::HUB),
        "hubspot" => Some(icons::HUBSPOT),
        #[allow(deprecated)]
        "hulu" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'hulu' is deprecated.").print(py);
            }
            Some(icons::HULU)
        }
        "human-baby-changing-table" => Some(icons::HUMAN_BABY_CHANGING_TABLE),
        "human-cane" => Some(icons::HUMAN_CANE),
        "human-capacity-decrease" => Some(icons::HUMAN_CAPACITY_DECREASE),
        "human-capacity-increase" => Some(icons::HUMAN_CAPACITY_INCREASE),
        "human-child" => Some(icons::HUMAN_CHILD),
        "human-dolly" => Some(icons::HUMAN_DOLLY),
        "human-edit" => Some(icons::HUMAN_EDIT),
        "human-female-boy" => Some(icons::HUMAN_FEMALE_BOY),
        "human-female-dance" => Some(icons::HUMAN_FEMALE_DANCE),
        "human-female-female-child" => Some(icons::HUMAN_FEMALE_FEMALE_CHILD),
        "human-female-female" => Some(icons::HUMAN_FEMALE_FEMALE),
        "human-female-girl" => Some(icons::HUMAN_FEMALE_GIRL),
        "human-female" => Some(icons::HUMAN_FEMALE),
        "human-greeting-proximity" => Some(icons::HUMAN_GREETING_PROXIMITY),
        "human-greeting-variant" => Some(icons::HUMAN_GREETING_VARIANT),
        "human-greeting" => Some(icons::HUMAN_GREETING),
        "human-handsdown" => Some(icons::HUMAN_HANDSDOWN),
        "human-handsup" => Some(icons::HUMAN_HANDSUP),
        "human-male-board-poll" => Some(icons::HUMAN_MALE_BOARD_POLL),
        "human-male-board" => Some(icons::HUMAN_MALE_BOARD),
        "human-male-boy" => Some(icons::HUMAN_MALE_BOY),
        "human-male-child" => Some(icons::HUMAN_MALE_CHILD),
        "human-male-female-child" => Some(icons::HUMAN_MALE_FEMALE_CHILD),
        "human-male-female" => Some(icons::HUMAN_MALE_FEMALE),
        "human-male-girl" => Some(icons::HUMAN_MALE_GIRL),
        "human-male-height-variant" => Some(icons::HUMAN_MALE_HEIGHT_VARIANT),
        "human-male-height" => Some(icons::HUMAN_MALE_HEIGHT),
        "human-male-male-child" => Some(icons::HUMAN_MALE_MALE_CHILD),
        "human-male-male" => Some(icons::HUMAN_MALE_MALE),
        "human-male" => Some(icons::HUMAN_MALE),
        "human-non-binary" => Some(icons::HUMAN_NON_BINARY),
        "human-pregnant" => Some(icons::HUMAN_PREGNANT),
        "human-queue" => Some(icons::HUMAN_QUEUE),
        "human-scooter" => Some(icons::HUMAN_SCOOTER),
        "human-walker" => Some(icons::HUMAN_WALKER),
        "human-wheelchair" => Some(icons::HUMAN_WHEELCHAIR),
        "human-white-cane" => Some(icons::HUMAN_WHITE_CANE),
        "human" => Some(icons::HUMAN),
        #[allow(deprecated)]
        "humble-bundle" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'humble-bundle' is deprecated.").print(py);
            }
            Some(icons::HUMBLE_BUNDLE)
        }
        "hvac-off" => Some(icons::HVAC_OFF),
        "hvac" => Some(icons::HVAC),
        "hydraulic-oil-level" => Some(icons::HYDRAULIC_OIL_LEVEL),
        "hydraulic-oil-temperature" => Some(icons::HYDRAULIC_OIL_TEMPERATURE),
        "hydro-power" => Some(icons::HYDRO_POWER),
        "hydrogen-station" => Some(icons::HYDROGEN_STATION),
        "ice-cream-off" => Some(icons::ICE_CREAM_OFF),
        "ice-cream" => Some(icons::ICE_CREAM),
        "ice-pop" => Some(icons::ICE_POP),
        "id-card" => Some(icons::ID_CARD),
        "identifier" => Some(icons::IDENTIFIER),
        "ideogram-cjk-variant" => Some(icons::IDEOGRAM_CJK_VARIANT),
        "ideogram-cjk" => Some(icons::IDEOGRAM_CJK),
        "image-album" => Some(icons::IMAGE_ALBUM),
        "image-area-close" => Some(icons::IMAGE_AREA_CLOSE),
        "image-area" => Some(icons::IMAGE_AREA),
        "image-auto-adjust" => Some(icons::IMAGE_AUTO_ADJUST),
        "image-broken-variant" => Some(icons::IMAGE_BROKEN_VARIANT),
        "image-broken" => Some(icons::IMAGE_BROKEN),
        "image-check-outline" => Some(icons::IMAGE_CHECK_OUTLINE),
        "image-check" => Some(icons::IMAGE_CHECK),
        "image-edit-outline" => Some(icons::IMAGE_EDIT_OUTLINE),
        "image-edit" => Some(icons::IMAGE_EDIT),
        "image-filter-black-white" => Some(icons::IMAGE_FILTER_BLACK_WHITE),
        "image-filter-center-focus-strong-outline" => {
            Some(icons::IMAGE_FILTER_CENTER_FOCUS_STRONG_OUTLINE)
        }
        "image-filter-center-focus-strong" => Some(icons::IMAGE_FILTER_CENTER_FOCUS_STRONG),
        "image-filter-center-focus-weak" => Some(icons::IMAGE_FILTER_CENTER_FOCUS_WEAK),
        "image-filter-center-focus" => Some(icons::IMAGE_FILTER_CENTER_FOCUS),
        "image-filter-drama-outline" => Some(icons::IMAGE_FILTER_DRAMA_OUTLINE),
        "image-filter-drama" => Some(icons::IMAGE_FILTER_DRAMA),
        "image-filter-frames" => Some(icons::IMAGE_FILTER_FRAMES),
        "image-filter-hdr-outline" => Some(icons::IMAGE_FILTER_HDR_OUTLINE),
        "image-filter-hdr" => Some(icons::IMAGE_FILTER_HDR),
        "image-filter-none" => Some(icons::IMAGE_FILTER_NONE),
        "image-filter-tilt-shift" => Some(icons::IMAGE_FILTER_TILT_SHIFT),
        "image-filter-vintage" => Some(icons::IMAGE_FILTER_VINTAGE),
        "image-frame" => Some(icons::IMAGE_FRAME),
        "image-lock-outline" => Some(icons::IMAGE_LOCK_OUTLINE),
        "image-lock" => Some(icons::IMAGE_LOCK),
        "image-marker-outline" => Some(icons::IMAGE_MARKER_OUTLINE),
        "image-marker" => Some(icons::IMAGE_MARKER),
        "image-minus-outline" => Some(icons::IMAGE_MINUS_OUTLINE),
        "image-minus" => Some(icons::IMAGE_MINUS),
        "image-move" => Some(icons::IMAGE_MOVE),
        "image-multiple-outline" => Some(icons::IMAGE_MULTIPLE_OUTLINE),
        "image-multiple" => Some(icons::IMAGE_MULTIPLE),
        "image-off-outline" => Some(icons::IMAGE_OFF_OUTLINE),
        "image-off" => Some(icons::IMAGE_OFF),
        "image-outline" => Some(icons::IMAGE_OUTLINE),
        "image-plus-outline" => Some(icons::IMAGE_PLUS_OUTLINE),
        "image-plus" => Some(icons::IMAGE_PLUS),
        "image-refresh-outline" => Some(icons::IMAGE_REFRESH_OUTLINE),
        "image-refresh" => Some(icons::IMAGE_REFRESH),
        "image-remove-outline" => Some(icons::IMAGE_REMOVE_OUTLINE),
        "image-remove" => Some(icons::IMAGE_REMOVE),
        "image-search-outline" => Some(icons::IMAGE_SEARCH_OUTLINE),
        "image-search" => Some(icons::IMAGE_SEARCH),
        "image-size-select-actual" => Some(icons::IMAGE_SIZE_SELECT_ACTUAL),
        "image-size-select-large" => Some(icons::IMAGE_SIZE_SELECT_LARGE),
        "image-size-select-small" => Some(icons::IMAGE_SIZE_SELECT_SMALL),
        "image-sync-outline" => Some(icons::IMAGE_SYNC_OUTLINE),
        "image-sync" => Some(icons::IMAGE_SYNC),
        "image-text" => Some(icons::IMAGE_TEXT),
        "image" => Some(icons::IMAGE),
        "import" => Some(icons::IMPORT),
        "inbox-arrow-down-outline" => Some(icons::INBOX_ARROW_DOWN_OUTLINE),
        "inbox-arrow-down" => Some(icons::INBOX_ARROW_DOWN),
        "inbox-arrow-up-outline" => Some(icons::INBOX_ARROW_UP_OUTLINE),
        "inbox-arrow-up" => Some(icons::INBOX_ARROW_UP),
        "inbox-full-outline" => Some(icons::INBOX_FULL_OUTLINE),
        "inbox-full" => Some(icons::INBOX_FULL),
        "inbox-multiple-outline" => Some(icons::INBOX_MULTIPLE_OUTLINE),
        "inbox-multiple" => Some(icons::INBOX_MULTIPLE),
        "inbox-outline" => Some(icons::INBOX_OUTLINE),
        "inbox-remove-outline" => Some(icons::INBOX_REMOVE_OUTLINE),
        "inbox-remove" => Some(icons::INBOX_REMOVE),
        "inbox" => Some(icons::INBOX),
        "incognito-circle-off" => Some(icons::INCOGNITO_CIRCLE_OFF),
        "incognito-circle" => Some(icons::INCOGNITO_CIRCLE),
        "incognito-off" => Some(icons::INCOGNITO_OFF),
        "incognito" => Some(icons::INCOGNITO),
        "induction" => Some(icons::INDUCTION),
        "infinity" => Some(icons::INFINITY),
        "information-box-outline" => Some(icons::INFORMATION_BOX_OUTLINE),
        "information-box" => Some(icons::INFORMATION_BOX),
        "information-off-outline" => Some(icons::INFORMATION_OFF_OUTLINE),
        "information-off" => Some(icons::INFORMATION_OFF),
        "information-outline" => Some(icons::INFORMATION_OUTLINE),
        "information-slab-box-outline" => Some(icons::INFORMATION_SLAB_BOX_OUTLINE),
        "information-slab-box" => Some(icons::INFORMATION_SLAB_BOX),
        "information-slab-circle-outline" => Some(icons::INFORMATION_SLAB_CIRCLE_OUTLINE),
        "information-slab-circle" => Some(icons::INFORMATION_SLAB_CIRCLE),
        "information-slab-symbol" => Some(icons::INFORMATION_SLAB_SYMBOL),
        "information-symbol" => Some(icons::INFORMATION_SYMBOL),
        "information-variant-box-outline" => Some(icons::INFORMATION_VARIANT_BOX_OUTLINE),
        "information-variant-box" => Some(icons::INFORMATION_VARIANT_BOX),
        "information-variant-circle-outline" => Some(icons::INFORMATION_VARIANT_CIRCLE_OUTLINE),
        "information-variant-circle" => Some(icons::INFORMATION_VARIANT_CIRCLE),
        "information-variant" => Some(icons::INFORMATION_VARIANT),
        "information" => Some(icons::INFORMATION),
        #[allow(deprecated)]
        "instagram" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'instagram' is deprecated.").print(py);
            }
            Some(icons::INSTAGRAM)
        }
        "instrument-triangle" => Some(icons::INSTRUMENT_TRIANGLE),
        "integrated-circuit-chip" => Some(icons::INTEGRATED_CIRCUIT_CHIP),
        "invert-colors-off" => Some(icons::INVERT_COLORS_OFF),
        "invert-colors" => Some(icons::INVERT_COLORS),
        "invoice-arrow-left-outline" => Some(icons::INVOICE_ARROW_LEFT_OUTLINE),
        "invoice-arrow-left" => Some(icons::INVOICE_ARROW_LEFT),
        "invoice-arrow-right-outline" => Some(icons::INVOICE_ARROW_RIGHT_OUTLINE),
        "invoice-arrow-right" => Some(icons::INVOICE_ARROW_RIGHT),
        "invoice-check-outline" => Some(icons::INVOICE_CHECK_OUTLINE),
        "invoice-check" => Some(icons::INVOICE_CHECK),
        _ => None,
    }
}
