// This file was generated. DO NOT EDIT.
use crate::{Icon, icons};

#[cfg(feature = "pyo3")]
use pyo3::exceptions::PyDeprecationWarning;

#[cfg(feature = "pyo3")]
use pyo3::prelude::*;

pub(super) fn find_part_29(#[cfg(feature = "pyo3")] py: Python, slug: &str) -> Option<Icon> {
    match slug {
        "run" => Some(icons::RUN),
        "rv-truck" => Some(icons::RV_TRUCK),
        "sack-outline" => Some(icons::SACK_OUTLINE),
        "sack-percent" => Some(icons::SACK_PERCENT),
        "sack" => Some(icons::SACK),
        "safe-square-outline" => Some(icons::SAFE_SQUARE_OUTLINE),
        "safe-square" => Some(icons::SAFE_SQUARE),
        "safe" => Some(icons::SAFE),
        "safety-goggles" => Some(icons::SAFETY_GOGGLES),
        "sail-boat-sink" => Some(icons::SAIL_BOAT_SINK),
        "sail-boat" => Some(icons::SAIL_BOAT),
        "sale-outline" => Some(icons::SALE_OUTLINE),
        "sale" => Some(icons::SALE),
        #[allow(deprecated)]
        "salesforce" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'salesforce' is deprecated.").print(py);
            }
            Some(icons::SALESFORCE)
        }
        #[allow(deprecated)]
        "sass" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'sass' is deprecated.").print(py);
            }
            Some(icons::SASS)
        }
        "satellite-uplink" => Some(icons::SATELLITE_UPLINK),
        "satellite-variant" => Some(icons::SATELLITE_VARIANT),
        "satellite" => Some(icons::SATELLITE),
        "sausage-off" => Some(icons::SAUSAGE_OFF),
        "sausage" => Some(icons::SAUSAGE),
        "saw-blade" => Some(icons::SAW_BLADE),
        "sawtooth-wave" => Some(icons::SAWTOOTH_WAVE),
        "saxophone" => Some(icons::SAXOPHONE),
        "scale-balance" => Some(icons::SCALE_BALANCE),
        "scale-bathroom" => Some(icons::SCALE_BATHROOM),
        "scale-off" => Some(icons::SCALE_OFF),
        "scale-unbalanced" => Some(icons::SCALE_UNBALANCED),
        "scale" => Some(icons::SCALE),
        "scan-helper" => Some(icons::SCAN_HELPER),
        "scanner-off" => Some(icons::SCANNER_OFF),
        "scanner" => Some(icons::SCANNER),
        "scatter-plot-outline" => Some(icons::SCATTER_PLOT_OUTLINE),
        "scatter-plot" => Some(icons::SCATTER_PLOT),
        "scent-off" => Some(icons::SCENT_OFF),
        "scent" => Some(icons::SCENT),
        "school-outline" => Some(icons::SCHOOL_OUTLINE),
        "school" => Some(icons::SCHOOL),
        "scissors-cutting" => Some(icons::SCISSORS_CUTTING),
        "scooter-electric" => Some(icons::SCOOTER_ELECTRIC),
        "scooter" => Some(icons::SCOOTER),
        "scoreboard-outline" => Some(icons::SCOREBOARD_OUTLINE),
        "scoreboard" => Some(icons::SCOREBOARD),
        "screen-rotation-lock" => Some(icons::SCREEN_ROTATION_LOCK),
        "screen-rotation" => Some(icons::SCREEN_ROTATION),
        "screw-flat-top" => Some(icons::SCREW_FLAT_TOP),
        "screw-lag" => Some(icons::SCREW_LAG),
        "screw-machine-flat-top" => Some(icons::SCREW_MACHINE_FLAT_TOP),
        "screw-machine-round-top" => Some(icons::SCREW_MACHINE_ROUND_TOP),
        "screw-round-top" => Some(icons::SCREW_ROUND_TOP),
        "screwdriver" => Some(icons::SCREWDRIVER),
        "script-outline" => Some(icons::SCRIPT_OUTLINE),
        "script-text-key-outline" => Some(icons::SCRIPT_TEXT_KEY_OUTLINE),
        "script-text-key" => Some(icons::SCRIPT_TEXT_KEY),
        "script-text-outline" => Some(icons::SCRIPT_TEXT_OUTLINE),
        "script-text-play-outline" => Some(icons::SCRIPT_TEXT_PLAY_OUTLINE),
        "script-text-play" => Some(icons::SCRIPT_TEXT_PLAY),
        "script-text" => Some(icons::SCRIPT_TEXT),
        "script" => Some(icons::SCRIPT),
        "sd" => Some(icons::SD),
        "seal-variant" => Some(icons::SEAL_VARIANT),
        "seal" => Some(icons::SEAL),
        "search-web" => Some(icons::SEARCH_WEB),
        "seat-flat-angled" => Some(icons::SEAT_FLAT_ANGLED),
        "seat-flat" => Some(icons::SEAT_FLAT),
        "seat-individual-suite" => Some(icons::SEAT_INDIVIDUAL_SUITE),
        "seat-legroom-extra" => Some(icons::SEAT_LEGROOM_EXTRA),
        "seat-legroom-normal" => Some(icons::SEAT_LEGROOM_NORMAL),
        "seat-legroom-reduced" => Some(icons::SEAT_LEGROOM_REDUCED),
        "seat-outline" => Some(icons::SEAT_OUTLINE),
        "seat-passenger" => Some(icons::SEAT_PASSENGER),
        "seat-recline-extra" => Some(icons::SEAT_RECLINE_EXTRA),
        "seat-recline-normal" => Some(icons::SEAT_RECLINE_NORMAL),
        "seat" => Some(icons::SEAT),
        "seatbelt" => Some(icons::SEATBELT),
        "security-network" => Some(icons::SECURITY_NETWORK),
        "security" => Some(icons::SECURITY),
        "seed-off-outline" => Some(icons::SEED_OFF_OUTLINE),
        "seed-off" => Some(icons::SEED_OFF),
        "seed-outline" => Some(icons::SEED_OUTLINE),
        "seed-plus-outline" => Some(icons::SEED_PLUS_OUTLINE),
        "seed-plus" => Some(icons::SEED_PLUS),
        "seed" => Some(icons::SEED),
        "seesaw" => Some(icons::SEESAW),
        "segment" => Some(icons::SEGMENT),
        "select-all" => Some(icons::SELECT_ALL),
        "select-arrow-down" => Some(icons::SELECT_ARROW_DOWN),
        "select-arrow-up" => Some(icons::SELECT_ARROW_UP),
        "select-color" => Some(icons::SELECT_COLOR),
        "select-compare" => Some(icons::SELECT_COMPARE),
        "select-drag" => Some(icons::SELECT_DRAG),
        "select-group" => Some(icons::SELECT_GROUP),
        "select-inverse" => Some(icons::SELECT_INVERSE),
        "select-marker" => Some(icons::SELECT_MARKER),
        "select-multiple-marker" => Some(icons::SELECT_MULTIPLE_MARKER),
        "select-multiple" => Some(icons::SELECT_MULTIPLE),
        "select-off" => Some(icons::SELECT_OFF),
        "select-place" => Some(icons::SELECT_PLACE),
        "select-remove" => Some(icons::SELECT_REMOVE),
        "select-search" => Some(icons::SELECT_SEARCH),
        "select" => Some(icons::SELECT),
        "selection-drag" => Some(icons::SELECTION_DRAG),
        "selection-ellipse-arrow-inside" => Some(icons::SELECTION_ELLIPSE_ARROW_INSIDE),
        "selection-ellipse-remove" => Some(icons::SELECTION_ELLIPSE_REMOVE),
        "selection-ellipse" => Some(icons::SELECTION_ELLIPSE),
        "selection-marker" => Some(icons::SELECTION_MARKER),
        "selection-multiple-marker" => Some(icons::SELECTION_MULTIPLE_MARKER),
        "selection-multiple" => Some(icons::SELECTION_MULTIPLE),
        "selection-off" => Some(icons::SELECTION_OFF),
        "selection-remove" => Some(icons::SELECTION_REMOVE),
        "selection-search" => Some(icons::SELECTION_SEARCH),
        "selection" => Some(icons::SELECTION),
        #[allow(deprecated)]
        "semantic-web" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'semantic-web' is deprecated.").print(py);
            }
            Some(icons::SEMANTIC_WEB)
        }
        "send-check-outline" => Some(icons::SEND_CHECK_OUTLINE),
        "send-check" => Some(icons::SEND_CHECK),
        "send-circle-outline" => Some(icons::SEND_CIRCLE_OUTLINE),
        "send-circle" => Some(icons::SEND_CIRCLE),
        "send-clock-outline" => Some(icons::SEND_CLOCK_OUTLINE),
        "send-clock" => Some(icons::SEND_CLOCK),
        "send-lock-outline" => Some(icons::SEND_LOCK_OUTLINE),
        "send-lock" => Some(icons::SEND_LOCK),
        "send-outline" => Some(icons::SEND_OUTLINE),
        "send-variant-clock-outline" => Some(icons::SEND_VARIANT_CLOCK_OUTLINE),
        "send-variant-clock" => Some(icons::SEND_VARIANT_CLOCK),
        "send-variant-outline" => Some(icons::SEND_VARIANT_OUTLINE),
        "send-variant" => Some(icons::SEND_VARIANT),
        "send" => Some(icons::SEND),
        "serial-port" => Some(icons::SERIAL_PORT),
        "server-minus-outline" => Some(icons::SERVER_MINUS_OUTLINE),
        "server-minus" => Some(icons::SERVER_MINUS),
        "server-network-off" => Some(icons::SERVER_NETWORK_OFF),
        "server-network-outline" => Some(icons::SERVER_NETWORK_OUTLINE),
        "server-network" => Some(icons::SERVER_NETWORK),
        "server-off" => Some(icons::SERVER_OFF),
        "server-outline" => Some(icons::SERVER_OUTLINE),
        "server-plus-outline" => Some(icons::SERVER_PLUS_OUTLINE),
        "server-plus" => Some(icons::SERVER_PLUS),
        "server-remove" => Some(icons::SERVER_REMOVE),
        "server-security" => Some(icons::SERVER_SECURITY),
        "server" => Some(icons::SERVER),
        "set-all" => Some(icons::SET_ALL),
        "set-center-right" => Some(icons::SET_CENTER_RIGHT),
        "set-center" => Some(icons::SET_CENTER),
        "set-left-center" => Some(icons::SET_LEFT_CENTER),
        "set-left-right" => Some(icons::SET_LEFT_RIGHT),
        "set-left" => Some(icons::SET_LEFT),
        "set-merge" => Some(icons::SET_MERGE),
        "set-none" => Some(icons::SET_NONE),
        "set-right" => Some(icons::SET_RIGHT),
        "set-split" => Some(icons::SET_SPLIT),
        "set-square" => Some(icons::SET_SQUARE),
        "set-top-box" => Some(icons::SET_TOP_BOX),
        "settings-helper" => Some(icons::SETTINGS_HELPER),
        "shaker-outline" => Some(icons::SHAKER_OUTLINE),
        "shaker" => Some(icons::SHAKER),
        "shape-circle-plus" => Some(icons::SHAPE_CIRCLE_PLUS),
        "shape-outline" => Some(icons::SHAPE_OUTLINE),
        "shape-oval-plus" => Some(icons::SHAPE_OVAL_PLUS),
        "shape-plus-outline" => Some(icons::SHAPE_PLUS_OUTLINE),
        "shape-plus" => Some(icons::SHAPE_PLUS),
        "shape-polygon-plus" => Some(icons::SHAPE_POLYGON_PLUS),
        "shape-rectangle-plus" => Some(icons::SHAPE_RECTANGLE_PLUS),
        "shape-square-plus" => Some(icons::SHAPE_SQUARE_PLUS),
        "shape-square-rounded-plus" => Some(icons::SHAPE_SQUARE_ROUNDED_PLUS),
        "shape" => Some(icons::SHAPE),
        "share-all-outline" => Some(icons::SHARE_ALL_OUTLINE),
        "share-all" => Some(icons::SHARE_ALL),
        "share-circle" => Some(icons::SHARE_CIRCLE),
        "share-off-outline" => Some(icons::SHARE_OFF_OUTLINE),
        "share-off" => Some(icons::SHARE_OFF),
        "share-outline" => Some(icons::SHARE_OUTLINE),
        "share-variant-outline" => Some(icons::SHARE_VARIANT_OUTLINE),
        "share-variant" => Some(icons::SHARE_VARIANT),
        "share" => Some(icons::SHARE),
        "shark-fin-outline" => Some(icons::SHARK_FIN_OUTLINE),
        "shark-fin" => Some(icons::SHARK_FIN),
        "shark-off" => Some(icons::SHARK_OFF),
        "shark" => Some(icons::SHARK),
        "sheep" => Some(icons::SHEEP),
        "shield-account-outline" => Some(icons::SHIELD_ACCOUNT_OUTLINE),
        "shield-account-variant-outline" => Some(icons::SHIELD_ACCOUNT_VARIANT_OUTLINE),
        "shield-account-variant" => Some(icons::SHIELD_ACCOUNT_VARIANT),
        "shield-account" => Some(icons::SHIELD_ACCOUNT),
        "shield-airplane-outline" => Some(icons::SHIELD_AIRPLANE_OUTLINE),
        "shield-airplane" => Some(icons::SHIELD_AIRPLANE),
        "shield-alert-outline" => Some(icons::SHIELD_ALERT_OUTLINE),
        "shield-alert" => Some(icons::SHIELD_ALERT),
        "shield-bug-outline" => Some(icons::SHIELD_BUG_OUTLINE),
        "shield-bug" => Some(icons::SHIELD_BUG),
        "shield-car" => Some(icons::SHIELD_CAR),
        "shield-check-outline" => Some(icons::SHIELD_CHECK_OUTLINE),
        "shield-check" => Some(icons::SHIELD_CHECK),
        "shield-cross-outline" => Some(icons::SHIELD_CROSS_OUTLINE),
        "shield-cross" => Some(icons::SHIELD_CROSS),
        "shield-crown-outline" => Some(icons::SHIELD_CROWN_OUTLINE),
        "shield-crown" => Some(icons::SHIELD_CROWN),
        "shield-edit-outline" => Some(icons::SHIELD_EDIT_OUTLINE),
        "shield-edit" => Some(icons::SHIELD_EDIT),
        "shield-half-full" => Some(icons::SHIELD_HALF_FULL),
        "shield-half" => Some(icons::SHIELD_HALF),
        "shield-home-outline" => Some(icons::SHIELD_HOME_OUTLINE),
        _ => None,
    }
}
