// This file was generated. DO NOT EDIT.
use crate::{Icon, icons};

#[cfg(feature = "pyo3")]
use pyo3::exceptions::PyDeprecationWarning;

#[cfg(feature = "pyo3")]
use pyo3::prelude::*;

pub(super) fn find_part_4(#[cfg(feature = "pyo3")] py: Python, slug: &str) -> Option<Icon> {
    match slug {
        "battery-50" => Some(icons::BATTERY_50),
        "battery-60-bluetooth" => Some(icons::BATTERY_60_BLUETOOTH),
        "battery-60" => Some(icons::BATTERY_60),
        "battery-70-bluetooth" => Some(icons::BATTERY_70_BLUETOOTH),
        "battery-70" => Some(icons::BATTERY_70),
        "battery-80-bluetooth" => Some(icons::BATTERY_80_BLUETOOTH),
        "battery-80" => Some(icons::BATTERY_80),
        "battery-90-bluetooth" => Some(icons::BATTERY_90_BLUETOOTH),
        "battery-90" => Some(icons::BATTERY_90),
        "battery-alert-bluetooth" => Some(icons::BATTERY_ALERT_BLUETOOTH),
        "battery-alert-variant-outline" => Some(icons::BATTERY_ALERT_VARIANT_OUTLINE),
        "battery-alert-variant" => Some(icons::BATTERY_ALERT_VARIANT),
        "battery-alert" => Some(icons::BATTERY_ALERT),
        "battery-arrow-down-outline" => Some(icons::BATTERY_ARROW_DOWN_OUTLINE),
        "battery-arrow-down" => Some(icons::BATTERY_ARROW_DOWN),
        "battery-arrow-up-outline" => Some(icons::BATTERY_ARROW_UP_OUTLINE),
        "battery-arrow-up" => Some(icons::BATTERY_ARROW_UP),
        "battery-bluetooth-variant" => Some(icons::BATTERY_BLUETOOTH_VARIANT),
        "battery-bluetooth" => Some(icons::BATTERY_BLUETOOTH),
        "battery-charging-10" => Some(icons::BATTERY_CHARGING_10),
        "battery-charging-100" => Some(icons::BATTERY_CHARGING_100),
        "battery-charging-20" => Some(icons::BATTERY_CHARGING_20),
        "battery-charging-30" => Some(icons::BATTERY_CHARGING_30),
        "battery-charging-40" => Some(icons::BATTERY_CHARGING_40),
        "battery-charging-50" => Some(icons::BATTERY_CHARGING_50),
        "battery-charging-60" => Some(icons::BATTERY_CHARGING_60),
        "battery-charging-70" => Some(icons::BATTERY_CHARGING_70),
        "battery-charging-80" => Some(icons::BATTERY_CHARGING_80),
        "battery-charging-90" => Some(icons::BATTERY_CHARGING_90),
        "battery-charging-high" => Some(icons::BATTERY_CHARGING_HIGH),
        "battery-charging-low" => Some(icons::BATTERY_CHARGING_LOW),
        "battery-charging-medium" => Some(icons::BATTERY_CHARGING_MEDIUM),
        "battery-charging-outline" => Some(icons::BATTERY_CHARGING_OUTLINE),
        "battery-charging-wireless-10" => Some(icons::BATTERY_CHARGING_WIRELESS_10),
        "battery-charging-wireless-20" => Some(icons::BATTERY_CHARGING_WIRELESS_20),
        "battery-charging-wireless-30" => Some(icons::BATTERY_CHARGING_WIRELESS_30),
        "battery-charging-wireless-40" => Some(icons::BATTERY_CHARGING_WIRELESS_40),
        "battery-charging-wireless-50" => Some(icons::BATTERY_CHARGING_WIRELESS_50),
        "battery-charging-wireless-60" => Some(icons::BATTERY_CHARGING_WIRELESS_60),
        "battery-charging-wireless-70" => Some(icons::BATTERY_CHARGING_WIRELESS_70),
        "battery-charging-wireless-80" => Some(icons::BATTERY_CHARGING_WIRELESS_80),
        "battery-charging-wireless-90" => Some(icons::BATTERY_CHARGING_WIRELESS_90),
        "battery-charging-wireless-alert" => Some(icons::BATTERY_CHARGING_WIRELESS_ALERT),
        "battery-charging-wireless-outline" => Some(icons::BATTERY_CHARGING_WIRELESS_OUTLINE),
        "battery-charging-wireless" => Some(icons::BATTERY_CHARGING_WIRELESS),
        "battery-charging" => Some(icons::BATTERY_CHARGING),
        "battery-check-outline" => Some(icons::BATTERY_CHECK_OUTLINE),
        "battery-check" => Some(icons::BATTERY_CHECK),
        "battery-clock-outline" => Some(icons::BATTERY_CLOCK_OUTLINE),
        "battery-clock" => Some(icons::BATTERY_CLOCK),
        "battery-heart-outline" => Some(icons::BATTERY_HEART_OUTLINE),
        "battery-heart-variant" => Some(icons::BATTERY_HEART_VARIANT),
        "battery-heart" => Some(icons::BATTERY_HEART),
        "battery-high" => Some(icons::BATTERY_HIGH),
        "battery-lock-open" => Some(icons::BATTERY_LOCK_OPEN),
        "battery-lock" => Some(icons::BATTERY_LOCK),
        "battery-low" => Some(icons::BATTERY_LOW),
        "battery-medium" => Some(icons::BATTERY_MEDIUM),
        "battery-minus-outline" => Some(icons::BATTERY_MINUS_OUTLINE),
        "battery-minus-variant" => Some(icons::BATTERY_MINUS_VARIANT),
        "battery-minus" => Some(icons::BATTERY_MINUS),
        "battery-negative" => Some(icons::BATTERY_NEGATIVE),
        "battery-off-outline" => Some(icons::BATTERY_OFF_OUTLINE),
        "battery-off" => Some(icons::BATTERY_OFF),
        "battery-outline" => Some(icons::BATTERY_OUTLINE),
        "battery-plus-outline" => Some(icons::BATTERY_PLUS_OUTLINE),
        "battery-plus-variant" => Some(icons::BATTERY_PLUS_VARIANT),
        "battery-plus" => Some(icons::BATTERY_PLUS),
        "battery-positive" => Some(icons::BATTERY_POSITIVE),
        "battery-remove-outline" => Some(icons::BATTERY_REMOVE_OUTLINE),
        "battery-remove" => Some(icons::BATTERY_REMOVE),
        "battery-sync-outline" => Some(icons::BATTERY_SYNC_OUTLINE),
        "battery-sync" => Some(icons::BATTERY_SYNC),
        "battery-unknown-bluetooth" => Some(icons::BATTERY_UNKNOWN_BLUETOOTH),
        "battery-unknown" => Some(icons::BATTERY_UNKNOWN),
        "battery" => Some(icons::BATTERY),
        "beach" => Some(icons::BEACH),
        "beaker-alert-outline" => Some(icons::BEAKER_ALERT_OUTLINE),
        "beaker-alert" => Some(icons::BEAKER_ALERT),
        "beaker-check-outline" => Some(icons::BEAKER_CHECK_OUTLINE),
        "beaker-check" => Some(icons::BEAKER_CHECK),
        "beaker-minus-outline" => Some(icons::BEAKER_MINUS_OUTLINE),
        "beaker-minus" => Some(icons::BEAKER_MINUS),
        "beaker-outline" => Some(icons::BEAKER_OUTLINE),
        "beaker-plus-outline" => Some(icons::BEAKER_PLUS_OUTLINE),
        "beaker-plus" => Some(icons::BEAKER_PLUS),
        "beaker-question-outline" => Some(icons::BEAKER_QUESTION_OUTLINE),
        "beaker-question" => Some(icons::BEAKER_QUESTION),
        "beaker-remove-outline" => Some(icons::BEAKER_REMOVE_OUTLINE),
        "beaker-remove" => Some(icons::BEAKER_REMOVE),
        "beaker" => Some(icons::BEAKER),
        "bed-clock" => Some(icons::BED_CLOCK),
        "bed-double-outline" => Some(icons::BED_DOUBLE_OUTLINE),
        "bed-double" => Some(icons::BED_DOUBLE),
        "bed-empty" => Some(icons::BED_EMPTY),
        "bed-king-outline" => Some(icons::BED_KING_OUTLINE),
        "bed-king" => Some(icons::BED_KING),
        "bed-outline" => Some(icons::BED_OUTLINE),
        "bed-queen-outline" => Some(icons::BED_QUEEN_OUTLINE),
        "bed-queen" => Some(icons::BED_QUEEN),
        "bed-single-outline" => Some(icons::BED_SINGLE_OUTLINE),
        "bed-single" => Some(icons::BED_SINGLE),
        "bed" => Some(icons::BED),
        "bee-flower" => Some(icons::BEE_FLOWER),
        "bee" => Some(icons::BEE),
        "beehive-off-outline" => Some(icons::BEEHIVE_OFF_OUTLINE),
        "beehive-outline" => Some(icons::BEEHIVE_OUTLINE),
        "beekeeper" => Some(icons::BEEKEEPER),
        "beer-outline" => Some(icons::BEER_OUTLINE),
        "beer" => Some(icons::BEER),
        "bell-alert-outline" => Some(icons::BELL_ALERT_OUTLINE),
        "bell-alert" => Some(icons::BELL_ALERT),
        "bell-badge-outline" => Some(icons::BELL_BADGE_OUTLINE),
        "bell-badge" => Some(icons::BELL_BADGE),
        "bell-cancel-outline" => Some(icons::BELL_CANCEL_OUTLINE),
        "bell-cancel" => Some(icons::BELL_CANCEL),
        "bell-check-outline" => Some(icons::BELL_CHECK_OUTLINE),
        "bell-check" => Some(icons::BELL_CHECK),
        "bell-circle-outline" => Some(icons::BELL_CIRCLE_OUTLINE),
        "bell-circle" => Some(icons::BELL_CIRCLE),
        "bell-cog-outline" => Some(icons::BELL_COG_OUTLINE),
        "bell-cog" => Some(icons::BELL_COG),
        "bell-minus-outline" => Some(icons::BELL_MINUS_OUTLINE),
        "bell-minus" => Some(icons::BELL_MINUS),
        "bell-off-outline" => Some(icons::BELL_OFF_OUTLINE),
        "bell-off" => Some(icons::BELL_OFF),
        "bell-outline" => Some(icons::BELL_OUTLINE),
        "bell-plus-outline" => Some(icons::BELL_PLUS_OUTLINE),
        "bell-plus" => Some(icons::BELL_PLUS),
        "bell-remove-outline" => Some(icons::BELL_REMOVE_OUTLINE),
        "bell-remove" => Some(icons::BELL_REMOVE),
        "bell-ring-outline" => Some(icons::BELL_RING_OUTLINE),
        "bell-ring" => Some(icons::BELL_RING),
        "bell-sleep-outline" => Some(icons::BELL_SLEEP_OUTLINE),
        "bell-sleep" => Some(icons::BELL_SLEEP),
        "bell" => Some(icons::BELL),
        "bench-back" => Some(icons::BENCH_BACK),
        "bench" => Some(icons::BENCH),
        "beta" => Some(icons::BETA),
        "betamax" => Some(icons::BETAMAX),
        "biathlon" => Some(icons::BIATHLON),
        "bicycle-basket" => Some(icons::BICYCLE_BASKET),
        "bicycle-cargo" => Some(icons::BICYCLE_CARGO),
        "bicycle-electric" => Some(icons::BICYCLE_ELECTRIC),
        "bicycle-penny-farthing" => Some(icons::BICYCLE_PENNY_FARTHING),
        "bicycle" => Some(icons::BICYCLE),
        "bike-fast" => Some(icons::BIKE_FAST),
        "bike-pedal-clipless" => Some(icons::BIKE_PEDAL_CLIPLESS),
        "bike-pedal-mountain" => Some(icons::BIKE_PEDAL_MOUNTAIN),
        "bike-pedal" => Some(icons::BIKE_PEDAL),
        "bike" => Some(icons::BIKE),
        "billboard" => Some(icons::BILLBOARD),
        "billiards-rack" => Some(icons::BILLIARDS_RACK),
        "billiards" => Some(icons::BILLIARDS),
        "binoculars" => Some(icons::BINOCULARS),
        "bio" => Some(icons::BIO),
        "biohazard" => Some(icons::BIOHAZARD),
        "bird" => Some(icons::BIRD),
        #[allow(deprecated)]
        "bitbucket" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'bitbucket' is deprecated.").print(py);
            }
            Some(icons::BITBUCKET)
        }
        #[allow(deprecated)]
        "bitcoin" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'bitcoin' is deprecated.").print(py);
            }
            Some(icons::BITCOIN)
        }
        #[allow(deprecated)]
        "black-mesa" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'black-mesa' is deprecated.").print(py);
            }
            Some(icons::BLACK_MESA)
        }
        "blender-outline" => Some(icons::BLENDER_OUTLINE),
        #[allow(deprecated)]
        "blender-software" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'blender-software' is deprecated.")
                    .print(py);
            }
            Some(icons::BLENDER_SOFTWARE)
        }
        "blender" => Some(icons::BLENDER),
        "blinds-horizontal-closed" => Some(icons::BLINDS_HORIZONTAL_CLOSED),
        "blinds-horizontal" => Some(icons::BLINDS_HORIZONTAL),
        "blinds-open" => Some(icons::BLINDS_OPEN),
        "blinds-vertical-closed" => Some(icons::BLINDS_VERTICAL_CLOSED),
        "blinds-vertical" => Some(icons::BLINDS_VERTICAL),
        "blinds" => Some(icons::BLINDS),
        "block-helper" => Some(icons::BLOCK_HELPER),
        "blood-bag" => Some(icons::BLOOD_BAG),
        "bluetooth-audio" => Some(icons::BLUETOOTH_AUDIO),
        "bluetooth-connect" => Some(icons::BLUETOOTH_CONNECT),
        "bluetooth-off" => Some(icons::BLUETOOTH_OFF),
        "bluetooth-settings" => Some(icons::BLUETOOTH_SETTINGS),
        "bluetooth-transfer" => Some(icons::BLUETOOTH_TRANSFER),
        "bluetooth" => Some(icons::BLUETOOTH),
        "blur-linear" => Some(icons::BLUR_LINEAR),
        "blur-off" => Some(icons::BLUR_OFF),
        "blur-radial" => Some(icons::BLUR_RADIAL),
        "blur" => Some(icons::BLUR),
        "bolt" => Some(icons::BOLT),
        "bomb-off" => Some(icons::BOMB_OFF),
        "bomb" => Some(icons::BOMB),
        "bone-off" => Some(icons::BONE_OFF),
        "bone" => Some(icons::BONE),
        "book-account-outline" => Some(icons::BOOK_ACCOUNT_OUTLINE),
        "book-account" => Some(icons::BOOK_ACCOUNT),
        "book-alert-outline" => Some(icons::BOOK_ALERT_OUTLINE),
        "book-alert" => Some(icons::BOOK_ALERT),
        "book-alphabet" => Some(icons::BOOK_ALPHABET),
        "book-arrow-down-outline" => Some(icons::BOOK_ARROW_DOWN_OUTLINE),
        "book-arrow-down" => Some(icons::BOOK_ARROW_DOWN),
        "book-arrow-left-outline" => Some(icons::BOOK_ARROW_LEFT_OUTLINE),
        "book-arrow-left" => Some(icons::BOOK_ARROW_LEFT),
        "book-arrow-right-outline" => Some(icons::BOOK_ARROW_RIGHT_OUTLINE),
        "book-arrow-right" => Some(icons::BOOK_ARROW_RIGHT),
        "book-arrow-up-outline" => Some(icons::BOOK_ARROW_UP_OUTLINE),
        "book-arrow-up" => Some(icons::BOOK_ARROW_UP),
        _ => None,
    }
}
