// This file was generated. DO NOT EDIT.
use crate::{Icon, icons};

#[cfg(feature = "pyo3")]
use pyo3::exceptions::PyDeprecationWarning;

#[cfg(feature = "pyo3")]
use pyo3::prelude::*;

pub(super) fn find_part_28(#[cfg(feature = "pyo3")] py: Python, slug: &str) -> Option<Icon> {
    match slug {
        "receipt-text-remove" => Some(icons::RECEIPT_TEXT_REMOVE),
        "receipt-text-send-outline" => Some(icons::RECEIPT_TEXT_SEND_OUTLINE),
        "receipt-text-send" => Some(icons::RECEIPT_TEXT_SEND),
        "receipt-text" => Some(icons::RECEIPT_TEXT),
        "receipt" => Some(icons::RECEIPT),
        "record-circle-outline" => Some(icons::RECORD_CIRCLE_OUTLINE),
        "record-circle" => Some(icons::RECORD_CIRCLE),
        "record-player" => Some(icons::RECORD_PLAYER),
        "record-rec" => Some(icons::RECORD_REC),
        "record" => Some(icons::RECORD),
        "rectangle-outline" => Some(icons::RECTANGLE_OUTLINE),
        "rectangle" => Some(icons::RECTANGLE),
        "recycle-variant" => Some(icons::RECYCLE_VARIANT),
        "recycle" => Some(icons::RECYCLE),
        #[allow(deprecated)]
        "reddit" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'reddit' is deprecated.").print(py);
            }
            Some(icons::REDDIT)
        }
        #[allow(deprecated)]
        "redhat" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'redhat' is deprecated.").print(py);
            }
            Some(icons::REDHAT)
        }
        "redo-variant" => Some(icons::REDO_VARIANT),
        "redo" => Some(icons::REDO),
        "reflect-horizontal" => Some(icons::REFLECT_HORIZONTAL),
        "reflect-vertical" => Some(icons::REFLECT_VERTICAL),
        "refresh-auto" => Some(icons::REFRESH_AUTO),
        "refresh-circle" => Some(icons::REFRESH_CIRCLE),
        "refresh" => Some(icons::REFRESH),
        "regex" => Some(icons::REGEX),
        "registered-trademark" => Some(icons::REGISTERED_TRADEMARK),
        "reiterate" => Some(icons::REITERATE),
        "relation-many-to-many" => Some(icons::RELATION_MANY_TO_MANY),
        "relation-many-to-one-or-many" => Some(icons::RELATION_MANY_TO_ONE_OR_MANY),
        "relation-many-to-one" => Some(icons::RELATION_MANY_TO_ONE),
        "relation-many-to-only-one" => Some(icons::RELATION_MANY_TO_ONLY_ONE),
        "relation-many-to-zero-or-many" => Some(icons::RELATION_MANY_TO_ZERO_OR_MANY),
        "relation-many-to-zero-or-one" => Some(icons::RELATION_MANY_TO_ZERO_OR_ONE),
        "relation-one-or-many-to-many" => Some(icons::RELATION_ONE_OR_MANY_TO_MANY),
        "relation-one-or-many-to-one-or-many" => Some(icons::RELATION_ONE_OR_MANY_TO_ONE_OR_MANY),
        "relation-one-or-many-to-one" => Some(icons::RELATION_ONE_OR_MANY_TO_ONE),
        "relation-one-or-many-to-only-one" => Some(icons::RELATION_ONE_OR_MANY_TO_ONLY_ONE),
        "relation-one-or-many-to-zero-or-many" => Some(icons::RELATION_ONE_OR_MANY_TO_ZERO_OR_MANY),
        "relation-one-or-many-to-zero-or-one" => Some(icons::RELATION_ONE_OR_MANY_TO_ZERO_OR_ONE),
        "relation-one-to-many" => Some(icons::RELATION_ONE_TO_MANY),
        "relation-one-to-one-or-many" => Some(icons::RELATION_ONE_TO_ONE_OR_MANY),
        "relation-one-to-one" => Some(icons::RELATION_ONE_TO_ONE),
        "relation-one-to-only-one" => Some(icons::RELATION_ONE_TO_ONLY_ONE),
        "relation-one-to-zero-or-many" => Some(icons::RELATION_ONE_TO_ZERO_OR_MANY),
        "relation-one-to-zero-or-one" => Some(icons::RELATION_ONE_TO_ZERO_OR_ONE),
        "relation-only-one-to-many" => Some(icons::RELATION_ONLY_ONE_TO_MANY),
        "relation-only-one-to-one-or-many" => Some(icons::RELATION_ONLY_ONE_TO_ONE_OR_MANY),
        "relation-only-one-to-one" => Some(icons::RELATION_ONLY_ONE_TO_ONE),
        "relation-only-one-to-only-one" => Some(icons::RELATION_ONLY_ONE_TO_ONLY_ONE),
        "relation-only-one-to-zero-or-many" => Some(icons::RELATION_ONLY_ONE_TO_ZERO_OR_MANY),
        "relation-only-one-to-zero-or-one" => Some(icons::RELATION_ONLY_ONE_TO_ZERO_OR_ONE),
        "relation-zero-or-many-to-many" => Some(icons::RELATION_ZERO_OR_MANY_TO_MANY),
        "relation-zero-or-many-to-one-or-many" => Some(icons::RELATION_ZERO_OR_MANY_TO_ONE_OR_MANY),
        "relation-zero-or-many-to-one" => Some(icons::RELATION_ZERO_OR_MANY_TO_ONE),
        "relation-zero-or-many-to-only-one" => Some(icons::RELATION_ZERO_OR_MANY_TO_ONLY_ONE),
        "relation-zero-or-many-to-zero-or-many" => {
            Some(icons::RELATION_ZERO_OR_MANY_TO_ZERO_OR_MANY)
        }
        "relation-zero-or-many-to-zero-or-one" => Some(icons::RELATION_ZERO_OR_MANY_TO_ZERO_OR_ONE),
        "relation-zero-or-one-to-many" => Some(icons::RELATION_ZERO_OR_ONE_TO_MANY),
        "relation-zero-or-one-to-one-or-many" => Some(icons::RELATION_ZERO_OR_ONE_TO_ONE_OR_MANY),
        "relation-zero-or-one-to-one" => Some(icons::RELATION_ZERO_OR_ONE_TO_ONE),
        "relation-zero-or-one-to-only-one" => Some(icons::RELATION_ZERO_OR_ONE_TO_ONLY_ONE),
        "relation-zero-or-one-to-zero-or-many" => Some(icons::RELATION_ZERO_OR_ONE_TO_ZERO_OR_MANY),
        "relation-zero-or-one-to-zero-or-one" => Some(icons::RELATION_ZERO_OR_ONE_TO_ZERO_OR_ONE),
        "relative-scale" => Some(icons::RELATIVE_SCALE),
        "reload-alert" => Some(icons::RELOAD_ALERT),
        "reload" => Some(icons::RELOAD),
        "reminder" => Some(icons::REMINDER),
        "remote-desktop" => Some(icons::REMOTE_DESKTOP),
        "remote-off" => Some(icons::REMOTE_OFF),
        "remote-tv-off" => Some(icons::REMOTE_TV_OFF),
        "remote-tv" => Some(icons::REMOTE_TV),
        "remote" => Some(icons::REMOTE),
        "rename-box-outline" => Some(icons::RENAME_BOX_OUTLINE),
        "rename-box" => Some(icons::RENAME_BOX),
        "rename-outline" => Some(icons::RENAME_OUTLINE),
        "rename" => Some(icons::RENAME),
        "reorder-horizontal" => Some(icons::REORDER_HORIZONTAL),
        "reorder-vertical" => Some(icons::REORDER_VERTICAL),
        "repeat-off" => Some(icons::REPEAT_OFF),
        "repeat-once" => Some(icons::REPEAT_ONCE),
        "repeat-variant" => Some(icons::REPEAT_VARIANT),
        "repeat" => Some(icons::REPEAT),
        "replay" => Some(icons::REPLAY),
        "reply-all-outline" => Some(icons::REPLY_ALL_OUTLINE),
        "reply-all" => Some(icons::REPLY_ALL),
        "reply-circle" => Some(icons::REPLY_CIRCLE),
        "reply-outline" => Some(icons::REPLY_OUTLINE),
        "reply" => Some(icons::REPLY),
        "reproduction" => Some(icons::REPRODUCTION),
        "resistor-nodes" => Some(icons::RESISTOR_NODES),
        "resistor" => Some(icons::RESISTOR),
        "resize-bottom-right" => Some(icons::RESIZE_BOTTOM_RIGHT),
        "resize" => Some(icons::RESIZE),
        "responsive" => Some(icons::RESPONSIVE),
        "restart-alert" => Some(icons::RESTART_ALERT),
        "restart-off" => Some(icons::RESTART_OFF),
        "restart" => Some(icons::RESTART),
        "restore-alert" => Some(icons::RESTORE_ALERT),
        "restore" => Some(icons::RESTORE),
        "rewind-10" => Some(icons::REWIND_10),
        "rewind-15" => Some(icons::REWIND_15),
        "rewind-30" => Some(icons::REWIND_30),
        "rewind-45" => Some(icons::REWIND_45),
        "rewind-5" => Some(icons::REWIND_5),
        "rewind-60" => Some(icons::REWIND_60),
        "rewind-outline" => Some(icons::REWIND_OUTLINE),
        "rewind" => Some(icons::REWIND),
        "rhombus-medium-outline" => Some(icons::RHOMBUS_MEDIUM_OUTLINE),
        "rhombus-medium" => Some(icons::RHOMBUS_MEDIUM),
        "rhombus-outline" => Some(icons::RHOMBUS_OUTLINE),
        "rhombus-split-outline" => Some(icons::RHOMBUS_SPLIT_OUTLINE),
        "rhombus-split" => Some(icons::RHOMBUS_SPLIT),
        "rhombus" => Some(icons::RHOMBUS),
        "ribbon" => Some(icons::RIBBON),
        "rice" => Some(icons::RICE),
        "rickshaw-electric" => Some(icons::RICKSHAW_ELECTRIC),
        "rickshaw" => Some(icons::RICKSHAW),
        "ring" => Some(icons::RING),
        "rivet" => Some(icons::RIVET),
        "road-variant" => Some(icons::ROAD_VARIANT),
        "road" => Some(icons::ROAD),
        "robber" => Some(icons::ROBBER),
        "robot-angry-outline" => Some(icons::ROBOT_ANGRY_OUTLINE),
        "robot-angry" => Some(icons::ROBOT_ANGRY),
        "robot-confused-outline" => Some(icons::ROBOT_CONFUSED_OUTLINE),
        "robot-confused" => Some(icons::ROBOT_CONFUSED),
        "robot-dead-outline" => Some(icons::ROBOT_DEAD_OUTLINE),
        "robot-dead" => Some(icons::ROBOT_DEAD),
        "robot-excited-outline" => Some(icons::ROBOT_EXCITED_OUTLINE),
        "robot-excited" => Some(icons::ROBOT_EXCITED),
        "robot-happy-outline" => Some(icons::ROBOT_HAPPY_OUTLINE),
        "robot-happy" => Some(icons::ROBOT_HAPPY),
        "robot-industrial-outline" => Some(icons::ROBOT_INDUSTRIAL_OUTLINE),
        "robot-industrial" => Some(icons::ROBOT_INDUSTRIAL),
        "robot-love-outline" => Some(icons::ROBOT_LOVE_OUTLINE),
        "robot-love" => Some(icons::ROBOT_LOVE),
        "robot-mower-outline" => Some(icons::ROBOT_MOWER_OUTLINE),
        "robot-mower" => Some(icons::ROBOT_MOWER),
        "robot-off-outline" => Some(icons::ROBOT_OFF_OUTLINE),
        "robot-off" => Some(icons::ROBOT_OFF),
        "robot-outline" => Some(icons::ROBOT_OUTLINE),
        "robot-vacuum-alert" => Some(icons::ROBOT_VACUUM_ALERT),
        "robot-vacuum-off" => Some(icons::ROBOT_VACUUM_OFF),
        "robot-vacuum-variant-alert" => Some(icons::ROBOT_VACUUM_VARIANT_ALERT),
        "robot-vacuum-variant-off" => Some(icons::ROBOT_VACUUM_VARIANT_OFF),
        "robot-vacuum-variant" => Some(icons::ROBOT_VACUUM_VARIANT),
        "robot-vacuum" => Some(icons::ROBOT_VACUUM),
        "robot" => Some(icons::ROBOT),
        "rocket-launch-outline" => Some(icons::ROCKET_LAUNCH_OUTLINE),
        "rocket-launch" => Some(icons::ROCKET_LAUNCH),
        "rocket-outline" => Some(icons::ROCKET_OUTLINE),
        "rocket" => Some(icons::ROCKET),
        "rodent" => Some(icons::RODENT),
        "roller-shade-closed" => Some(icons::ROLLER_SHADE_CLOSED),
        "roller-shade" => Some(icons::ROLLER_SHADE),
        "roller-skate-off" => Some(icons::ROLLER_SKATE_OFF),
        "roller-skate" => Some(icons::ROLLER_SKATE),
        "rollerblade-off" => Some(icons::ROLLERBLADE_OFF),
        "rollerblade" => Some(icons::ROLLERBLADE),
        #[allow(deprecated)]
        "rollupjs" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'rollupjs' is deprecated.").print(py);
            }
            Some(icons::ROLLUPJS)
        }
        "rolodex-outline" => Some(icons::ROLODEX_OUTLINE),
        "rolodex" => Some(icons::ROLODEX),
        "roman-numeral-1" => Some(icons::ROMAN_NUMERAL_1),
        "roman-numeral-10" => Some(icons::ROMAN_NUMERAL_10),
        "roman-numeral-2" => Some(icons::ROMAN_NUMERAL_2),
        "roman-numeral-3" => Some(icons::ROMAN_NUMERAL_3),
        "roman-numeral-4" => Some(icons::ROMAN_NUMERAL_4),
        "roman-numeral-5" => Some(icons::ROMAN_NUMERAL_5),
        "roman-numeral-6" => Some(icons::ROMAN_NUMERAL_6),
        "roman-numeral-7" => Some(icons::ROMAN_NUMERAL_7),
        "roman-numeral-8" => Some(icons::ROMAN_NUMERAL_8),
        "roman-numeral-9" => Some(icons::ROMAN_NUMERAL_9),
        "room-service-outline" => Some(icons::ROOM_SERVICE_OUTLINE),
        "room-service" => Some(icons::ROOM_SERVICE),
        "rotate-360" => Some(icons::ROTATE_360),
        "rotate-3d-variant" => Some(icons::ROTATE_3D_VARIANT),
        "rotate-3d" => Some(icons::ROTATE_3D),
        "rotate-left-variant" => Some(icons::ROTATE_LEFT_VARIANT),
        "rotate-left" => Some(icons::ROTATE_LEFT),
        "rotate-orbit" => Some(icons::ROTATE_ORBIT),
        "rotate-right-variant" => Some(icons::ROTATE_RIGHT_VARIANT),
        "rotate-right" => Some(icons::ROTATE_RIGHT),
        "rounded-corner" => Some(icons::ROUNDED_CORNER),
        "router-network-wireless" => Some(icons::ROUTER_NETWORK_WIRELESS),
        "router-network" => Some(icons::ROUTER_NETWORK),
        "router-wireless-off" => Some(icons::ROUTER_WIRELESS_OFF),
        "router-wireless-settings" => Some(icons::ROUTER_WIRELESS_SETTINGS),
        "router-wireless" => Some(icons::ROUTER_WIRELESS),
        "router" => Some(icons::ROUTER),
        "routes-clock" => Some(icons::ROUTES_CLOCK),
        "routes" => Some(icons::ROUTES),
        "rowing" => Some(icons::ROWING),
        "rss-box" => Some(icons::RSS_BOX),
        "rss-off" => Some(icons::RSS_OFF),
        "rss" => Some(icons::RSS),
        "rug" => Some(icons::RUG),
        "rugby" => Some(icons::RUGBY),
        "ruler-square-compass" => Some(icons::RULER_SQUARE_COMPASS),
        "ruler-square" => Some(icons::RULER_SQUARE),
        "ruler" => Some(icons::RULER),
        "run-fast" => Some(icons::RUN_FAST),
        _ => None,
    }
}
