// This file was generated. DO NOT EDIT.
use crate::{Icon, icons};

#[cfg(feature = "pyo3")]
use pyo3::exceptions::PyDeprecationWarning;

#[cfg(feature = "pyo3")]
use pyo3::prelude::*;

pub(super) fn find_part_11(#[cfg(feature = "pyo3")] py: Python, slug: &str) -> Option<Icon> {
    match slug {
        "credit-card-remove" => Some(icons::CREDIT_CARD_REMOVE),
        "credit-card-scan-outline" => Some(icons::CREDIT_CARD_SCAN_OUTLINE),
        "credit-card-scan" => Some(icons::CREDIT_CARD_SCAN),
        "credit-card-search-outline" => Some(icons::CREDIT_CARD_SEARCH_OUTLINE),
        "credit-card-search" => Some(icons::CREDIT_CARD_SEARCH),
        "credit-card-settings-outline" => Some(icons::CREDIT_CARD_SETTINGS_OUTLINE),
        "credit-card-settings" => Some(icons::CREDIT_CARD_SETTINGS),
        "credit-card-sync-outline" => Some(icons::CREDIT_CARD_SYNC_OUTLINE),
        "credit-card-sync" => Some(icons::CREDIT_CARD_SYNC),
        "credit-card-wireless-off-outline" => Some(icons::CREDIT_CARD_WIRELESS_OFF_OUTLINE),
        "credit-card-wireless-off" => Some(icons::CREDIT_CARD_WIRELESS_OFF),
        "credit-card-wireless-outline" => Some(icons::CREDIT_CARD_WIRELESS_OUTLINE),
        "credit-card-wireless" => Some(icons::CREDIT_CARD_WIRELESS),
        "credit-card" => Some(icons::CREDIT_CARD),
        "cricket" => Some(icons::CRICKET),
        "crop-free" => Some(icons::CROP_FREE),
        "crop-landscape" => Some(icons::CROP_LANDSCAPE),
        "crop-portrait" => Some(icons::CROP_PORTRAIT),
        "crop-rotate" => Some(icons::CROP_ROTATE),
        "crop-square" => Some(icons::CROP_SQUARE),
        "crop" => Some(icons::CROP),
        "cross-bolnisi" => Some(icons::CROSS_BOLNISI),
        "cross-celtic" => Some(icons::CROSS_CELTIC),
        "cross-outline" => Some(icons::CROSS_OUTLINE),
        "cross" => Some(icons::CROSS),
        "crosshairs-gps" => Some(icons::CROSSHAIRS_GPS),
        "crosshairs-off" => Some(icons::CROSSHAIRS_OFF),
        "crosshairs-question" => Some(icons::CROSSHAIRS_QUESTION),
        "crosshairs" => Some(icons::CROSSHAIRS),
        "crowd" => Some(icons::CROWD),
        "crown-circle-outline" => Some(icons::CROWN_CIRCLE_OUTLINE),
        "crown-circle" => Some(icons::CROWN_CIRCLE),
        "crown-outline" => Some(icons::CROWN_OUTLINE),
        "crown" => Some(icons::CROWN),
        #[allow(deprecated)]
        "cryengine" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'cryengine' is deprecated.").print(py);
            }
            Some(icons::CRYENGINE)
        }
        "crystal-ball" => Some(icons::CRYSTAL_BALL),
        "cube-off-outline" => Some(icons::CUBE_OFF_OUTLINE),
        "cube-off" => Some(icons::CUBE_OFF),
        "cube-outline" => Some(icons::CUBE_OUTLINE),
        "cube-scan" => Some(icons::CUBE_SCAN),
        "cube-send" => Some(icons::CUBE_SEND),
        "cube-unfolded" => Some(icons::CUBE_UNFOLDED),
        "cube" => Some(icons::CUBE),
        "cup-off-outline" => Some(icons::CUP_OFF_OUTLINE),
        "cup-off" => Some(icons::CUP_OFF),
        "cup-outline" => Some(icons::CUP_OUTLINE),
        "cup-water" => Some(icons::CUP_WATER),
        "cup" => Some(icons::CUP),
        "cupboard-outline" => Some(icons::CUPBOARD_OUTLINE),
        "cupboard" => Some(icons::CUPBOARD),
        "cupcake" => Some(icons::CUPCAKE),
        "curling" => Some(icons::CURLING),
        "currency-bdt" => Some(icons::CURRENCY_BDT),
        "currency-brl" => Some(icons::CURRENCY_BRL),
        "currency-btc" => Some(icons::CURRENCY_BTC),
        "currency-cny" => Some(icons::CURRENCY_CNY),
        "currency-eth" => Some(icons::CURRENCY_ETH),
        "currency-eur-off" => Some(icons::CURRENCY_EUR_OFF),
        "currency-eur" => Some(icons::CURRENCY_EUR),
        "currency-fra" => Some(icons::CURRENCY_FRA),
        "currency-gbp" => Some(icons::CURRENCY_GBP),
        "currency-ils" => Some(icons::CURRENCY_ILS),
        "currency-inr" => Some(icons::CURRENCY_INR),
        "currency-jpy" => Some(icons::CURRENCY_JPY),
        "currency-krw" => Some(icons::CURRENCY_KRW),
        "currency-kzt" => Some(icons::CURRENCY_KZT),
        "currency-mnt" => Some(icons::CURRENCY_MNT),
        "currency-ngn" => Some(icons::CURRENCY_NGN),
        "currency-php" => Some(icons::CURRENCY_PHP),
        "currency-rial" => Some(icons::CURRENCY_RIAL),
        "currency-rub" => Some(icons::CURRENCY_RUB),
        "currency-rupee" => Some(icons::CURRENCY_RUPEE),
        "currency-sign" => Some(icons::CURRENCY_SIGN),
        "currency-thb" => Some(icons::CURRENCY_THB),
        "currency-try" => Some(icons::CURRENCY_TRY),
        "currency-twd" => Some(icons::CURRENCY_TWD),
        "currency-uah" => Some(icons::CURRENCY_UAH),
        "currency-usd-off" => Some(icons::CURRENCY_USD_OFF),
        "currency-usd" => Some(icons::CURRENCY_USD),
        "current-ac" => Some(icons::CURRENT_AC),
        "current-dc" => Some(icons::CURRENT_DC),
        "cursor-default-click-outline" => Some(icons::CURSOR_DEFAULT_CLICK_OUTLINE),
        "cursor-default-click" => Some(icons::CURSOR_DEFAULT_CLICK),
        "cursor-default-gesture-outline" => Some(icons::CURSOR_DEFAULT_GESTURE_OUTLINE),
        "cursor-default-gesture" => Some(icons::CURSOR_DEFAULT_GESTURE),
        "cursor-default-outline" => Some(icons::CURSOR_DEFAULT_OUTLINE),
        "cursor-default" => Some(icons::CURSOR_DEFAULT),
        "cursor-move" => Some(icons::CURSOR_MOVE),
        "cursor-pointer" => Some(icons::CURSOR_POINTER),
        "cursor-text" => Some(icons::CURSOR_TEXT),
        "curtains-closed" => Some(icons::CURTAINS_CLOSED),
        "curtains" => Some(icons::CURTAINS),
        "cylinder-off" => Some(icons::CYLINDER_OFF),
        "cylinder" => Some(icons::CYLINDER),
        "dance-ballroom" => Some(icons::DANCE_BALLROOM),
        "dance-pole" => Some(icons::DANCE_POLE),
        "data-matrix-edit" => Some(icons::DATA_MATRIX_EDIT),
        "data-matrix-minus" => Some(icons::DATA_MATRIX_MINUS),
        "data-matrix-plus" => Some(icons::DATA_MATRIX_PLUS),
        "data-matrix-remove" => Some(icons::DATA_MATRIX_REMOVE),
        "data-matrix-scan" => Some(icons::DATA_MATRIX_SCAN),
        "data-matrix" => Some(icons::DATA_MATRIX),
        "database-alert-outline" => Some(icons::DATABASE_ALERT_OUTLINE),
        "database-alert" => Some(icons::DATABASE_ALERT),
        "database-arrow-down-outline" => Some(icons::DATABASE_ARROW_DOWN_OUTLINE),
        "database-arrow-down" => Some(icons::DATABASE_ARROW_DOWN),
        "database-arrow-left-outline" => Some(icons::DATABASE_ARROW_LEFT_OUTLINE),
        "database-arrow-left" => Some(icons::DATABASE_ARROW_LEFT),
        "database-arrow-right-outline" => Some(icons::DATABASE_ARROW_RIGHT_OUTLINE),
        "database-arrow-right" => Some(icons::DATABASE_ARROW_RIGHT),
        "database-arrow-up-outline" => Some(icons::DATABASE_ARROW_UP_OUTLINE),
        "database-arrow-up" => Some(icons::DATABASE_ARROW_UP),
        "database-check-outline" => Some(icons::DATABASE_CHECK_OUTLINE),
        "database-check" => Some(icons::DATABASE_CHECK),
        "database-clock-outline" => Some(icons::DATABASE_CLOCK_OUTLINE),
        "database-clock" => Some(icons::DATABASE_CLOCK),
        "database-cog-outline" => Some(icons::DATABASE_COG_OUTLINE),
        "database-cog" => Some(icons::DATABASE_COG),
        "database-edit-outline" => Some(icons::DATABASE_EDIT_OUTLINE),
        "database-edit" => Some(icons::DATABASE_EDIT),
        "database-export-outline" => Some(icons::DATABASE_EXPORT_OUTLINE),
        "database-export" => Some(icons::DATABASE_EXPORT),
        "database-eye-off-outline" => Some(icons::DATABASE_EYE_OFF_OUTLINE),
        "database-eye-off" => Some(icons::DATABASE_EYE_OFF),
        "database-eye-outline" => Some(icons::DATABASE_EYE_OUTLINE),
        "database-eye" => Some(icons::DATABASE_EYE),
        "database-import-outline" => Some(icons::DATABASE_IMPORT_OUTLINE),
        "database-import" => Some(icons::DATABASE_IMPORT),
        "database-lock-outline" => Some(icons::DATABASE_LOCK_OUTLINE),
        "database-lock" => Some(icons::DATABASE_LOCK),
        "database-marker-outline" => Some(icons::DATABASE_MARKER_OUTLINE),
        "database-marker" => Some(icons::DATABASE_MARKER),
        "database-minus-outline" => Some(icons::DATABASE_MINUS_OUTLINE),
        "database-minus" => Some(icons::DATABASE_MINUS),
        "database-off-outline" => Some(icons::DATABASE_OFF_OUTLINE),
        "database-off" => Some(icons::DATABASE_OFF),
        "database-outline" => Some(icons::DATABASE_OUTLINE),
        "database-plus-outline" => Some(icons::DATABASE_PLUS_OUTLINE),
        "database-plus" => Some(icons::DATABASE_PLUS),
        "database-refresh-outline" => Some(icons::DATABASE_REFRESH_OUTLINE),
        "database-refresh" => Some(icons::DATABASE_REFRESH),
        "database-remove-outline" => Some(icons::DATABASE_REMOVE_OUTLINE),
        "database-remove" => Some(icons::DATABASE_REMOVE),
        "database-search-outline" => Some(icons::DATABASE_SEARCH_OUTLINE),
        "database-search" => Some(icons::DATABASE_SEARCH),
        "database-settings-outline" => Some(icons::DATABASE_SETTINGS_OUTLINE),
        "database-settings" => Some(icons::DATABASE_SETTINGS),
        "database-sync-outline" => Some(icons::DATABASE_SYNC_OUTLINE),
        "database-sync" => Some(icons::DATABASE_SYNC),
        "database" => Some(icons::DATABASE),
        "death-star-variant" => Some(icons::DEATH_STAR_VARIANT),
        "death-star" => Some(icons::DEATH_STAR),
        "deathly-hallows" => Some(icons::DEATHLY_HALLOWS),
        #[allow(deprecated)]
        "debian" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'debian' is deprecated.").print(py);
            }
            Some(icons::DEBIAN)
        }
        "debug-step-into" => Some(icons::DEBUG_STEP_INTO),
        "debug-step-out" => Some(icons::DEBUG_STEP_OUT),
        "debug-step-over" => Some(icons::DEBUG_STEP_OVER),
        "decagram-outline" => Some(icons::DECAGRAM_OUTLINE),
        "decagram" => Some(icons::DECAGRAM),
        "decimal-comma-decrease" => Some(icons::DECIMAL_COMMA_DECREASE),
        "decimal-comma-increase" => Some(icons::DECIMAL_COMMA_INCREASE),
        "decimal-comma" => Some(icons::DECIMAL_COMMA),
        "decimal-decrease" => Some(icons::DECIMAL_DECREASE),
        "decimal-increase" => Some(icons::DECIMAL_INCREASE),
        "decimal" => Some(icons::DECIMAL),
        "delete-alert-outline" => Some(icons::DELETE_ALERT_OUTLINE),
        "delete-alert" => Some(icons::DELETE_ALERT),
        "delete-circle-outline" => Some(icons::DELETE_CIRCLE_OUTLINE),
        "delete-circle" => Some(icons::DELETE_CIRCLE),
        "delete-clock-outline" => Some(icons::DELETE_CLOCK_OUTLINE),
        "delete-clock" => Some(icons::DELETE_CLOCK),
        "delete-empty-outline" => Some(icons::DELETE_EMPTY_OUTLINE),
        "delete-empty" => Some(icons::DELETE_EMPTY),
        "delete-forever-outline" => Some(icons::DELETE_FOREVER_OUTLINE),
        "delete-forever" => Some(icons::DELETE_FOREVER),
        "delete-off-outline" => Some(icons::DELETE_OFF_OUTLINE),
        "delete-off" => Some(icons::DELETE_OFF),
        "delete-outline" => Some(icons::DELETE_OUTLINE),
        "delete-restore" => Some(icons::DELETE_RESTORE),
        "delete-sweep-outline" => Some(icons::DELETE_SWEEP_OUTLINE),
        "delete-sweep" => Some(icons::DELETE_SWEEP),
        "delete-variant" => Some(icons::DELETE_VARIANT),
        "delete" => Some(icons::DELETE),
        "delta" => Some(icons::DELTA),
        "desk-lamp-off" => Some(icons::DESK_LAMP_OFF),
        "desk-lamp-on" => Some(icons::DESK_LAMP_ON),
        "desk-lamp" => Some(icons::DESK_LAMP),
        "desk" => Some(icons::DESK),
        "deskphone" => Some(icons::DESKPHONE),
        "desktop-classic" => Some(icons::DESKTOP_CLASSIC),
        "desktop-tower-monitor" => Some(icons::DESKTOP_TOWER_MONITOR),
        "desktop-tower" => Some(icons::DESKTOP_TOWER),
        "details" => Some(icons::DETAILS),
        #[allow(deprecated)]
        "dev-to" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'dev-to' is deprecated.").print(py);
            }
            Some(icons::DEV_TO)
        }
        "developer-board" => Some(icons::DEVELOPER_BOARD),
        #[allow(deprecated)]
        "deviantart" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'deviantart' is deprecated.").print(py);
            }
            Some(icons::DEVIANTART)
        }
        "devices" => Some(icons::DEVICES),
        "dharmachakra" => Some(icons::DHARMACHAKRA),
        "diabetes" => Some(icons::DIABETES),
        "dialpad" => Some(icons::DIALPAD),
        _ => None,
    }
}
