// This file was generated. DO NOT EDIT.
use crate::{Icon, icons};

#[cfg(feature = "pyo3")]
use pyo3::exceptions::PyDeprecationWarning;

#[cfg(feature = "pyo3")]
use pyo3::prelude::*;

pub(super) fn find_part_15(#[cfg(feature = "pyo3")] py: Python, slug: &str) -> Option<Icon> {
    match slug {
        "fingerprint" => Some(icons::FINGERPRINT),
        "fire-alert" => Some(icons::FIRE_ALERT),
        "fire-circle" => Some(icons::FIRE_CIRCLE),
        "fire-extinguisher" => Some(icons::FIRE_EXTINGUISHER),
        "fire-hydrant-alert" => Some(icons::FIRE_HYDRANT_ALERT),
        "fire-hydrant-off" => Some(icons::FIRE_HYDRANT_OFF),
        "fire-hydrant" => Some(icons::FIRE_HYDRANT),
        "fire-off" => Some(icons::FIRE_OFF),
        "fire-station" => Some(icons::FIRE_STATION),
        "fire-truck" => Some(icons::FIRE_TRUCK),
        "fire" => Some(icons::FIRE),
        #[allow(deprecated)]
        "firebase" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'firebase' is deprecated.").print(py);
            }
            Some(icons::FIREBASE)
        }
        #[allow(deprecated)]
        "firefox" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'firefox' is deprecated.").print(py);
            }
            Some(icons::FIREFOX)
        }
        "fireplace-off" => Some(icons::FIREPLACE_OFF),
        "fireplace" => Some(icons::FIREPLACE),
        "firewire" => Some(icons::FIREWIRE),
        "firework-off" => Some(icons::FIREWORK_OFF),
        "firework" => Some(icons::FIREWORK),
        "fish-off" => Some(icons::FISH_OFF),
        "fish" => Some(icons::FISH),
        "fishbowl-outline" => Some(icons::FISHBOWL_OUTLINE),
        "fishbowl" => Some(icons::FISHBOWL),
        "fit-to-page-outline" => Some(icons::FIT_TO_PAGE_OUTLINE),
        "fit-to-page" => Some(icons::FIT_TO_PAGE),
        "fit-to-screen-outline" => Some(icons::FIT_TO_SCREEN_OUTLINE),
        "fit-to-screen" => Some(icons::FIT_TO_SCREEN),
        "flag-checkered" => Some(icons::FLAG_CHECKERED),
        "flag-minus-outline" => Some(icons::FLAG_MINUS_OUTLINE),
        "flag-minus" => Some(icons::FLAG_MINUS),
        "flag-off-outline" => Some(icons::FLAG_OFF_OUTLINE),
        "flag-off" => Some(icons::FLAG_OFF),
        "flag-outline" => Some(icons::FLAG_OUTLINE),
        "flag-plus-outline" => Some(icons::FLAG_PLUS_OUTLINE),
        "flag-plus" => Some(icons::FLAG_PLUS),
        "flag-remove-outline" => Some(icons::FLAG_REMOVE_OUTLINE),
        "flag-remove" => Some(icons::FLAG_REMOVE),
        "flag-triangle" => Some(icons::FLAG_TRIANGLE),
        "flag-variant-minus-outline" => Some(icons::FLAG_VARIANT_MINUS_OUTLINE),
        "flag-variant-minus" => Some(icons::FLAG_VARIANT_MINUS),
        "flag-variant-off-outline" => Some(icons::FLAG_VARIANT_OFF_OUTLINE),
        "flag-variant-off" => Some(icons::FLAG_VARIANT_OFF),
        "flag-variant-outline" => Some(icons::FLAG_VARIANT_OUTLINE),
        "flag-variant-plus-outline" => Some(icons::FLAG_VARIANT_PLUS_OUTLINE),
        "flag-variant-plus" => Some(icons::FLAG_VARIANT_PLUS),
        "flag-variant-remove-outline" => Some(icons::FLAG_VARIANT_REMOVE_OUTLINE),
        "flag-variant-remove" => Some(icons::FLAG_VARIANT_REMOVE),
        "flag-variant" => Some(icons::FLAG_VARIANT),
        "flag" => Some(icons::FLAG),
        "flare" => Some(icons::FLARE),
        "flash-alert-outline" => Some(icons::FLASH_ALERT_OUTLINE),
        "flash-alert" => Some(icons::FLASH_ALERT),
        "flash-auto" => Some(icons::FLASH_AUTO),
        "flash-off-outline" => Some(icons::FLASH_OFF_OUTLINE),
        "flash-off" => Some(icons::FLASH_OFF),
        "flash-outline" => Some(icons::FLASH_OUTLINE),
        "flash-red-eye" => Some(icons::FLASH_RED_EYE),
        "flash-triangle-outline" => Some(icons::FLASH_TRIANGLE_OUTLINE),
        "flash-triangle" => Some(icons::FLASH_TRIANGLE),
        "flash" => Some(icons::FLASH),
        "flashlight-off" => Some(icons::FLASHLIGHT_OFF),
        "flashlight" => Some(icons::FLASHLIGHT),
        "flask-empty-minus-outline" => Some(icons::FLASK_EMPTY_MINUS_OUTLINE),
        "flask-empty-minus" => Some(icons::FLASK_EMPTY_MINUS),
        "flask-empty-off-outline" => Some(icons::FLASK_EMPTY_OFF_OUTLINE),
        "flask-empty-off" => Some(icons::FLASK_EMPTY_OFF),
        "flask-empty-outline" => Some(icons::FLASK_EMPTY_OUTLINE),
        "flask-empty-plus-outline" => Some(icons::FLASK_EMPTY_PLUS_OUTLINE),
        "flask-empty-plus" => Some(icons::FLASK_EMPTY_PLUS),
        "flask-empty-remove-outline" => Some(icons::FLASK_EMPTY_REMOVE_OUTLINE),
        "flask-empty-remove" => Some(icons::FLASK_EMPTY_REMOVE),
        "flask-empty" => Some(icons::FLASK_EMPTY),
        "flask-minus-outline" => Some(icons::FLASK_MINUS_OUTLINE),
        "flask-minus" => Some(icons::FLASK_MINUS),
        "flask-off-outline" => Some(icons::FLASK_OFF_OUTLINE),
        "flask-off" => Some(icons::FLASK_OFF),
        "flask-outline" => Some(icons::FLASK_OUTLINE),
        "flask-plus-outline" => Some(icons::FLASK_PLUS_OUTLINE),
        "flask-plus" => Some(icons::FLASK_PLUS),
        "flask-remove-outline" => Some(icons::FLASK_REMOVE_OUTLINE),
        "flask-remove" => Some(icons::FLASK_REMOVE),
        "flask-round-bottom-empty-outline" => Some(icons::FLASK_ROUND_BOTTOM_EMPTY_OUTLINE),
        "flask-round-bottom-empty" => Some(icons::FLASK_ROUND_BOTTOM_EMPTY),
        "flask-round-bottom-outline" => Some(icons::FLASK_ROUND_BOTTOM_OUTLINE),
        "flask-round-bottom" => Some(icons::FLASK_ROUND_BOTTOM),
        "flask" => Some(icons::FLASK),
        "fleur-de-lis" => Some(icons::FLEUR_DE_LIS),
        "flip-horizontal" => Some(icons::FLIP_HORIZONTAL),
        "flip-to-back" => Some(icons::FLIP_TO_BACK),
        "flip-to-front" => Some(icons::FLIP_TO_FRONT),
        "flip-vertical" => Some(icons::FLIP_VERTICAL),
        "floor-lamp-dual-outline" => Some(icons::FLOOR_LAMP_DUAL_OUTLINE),
        "floor-lamp-dual" => Some(icons::FLOOR_LAMP_DUAL),
        "floor-lamp-outline" => Some(icons::FLOOR_LAMP_OUTLINE),
        "floor-lamp-torchiere-outline" => Some(icons::FLOOR_LAMP_TORCHIERE_OUTLINE),
        "floor-lamp-torchiere-variant-outline" => Some(icons::FLOOR_LAMP_TORCHIERE_VARIANT_OUTLINE),
        "floor-lamp-torchiere-variant" => Some(icons::FLOOR_LAMP_TORCHIERE_VARIANT),
        "floor-lamp-torchiere" => Some(icons::FLOOR_LAMP_TORCHIERE),
        "floor-lamp" => Some(icons::FLOOR_LAMP),
        "floor-plan" => Some(icons::FLOOR_PLAN),
        "floppy-variant" => Some(icons::FLOPPY_VARIANT),
        "floppy" => Some(icons::FLOPPY),
        "flower-outline" => Some(icons::FLOWER_OUTLINE),
        "flower-pollen-outline" => Some(icons::FLOWER_POLLEN_OUTLINE),
        "flower-pollen" => Some(icons::FLOWER_POLLEN),
        "flower-poppy" => Some(icons::FLOWER_POPPY),
        "flower-tulip-outline" => Some(icons::FLOWER_TULIP_OUTLINE),
        "flower-tulip" => Some(icons::FLOWER_TULIP),
        "flower" => Some(icons::FLOWER),
        "focus-auto" => Some(icons::FOCUS_AUTO),
        "focus-field-horizontal" => Some(icons::FOCUS_FIELD_HORIZONTAL),
        "focus-field-vertical" => Some(icons::FOCUS_FIELD_VERTICAL),
        "focus-field" => Some(icons::FOCUS_FIELD),
        "folder-account-outline" => Some(icons::FOLDER_ACCOUNT_OUTLINE),
        "folder-account" => Some(icons::FOLDER_ACCOUNT),
        "folder-alert-outline" => Some(icons::FOLDER_ALERT_OUTLINE),
        "folder-alert" => Some(icons::FOLDER_ALERT),
        "folder-arrow-down-outline" => Some(icons::FOLDER_ARROW_DOWN_OUTLINE),
        "folder-arrow-down" => Some(icons::FOLDER_ARROW_DOWN),
        "folder-arrow-left-outline" => Some(icons::FOLDER_ARROW_LEFT_OUTLINE),
        "folder-arrow-left-right-outline" => Some(icons::FOLDER_ARROW_LEFT_RIGHT_OUTLINE),
        "folder-arrow-left-right" => Some(icons::FOLDER_ARROW_LEFT_RIGHT),
        "folder-arrow-left" => Some(icons::FOLDER_ARROW_LEFT),
        "folder-arrow-right-outline" => Some(icons::FOLDER_ARROW_RIGHT_OUTLINE),
        "folder-arrow-right" => Some(icons::FOLDER_ARROW_RIGHT),
        "folder-arrow-up-down-outline" => Some(icons::FOLDER_ARROW_UP_DOWN_OUTLINE),
        "folder-arrow-up-down" => Some(icons::FOLDER_ARROW_UP_DOWN),
        "folder-arrow-up-outline" => Some(icons::FOLDER_ARROW_UP_OUTLINE),
        "folder-arrow-up" => Some(icons::FOLDER_ARROW_UP),
        "folder-cancel-outline" => Some(icons::FOLDER_CANCEL_OUTLINE),
        "folder-cancel" => Some(icons::FOLDER_CANCEL),
        "folder-check-outline" => Some(icons::FOLDER_CHECK_OUTLINE),
        "folder-check" => Some(icons::FOLDER_CHECK),
        "folder-clock-outline" => Some(icons::FOLDER_CLOCK_OUTLINE),
        "folder-clock" => Some(icons::FOLDER_CLOCK),
        "folder-cog-outline" => Some(icons::FOLDER_COG_OUTLINE),
        "folder-cog" => Some(icons::FOLDER_COG),
        "folder-download-outline" => Some(icons::FOLDER_DOWNLOAD_OUTLINE),
        "folder-download" => Some(icons::FOLDER_DOWNLOAD),
        "folder-edit-outline" => Some(icons::FOLDER_EDIT_OUTLINE),
        "folder-edit" => Some(icons::FOLDER_EDIT),
        "folder-eye-outline" => Some(icons::FOLDER_EYE_OUTLINE),
        "folder-eye" => Some(icons::FOLDER_EYE),
        "folder-file-outline" => Some(icons::FOLDER_FILE_OUTLINE),
        "folder-file" => Some(icons::FOLDER_FILE),
        #[allow(deprecated)]
        "folder-google-drive" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'folder-google-drive' is deprecated.")
                    .print(py);
            }
            Some(icons::FOLDER_GOOGLE_DRIVE)
        }
        "folder-heart-outline" => Some(icons::FOLDER_HEART_OUTLINE),
        "folder-heart" => Some(icons::FOLDER_HEART),
        "folder-hidden" => Some(icons::FOLDER_HIDDEN),
        "folder-home-outline" => Some(icons::FOLDER_HOME_OUTLINE),
        "folder-home" => Some(icons::FOLDER_HOME),
        "folder-image" => Some(icons::FOLDER_IMAGE),
        "folder-information-outline" => Some(icons::FOLDER_INFORMATION_OUTLINE),
        "folder-information" => Some(icons::FOLDER_INFORMATION),
        "folder-key-network-outline" => Some(icons::FOLDER_KEY_NETWORK_OUTLINE),
        "folder-key-network" => Some(icons::FOLDER_KEY_NETWORK),
        "folder-key-outline" => Some(icons::FOLDER_KEY_OUTLINE),
        "folder-key" => Some(icons::FOLDER_KEY),
        "folder-lock-open-outline" => Some(icons::FOLDER_LOCK_OPEN_OUTLINE),
        "folder-lock-open" => Some(icons::FOLDER_LOCK_OPEN),
        "folder-lock-outline" => Some(icons::FOLDER_LOCK_OUTLINE),
        "folder-lock" => Some(icons::FOLDER_LOCK),
        "folder-marker-outline" => Some(icons::FOLDER_MARKER_OUTLINE),
        "folder-marker" => Some(icons::FOLDER_MARKER),
        "folder-minus-outline" => Some(icons::FOLDER_MINUS_OUTLINE),
        "folder-minus" => Some(icons::FOLDER_MINUS),
        "folder-move-outline" => Some(icons::FOLDER_MOVE_OUTLINE),
        "folder-move" => Some(icons::FOLDER_MOVE),
        "folder-multiple-image" => Some(icons::FOLDER_MULTIPLE_IMAGE),
        "folder-multiple-outline" => Some(icons::FOLDER_MULTIPLE_OUTLINE),
        "folder-multiple-plus-outline" => Some(icons::FOLDER_MULTIPLE_PLUS_OUTLINE),
        "folder-multiple-plus" => Some(icons::FOLDER_MULTIPLE_PLUS),
        "folder-multiple" => Some(icons::FOLDER_MULTIPLE),
        "folder-music-outline" => Some(icons::FOLDER_MUSIC_OUTLINE),
        "folder-music" => Some(icons::FOLDER_MUSIC),
        "folder-network-outline" => Some(icons::FOLDER_NETWORK_OUTLINE),
        "folder-network" => Some(icons::FOLDER_NETWORK),
        "folder-off-outline" => Some(icons::FOLDER_OFF_OUTLINE),
        "folder-off" => Some(icons::FOLDER_OFF),
        "folder-open-outline" => Some(icons::FOLDER_OPEN_OUTLINE),
        "folder-open" => Some(icons::FOLDER_OPEN),
        "folder-outline" => Some(icons::FOLDER_OUTLINE),
        "folder-play-outline" => Some(icons::FOLDER_PLAY_OUTLINE),
        "folder-play" => Some(icons::FOLDER_PLAY),
        "folder-plus-outline" => Some(icons::FOLDER_PLUS_OUTLINE),
        "folder-plus" => Some(icons::FOLDER_PLUS),
        "folder-pound-outline" => Some(icons::FOLDER_POUND_OUTLINE),
        "folder-pound" => Some(icons::FOLDER_POUND),
        "folder-question-outline" => Some(icons::FOLDER_QUESTION_OUTLINE),
        "folder-question" => Some(icons::FOLDER_QUESTION),
        "folder-refresh-outline" => Some(icons::FOLDER_REFRESH_OUTLINE),
        "folder-refresh" => Some(icons::FOLDER_REFRESH),
        "folder-remove-outline" => Some(icons::FOLDER_REMOVE_OUTLINE),
        "folder-remove" => Some(icons::FOLDER_REMOVE),
        "folder-search-outline" => Some(icons::FOLDER_SEARCH_OUTLINE),
        "folder-search" => Some(icons::FOLDER_SEARCH),
        "folder-settings-outline" => Some(icons::FOLDER_SETTINGS_OUTLINE),
        "folder-settings" => Some(icons::FOLDER_SETTINGS),
        "folder-star-multiple-outline" => Some(icons::FOLDER_STAR_MULTIPLE_OUTLINE),
        "folder-star-multiple" => Some(icons::FOLDER_STAR_MULTIPLE),
        "folder-star-outline" => Some(icons::FOLDER_STAR_OUTLINE),
        _ => None,
    }
}
