// This file was generated. DO NOT EDIT.
use crate::{Icon, icons};

#[cfg(feature = "pyo3")]
use pyo3::exceptions::PyDeprecationWarning;

#[cfg(feature = "pyo3")]
use pyo3::prelude::*;

pub(super) fn find_part_32(#[cfg(feature = "pyo3")] py: Python, slug: &str) -> Option<Icon> {
    match slug {
        "store-check-outline" => Some(icons::STORE_CHECK_OUTLINE),
        "store-check" => Some(icons::STORE_CHECK),
        "store-clock-outline" => Some(icons::STORE_CLOCK_OUTLINE),
        "store-clock" => Some(icons::STORE_CLOCK),
        "store-cog-outline" => Some(icons::STORE_COG_OUTLINE),
        "store-cog" => Some(icons::STORE_COG),
        "store-edit-outline" => Some(icons::STORE_EDIT_OUTLINE),
        "store-edit" => Some(icons::STORE_EDIT),
        "store-marker-outline" => Some(icons::STORE_MARKER_OUTLINE),
        "store-marker" => Some(icons::STORE_MARKER),
        "store-minus-outline" => Some(icons::STORE_MINUS_OUTLINE),
        "store-minus" => Some(icons::STORE_MINUS),
        "store-off-outline" => Some(icons::STORE_OFF_OUTLINE),
        "store-off" => Some(icons::STORE_OFF),
        "store-outline" => Some(icons::STORE_OUTLINE),
        "store-plus-outline" => Some(icons::STORE_PLUS_OUTLINE),
        "store-plus" => Some(icons::STORE_PLUS),
        "store-remove-outline" => Some(icons::STORE_REMOVE_OUTLINE),
        "store-remove" => Some(icons::STORE_REMOVE),
        "store-search-outline" => Some(icons::STORE_SEARCH_OUTLINE),
        "store-search" => Some(icons::STORE_SEARCH),
        "store-settings-outline" => Some(icons::STORE_SETTINGS_OUTLINE),
        "store-settings" => Some(icons::STORE_SETTINGS),
        "store" => Some(icons::STORE),
        "storefront-check-outline" => Some(icons::STOREFRONT_CHECK_OUTLINE),
        "storefront-check" => Some(icons::STOREFRONT_CHECK),
        "storefront-edit-outline" => Some(icons::STOREFRONT_EDIT_OUTLINE),
        "storefront-edit" => Some(icons::STOREFRONT_EDIT),
        "storefront-minus-outline" => Some(icons::STOREFRONT_MINUS_OUTLINE),
        "storefront-minus" => Some(icons::STOREFRONT_MINUS),
        "storefront-outline" => Some(icons::STOREFRONT_OUTLINE),
        "storefront-plus-outline" => Some(icons::STOREFRONT_PLUS_OUTLINE),
        "storefront-plus" => Some(icons::STOREFRONT_PLUS),
        "storefront-remove-outline" => Some(icons::STOREFRONT_REMOVE_OUTLINE),
        "storefront-remove" => Some(icons::STOREFRONT_REMOVE),
        "storefront" => Some(icons::STOREFRONT),
        "stove" => Some(icons::STOVE),
        "strategy" => Some(icons::STRATEGY),
        "stretch-to-page-outline" => Some(icons::STRETCH_TO_PAGE_OUTLINE),
        "stretch-to-page" => Some(icons::STRETCH_TO_PAGE),
        "string-lights-off" => Some(icons::STRING_LIGHTS_OFF),
        "string-lights" => Some(icons::STRING_LIGHTS),
        "subdirectory-arrow-left" => Some(icons::SUBDIRECTORY_ARROW_LEFT),
        "subdirectory-arrow-right" => Some(icons::SUBDIRECTORY_ARROW_RIGHT),
        "submarine" => Some(icons::SUBMARINE),
        "subtitles-outline" => Some(icons::SUBTITLES_OUTLINE),
        "subtitles" => Some(icons::SUBTITLES),
        "subway-alert-variant" => Some(icons::SUBWAY_ALERT_VARIANT),
        "subway-variant" => Some(icons::SUBWAY_VARIANT),
        "subway" => Some(icons::SUBWAY),
        "summit" => Some(icons::SUMMIT),
        "sun-angle-outline" => Some(icons::SUN_ANGLE_OUTLINE),
        "sun-angle" => Some(icons::SUN_ANGLE),
        "sun-clock-outline" => Some(icons::SUN_CLOCK_OUTLINE),
        "sun-clock" => Some(icons::SUN_CLOCK),
        "sun-compass" => Some(icons::SUN_COMPASS),
        "sun-snowflake-variant" => Some(icons::SUN_SNOWFLAKE_VARIANT),
        "sun-snowflake" => Some(icons::SUN_SNOWFLAKE),
        "sun-thermometer-outline" => Some(icons::SUN_THERMOMETER_OUTLINE),
        "sun-thermometer" => Some(icons::SUN_THERMOMETER),
        "sun-wireless-outline" => Some(icons::SUN_WIRELESS_OUTLINE),
        "sun-wireless" => Some(icons::SUN_WIRELESS),
        "sunglasses" => Some(icons::SUNGLASSES),
        "surfing" => Some(icons::SURFING),
        "surround-sound-2-0" => Some(icons::SURROUND_SOUND_2_0),
        "surround-sound-2-1" => Some(icons::SURROUND_SOUND_2_1),
        "surround-sound-3-1" => Some(icons::SURROUND_SOUND_3_1),
        "surround-sound-5-1-2" => Some(icons::SURROUND_SOUND_5_1_2),
        "surround-sound-5-1" => Some(icons::SURROUND_SOUND_5_1),
        "surround-sound-7-1" => Some(icons::SURROUND_SOUND_7_1),
        "surround-sound" => Some(icons::SURROUND_SOUND),
        #[allow(deprecated)]
        "svg" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'svg' is deprecated.").print(py);
            }
            Some(icons::SVG)
        }
        "swap-horizontal-bold" => Some(icons::SWAP_HORIZONTAL_BOLD),
        "swap-horizontal-circle-outline" => Some(icons::SWAP_HORIZONTAL_CIRCLE_OUTLINE),
        "swap-horizontal-circle" => Some(icons::SWAP_HORIZONTAL_CIRCLE),
        "swap-horizontal-hidden" => Some(icons::SWAP_HORIZONTAL_HIDDEN),
        "swap-horizontal-variant" => Some(icons::SWAP_HORIZONTAL_VARIANT),
        "swap-horizontal" => Some(icons::SWAP_HORIZONTAL),
        "swap-vertical-bold" => Some(icons::SWAP_VERTICAL_BOLD),
        "swap-vertical-circle-outline" => Some(icons::SWAP_VERTICAL_CIRCLE_OUTLINE),
        "swap-vertical-circle" => Some(icons::SWAP_VERTICAL_CIRCLE),
        "swap-vertical-variant" => Some(icons::SWAP_VERTICAL_VARIANT),
        "swap-vertical" => Some(icons::SWAP_VERTICAL),
        "swim" => Some(icons::SWIM),
        "switch" => Some(icons::SWITCH),
        "sword-cross" => Some(icons::SWORD_CROSS),
        "sword" => Some(icons::SWORD),
        "syllabary-hangul" => Some(icons::SYLLABARY_HANGUL),
        "syllabary-hiragana" => Some(icons::SYLLABARY_HIRAGANA),
        "syllabary-katakana-halfwidth" => Some(icons::SYLLABARY_KATAKANA_HALFWIDTH),
        "syllabary-katakana" => Some(icons::SYLLABARY_KATAKANA),
        "symbol" => Some(icons::SYMBOL),
        #[allow(deprecated)]
        "symfony" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'symfony' is deprecated.").print(py);
            }
            Some(icons::SYMFONY)
        }
        "synagogue-outline" => Some(icons::SYNAGOGUE_OUTLINE),
        "synagogue" => Some(icons::SYNAGOGUE),
        "sync-alert" => Some(icons::SYNC_ALERT),
        "sync-circle" => Some(icons::SYNC_CIRCLE),
        "sync-off" => Some(icons::SYNC_OFF),
        "sync" => Some(icons::SYNC),
        "tab-minus" => Some(icons::TAB_MINUS),
        "tab-plus" => Some(icons::TAB_PLUS),
        "tab-remove" => Some(icons::TAB_REMOVE),
        "tab-search" => Some(icons::TAB_SEARCH),
        "tab-unselected" => Some(icons::TAB_UNSELECTED),
        "tab" => Some(icons::TAB),
        "table-account" => Some(icons::TABLE_ACCOUNT),
        "table-alert" => Some(icons::TABLE_ALERT),
        "table-arrow-down" => Some(icons::TABLE_ARROW_DOWN),
        "table-arrow-left" => Some(icons::TABLE_ARROW_LEFT),
        "table-arrow-right" => Some(icons::TABLE_ARROW_RIGHT),
        "table-arrow-up" => Some(icons::TABLE_ARROW_UP),
        "table-border" => Some(icons::TABLE_BORDER),
        "table-cancel" => Some(icons::TABLE_CANCEL),
        "table-chair" => Some(icons::TABLE_CHAIR),
        "table-check" => Some(icons::TABLE_CHECK),
        "table-clock" => Some(icons::TABLE_CLOCK),
        "table-cog" => Some(icons::TABLE_COG),
        "table-column-plus-after" => Some(icons::TABLE_COLUMN_PLUS_AFTER),
        "table-column-plus-before" => Some(icons::TABLE_COLUMN_PLUS_BEFORE),
        "table-column-remove" => Some(icons::TABLE_COLUMN_REMOVE),
        "table-column-width" => Some(icons::TABLE_COLUMN_WIDTH),
        "table-column" => Some(icons::TABLE_COLUMN),
        "table-edit" => Some(icons::TABLE_EDIT),
        "table-eye-off" => Some(icons::TABLE_EYE_OFF),
        "table-eye" => Some(icons::TABLE_EYE),
        "table-filter" => Some(icons::TABLE_FILTER),
        "table-furniture" => Some(icons::TABLE_FURNITURE),
        "table-headers-eye-off" => Some(icons::TABLE_HEADERS_EYE_OFF),
        "table-headers-eye" => Some(icons::TABLE_HEADERS_EYE),
        "table-heart" => Some(icons::TABLE_HEART),
        "table-key" => Some(icons::TABLE_KEY),
        "table-large-plus" => Some(icons::TABLE_LARGE_PLUS),
        "table-large-remove" => Some(icons::TABLE_LARGE_REMOVE),
        "table-large" => Some(icons::TABLE_LARGE),
        "table-lock" => Some(icons::TABLE_LOCK),
        "table-merge-cells" => Some(icons::TABLE_MERGE_CELLS),
        "table-minus" => Some(icons::TABLE_MINUS),
        "table-multiple" => Some(icons::TABLE_MULTIPLE),
        "table-network" => Some(icons::TABLE_NETWORK),
        "table-of-contents" => Some(icons::TABLE_OF_CONTENTS),
        "table-off" => Some(icons::TABLE_OFF),
        "table-picnic" => Some(icons::TABLE_PICNIC),
        "table-pivot" => Some(icons::TABLE_PIVOT),
        "table-plus" => Some(icons::TABLE_PLUS),
        "table-question" => Some(icons::TABLE_QUESTION),
        "table-refresh" => Some(icons::TABLE_REFRESH),
        "table-remove" => Some(icons::TABLE_REMOVE),
        "table-row-height" => Some(icons::TABLE_ROW_HEIGHT),
        "table-row-plus-after" => Some(icons::TABLE_ROW_PLUS_AFTER),
        "table-row-plus-before" => Some(icons::TABLE_ROW_PLUS_BEFORE),
        "table-row-remove" => Some(icons::TABLE_ROW_REMOVE),
        "table-row" => Some(icons::TABLE_ROW),
        "table-search" => Some(icons::TABLE_SEARCH),
        "table-settings" => Some(icons::TABLE_SETTINGS),
        "table-split-cell" => Some(icons::TABLE_SPLIT_CELL),
        "table-star" => Some(icons::TABLE_STAR),
        "table-sync" => Some(icons::TABLE_SYNC),
        "table-tennis" => Some(icons::TABLE_TENNIS),
        "table" => Some(icons::TABLE),
        "tablet-cellphone" => Some(icons::TABLET_CELLPHONE),
        "tablet-dashboard" => Some(icons::TABLET_DASHBOARD),
        "tablet" => Some(icons::TABLET),
        "taco" => Some(icons::TACO),
        "tag-arrow-down-outline" => Some(icons::TAG_ARROW_DOWN_OUTLINE),
        "tag-arrow-down" => Some(icons::TAG_ARROW_DOWN),
        "tag-arrow-left-outline" => Some(icons::TAG_ARROW_LEFT_OUTLINE),
        "tag-arrow-left" => Some(icons::TAG_ARROW_LEFT),
        "tag-arrow-right-outline" => Some(icons::TAG_ARROW_RIGHT_OUTLINE),
        "tag-arrow-right" => Some(icons::TAG_ARROW_RIGHT),
        "tag-arrow-up-outline" => Some(icons::TAG_ARROW_UP_OUTLINE),
        "tag-arrow-up" => Some(icons::TAG_ARROW_UP),
        "tag-check-outline" => Some(icons::TAG_CHECK_OUTLINE),
        "tag-check" => Some(icons::TAG_CHECK),
        "tag-edit-outline" => Some(icons::TAG_EDIT_OUTLINE),
        "tag-edit" => Some(icons::TAG_EDIT),
        "tag-faces" => Some(icons::TAG_FACES),
        "tag-heart-outline" => Some(icons::TAG_HEART_OUTLINE),
        "tag-heart" => Some(icons::TAG_HEART),
        "tag-hidden" => Some(icons::TAG_HIDDEN),
        "tag-minus-outline" => Some(icons::TAG_MINUS_OUTLINE),
        "tag-minus" => Some(icons::TAG_MINUS),
        "tag-multiple-outline" => Some(icons::TAG_MULTIPLE_OUTLINE),
        "tag-multiple" => Some(icons::TAG_MULTIPLE),
        "tag-off-outline" => Some(icons::TAG_OFF_OUTLINE),
        "tag-off" => Some(icons::TAG_OFF),
        "tag-outline" => Some(icons::TAG_OUTLINE),
        "tag-plus-outline" => Some(icons::TAG_PLUS_OUTLINE),
        "tag-plus" => Some(icons::TAG_PLUS),
        "tag-remove-outline" => Some(icons::TAG_REMOVE_OUTLINE),
        "tag-remove" => Some(icons::TAG_REMOVE),
        "tag-search-outline" => Some(icons::TAG_SEARCH_OUTLINE),
        "tag-search" => Some(icons::TAG_SEARCH),
        "tag-text-outline" => Some(icons::TAG_TEXT_OUTLINE),
        "tag-text" => Some(icons::TAG_TEXT),
        "tag" => Some(icons::TAG),
        #[allow(deprecated)]
        "tailwind" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'tailwind' is deprecated.").print(py);
            }
            Some(icons::TAILWIND)
        }
        "tally-mark-1" => Some(icons::TALLY_MARK_1),
        "tally-mark-2" => Some(icons::TALLY_MARK_2),
        "tally-mark-3" => Some(icons::TALLY_MARK_3),
        "tally-mark-4" => Some(icons::TALLY_MARK_4),
        _ => None,
    }
}
