// This file was generated. DO NOT EDIT.
use crate::{Icon, icons};

#[cfg(feature = "pyo3")]
use pyo3::exceptions::PyDeprecationWarning;

#[cfg(feature = "pyo3")]
use pyo3::prelude::*;

pub(super) fn find_part_3(#[cfg(feature = "pyo3")] py: Python, slug: &str) -> Option<Icon> {
    match slug {
        "arrow-u-down-left" => Some(icons::ARROW_U_DOWN_LEFT),
        "arrow-u-down-right-bold" => Some(icons::ARROW_U_DOWN_RIGHT_BOLD),
        "arrow-u-down-right" => Some(icons::ARROW_U_DOWN_RIGHT),
        "arrow-u-left-bottom-bold" => Some(icons::ARROW_U_LEFT_BOTTOM_BOLD),
        "arrow-u-left-bottom" => Some(icons::ARROW_U_LEFT_BOTTOM),
        "arrow-u-left-top-bold" => Some(icons::ARROW_U_LEFT_TOP_BOLD),
        "arrow-u-left-top" => Some(icons::ARROW_U_LEFT_TOP),
        "arrow-u-right-bottom-bold" => Some(icons::ARROW_U_RIGHT_BOTTOM_BOLD),
        "arrow-u-right-bottom" => Some(icons::ARROW_U_RIGHT_BOTTOM),
        "arrow-u-right-top-bold" => Some(icons::ARROW_U_RIGHT_TOP_BOLD),
        "arrow-u-right-top" => Some(icons::ARROW_U_RIGHT_TOP),
        "arrow-u-up-left-bold" => Some(icons::ARROW_U_UP_LEFT_BOLD),
        "arrow-u-up-left" => Some(icons::ARROW_U_UP_LEFT),
        "arrow-u-up-right-bold" => Some(icons::ARROW_U_UP_RIGHT_BOLD),
        "arrow-u-up-right" => Some(icons::ARROW_U_UP_RIGHT),
        "arrow-up-bold-box-outline" => Some(icons::ARROW_UP_BOLD_BOX_OUTLINE),
        "arrow-up-bold-box" => Some(icons::ARROW_UP_BOLD_BOX),
        "arrow-up-bold-circle-outline" => Some(icons::ARROW_UP_BOLD_CIRCLE_OUTLINE),
        "arrow-up-bold-circle" => Some(icons::ARROW_UP_BOLD_CIRCLE),
        "arrow-up-bold-hexagon-outline" => Some(icons::ARROW_UP_BOLD_HEXAGON_OUTLINE),
        "arrow-up-bold-outline" => Some(icons::ARROW_UP_BOLD_OUTLINE),
        "arrow-up-bold" => Some(icons::ARROW_UP_BOLD),
        "arrow-up-box" => Some(icons::ARROW_UP_BOX),
        "arrow-up-circle-outline" => Some(icons::ARROW_UP_CIRCLE_OUTLINE),
        "arrow-up-circle" => Some(icons::ARROW_UP_CIRCLE),
        "arrow-up-down-bold-outline" => Some(icons::ARROW_UP_DOWN_BOLD_OUTLINE),
        "arrow-up-down-bold" => Some(icons::ARROW_UP_DOWN_BOLD),
        "arrow-up-down" => Some(icons::ARROW_UP_DOWN),
        "arrow-up-drop-circle-outline" => Some(icons::ARROW_UP_DROP_CIRCLE_OUTLINE),
        "arrow-up-drop-circle" => Some(icons::ARROW_UP_DROP_CIRCLE),
        "arrow-up-left-bold" => Some(icons::ARROW_UP_LEFT_BOLD),
        "arrow-up-left" => Some(icons::ARROW_UP_LEFT),
        "arrow-up-right-bold" => Some(icons::ARROW_UP_RIGHT_BOLD),
        "arrow-up-right" => Some(icons::ARROW_UP_RIGHT),
        "arrow-up-thick" => Some(icons::ARROW_UP_THICK),
        "arrow-up-thin-circle-outline" => Some(icons::ARROW_UP_THIN_CIRCLE_OUTLINE),
        "arrow-up-thin" => Some(icons::ARROW_UP_THIN),
        "arrow-up" => Some(icons::ARROW_UP),
        "arrow-vertical-lock" => Some(icons::ARROW_VERTICAL_LOCK),
        "artboard" => Some(icons::ARTBOARD),
        #[allow(deprecated)]
        "artstation" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'artstation' is deprecated.").print(py);
            }
            Some(icons::ARTSTATION)
        }
        "aspect-ratio" => Some(icons::ASPECT_RATIO),
        "assistant" => Some(icons::ASSISTANT),
        "asterisk-circle-outline" => Some(icons::ASTERISK_CIRCLE_OUTLINE),
        "asterisk" => Some(icons::ASTERISK),
        "at" => Some(icons::AT),
        #[allow(deprecated)]
        "atlassian" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'atlassian' is deprecated.").print(py);
            }
            Some(icons::ATLASSIAN)
        }
        "atm" => Some(icons::ATM),
        "atom-variant" => Some(icons::ATOM_VARIANT),
        "atom" => Some(icons::ATOM),
        "attachment-check" => Some(icons::ATTACHMENT_CHECK),
        "attachment-lock" => Some(icons::ATTACHMENT_LOCK),
        "attachment-minus" => Some(icons::ATTACHMENT_MINUS),
        "attachment-off" => Some(icons::ATTACHMENT_OFF),
        "attachment-plus" => Some(icons::ATTACHMENT_PLUS),
        "attachment-remove" => Some(icons::ATTACHMENT_REMOVE),
        "attachment" => Some(icons::ATTACHMENT),
        "atv" => Some(icons::ATV),
        "audio-input-rca" => Some(icons::AUDIO_INPUT_RCA),
        "audio-input-stereo-minijack" => Some(icons::AUDIO_INPUT_STEREO_MINIJACK),
        "audio-input-xlr" => Some(icons::AUDIO_INPUT_XLR),
        "audio-video-off" => Some(icons::AUDIO_VIDEO_OFF),
        "audio-video" => Some(icons::AUDIO_VIDEO),
        "augmented-reality" => Some(icons::AUGMENTED_REALITY),
        "aurora" => Some(icons::AURORA),
        "auto-download" => Some(icons::AUTO_DOWNLOAD),
        "auto-fix" => Some(icons::AUTO_FIX),
        "auto-mode" => Some(icons::AUTO_MODE),
        "auto-upload" => Some(icons::AUTO_UPLOAD),
        "autorenew-off" => Some(icons::AUTORENEW_OFF),
        "autorenew" => Some(icons::AUTORENEW),
        "av-timer" => Some(icons::AV_TIMER),
        "awning-outline" => Some(icons::AWNING_OUTLINE),
        "awning" => Some(icons::AWNING),
        #[allow(deprecated)]
        "aws" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'aws' is deprecated.").print(py);
            }
            Some(icons::AWS)
        }
        "axe-battle" => Some(icons::AXE_BATTLE),
        "axe" => Some(icons::AXE),
        "axis-arrow-info" => Some(icons::AXIS_ARROW_INFO),
        "axis-arrow-lock" => Some(icons::AXIS_ARROW_LOCK),
        "axis-arrow" => Some(icons::AXIS_ARROW),
        "axis-lock" => Some(icons::AXIS_LOCK),
        "axis-x-arrow-lock" => Some(icons::AXIS_X_ARROW_LOCK),
        "axis-x-arrow" => Some(icons::AXIS_X_ARROW),
        "axis-x-rotate-clockwise" => Some(icons::AXIS_X_ROTATE_CLOCKWISE),
        "axis-x-rotate-counterclockwise" => Some(icons::AXIS_X_ROTATE_COUNTERCLOCKWISE),
        "axis-x-y-arrow-lock" => Some(icons::AXIS_X_Y_ARROW_LOCK),
        "axis-y-arrow-lock" => Some(icons::AXIS_Y_ARROW_LOCK),
        "axis-y-arrow" => Some(icons::AXIS_Y_ARROW),
        "axis-y-rotate-clockwise" => Some(icons::AXIS_Y_ROTATE_CLOCKWISE),
        "axis-y-rotate-counterclockwise" => Some(icons::AXIS_Y_ROTATE_COUNTERCLOCKWISE),
        "axis-z-arrow-lock" => Some(icons::AXIS_Z_ARROW_LOCK),
        "axis-z-arrow" => Some(icons::AXIS_Z_ARROW),
        "axis-z-rotate-clockwise" => Some(icons::AXIS_Z_ROTATE_CLOCKWISE),
        "axis-z-rotate-counterclockwise" => Some(icons::AXIS_Z_ROTATE_COUNTERCLOCKWISE),
        "axis" => Some(icons::AXIS),
        #[allow(deprecated)]
        "babel" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'babel' is deprecated.").print(py);
            }
            Some(icons::BABEL)
        }
        "baby-bottle-outline" => Some(icons::BABY_BOTTLE_OUTLINE),
        "baby-bottle" => Some(icons::BABY_BOTTLE),
        "baby-buggy-off" => Some(icons::BABY_BUGGY_OFF),
        "baby-buggy" => Some(icons::BABY_BUGGY),
        "baby-carriage-off" => Some(icons::BABY_CARRIAGE_OFF),
        "baby-carriage" => Some(icons::BABY_CARRIAGE),
        "baby-face-outline" => Some(icons::BABY_FACE_OUTLINE),
        "baby-face" => Some(icons::BABY_FACE),
        "baby" => Some(icons::BABY),
        "backburger" => Some(icons::BACKBURGER),
        "backspace-outline" => Some(icons::BACKSPACE_OUTLINE),
        "backspace-reverse-outline" => Some(icons::BACKSPACE_REVERSE_OUTLINE),
        "backspace-reverse" => Some(icons::BACKSPACE_REVERSE),
        "backspace" => Some(icons::BACKSPACE),
        "backup-restore" => Some(icons::BACKUP_RESTORE),
        "bacteria-outline" => Some(icons::BACTERIA_OUTLINE),
        "bacteria" => Some(icons::BACTERIA),
        "badge-account-alert-outline" => Some(icons::BADGE_ACCOUNT_ALERT_OUTLINE),
        "badge-account-alert" => Some(icons::BADGE_ACCOUNT_ALERT),
        "badge-account-horizontal-outline" => Some(icons::BADGE_ACCOUNT_HORIZONTAL_OUTLINE),
        "badge-account-horizontal" => Some(icons::BADGE_ACCOUNT_HORIZONTAL),
        "badge-account-outline" => Some(icons::BADGE_ACCOUNT_OUTLINE),
        "badge-account" => Some(icons::BADGE_ACCOUNT),
        "badminton" => Some(icons::BADMINTON),
        "bag-carry-on-check" => Some(icons::BAG_CARRY_ON_CHECK),
        "bag-carry-on-off" => Some(icons::BAG_CARRY_ON_OFF),
        "bag-carry-on" => Some(icons::BAG_CARRY_ON),
        "bag-checked" => Some(icons::BAG_CHECKED),
        "bag-personal-off-outline" => Some(icons::BAG_PERSONAL_OFF_OUTLINE),
        "bag-personal-off" => Some(icons::BAG_PERSONAL_OFF),
        "bag-personal-outline" => Some(icons::BAG_PERSONAL_OUTLINE),
        "bag-personal-plus-outline" => Some(icons::BAG_PERSONAL_PLUS_OUTLINE),
        "bag-personal-plus" => Some(icons::BAG_PERSONAL_PLUS),
        "bag-personal-tag-outline" => Some(icons::BAG_PERSONAL_TAG_OUTLINE),
        "bag-personal-tag" => Some(icons::BAG_PERSONAL_TAG),
        "bag-personal" => Some(icons::BAG_PERSONAL),
        "bag-suitcase-off-outline" => Some(icons::BAG_SUITCASE_OFF_OUTLINE),
        "bag-suitcase-off" => Some(icons::BAG_SUITCASE_OFF),
        "bag-suitcase-outline" => Some(icons::BAG_SUITCASE_OUTLINE),
        "bag-suitcase" => Some(icons::BAG_SUITCASE),
        "baguette" => Some(icons::BAGUETTE),
        "balcony" => Some(icons::BALCONY),
        "balloon" => Some(icons::BALLOON),
        "ballot-outline" => Some(icons::BALLOT_OUTLINE),
        "ballot-recount-outline" => Some(icons::BALLOT_RECOUNT_OUTLINE),
        "ballot-recount" => Some(icons::BALLOT_RECOUNT),
        "ballot" => Some(icons::BALLOT),
        "bandage" => Some(icons::BANDAGE),
        "bank-check" => Some(icons::BANK_CHECK),
        "bank-circle-outline" => Some(icons::BANK_CIRCLE_OUTLINE),
        "bank-circle" => Some(icons::BANK_CIRCLE),
        "bank-minus" => Some(icons::BANK_MINUS),
        "bank-off-outline" => Some(icons::BANK_OFF_OUTLINE),
        "bank-off" => Some(icons::BANK_OFF),
        "bank-outline" => Some(icons::BANK_OUTLINE),
        "bank-plus" => Some(icons::BANK_PLUS),
        "bank-remove" => Some(icons::BANK_REMOVE),
        "bank-transfer-in" => Some(icons::BANK_TRANSFER_IN),
        "bank-transfer-out" => Some(icons::BANK_TRANSFER_OUT),
        "bank-transfer" => Some(icons::BANK_TRANSFER),
        "bank" => Some(icons::BANK),
        "barcode-off" => Some(icons::BARCODE_OFF),
        "barcode-scan" => Some(icons::BARCODE_SCAN),
        "barcode" => Some(icons::BARCODE),
        "barley-off" => Some(icons::BARLEY_OFF),
        "barley" => Some(icons::BARLEY),
        "barn" => Some(icons::BARN),
        "barrel-outline" => Some(icons::BARREL_OUTLINE),
        "barrel" => Some(icons::BARREL),
        "baseball-bat" => Some(icons::BASEBALL_BAT),
        "baseball-diamond-outline" => Some(icons::BASEBALL_DIAMOND_OUTLINE),
        "baseball-diamond" => Some(icons::BASEBALL_DIAMOND),
        "baseball-outline" => Some(icons::BASEBALL_OUTLINE),
        "baseball" => Some(icons::BASEBALL),
        "bash" => Some(icons::BASH),
        "basket-check-outline" => Some(icons::BASKET_CHECK_OUTLINE),
        "basket-check" => Some(icons::BASKET_CHECK),
        "basket-fill" => Some(icons::BASKET_FILL),
        "basket-minus-outline" => Some(icons::BASKET_MINUS_OUTLINE),
        "basket-minus" => Some(icons::BASKET_MINUS),
        "basket-off-outline" => Some(icons::BASKET_OFF_OUTLINE),
        "basket-off" => Some(icons::BASKET_OFF),
        "basket-outline" => Some(icons::BASKET_OUTLINE),
        "basket-plus-outline" => Some(icons::BASKET_PLUS_OUTLINE),
        "basket-plus" => Some(icons::BASKET_PLUS),
        "basket-remove-outline" => Some(icons::BASKET_REMOVE_OUTLINE),
        "basket-remove" => Some(icons::BASKET_REMOVE),
        "basket-unfill" => Some(icons::BASKET_UNFILL),
        "basket" => Some(icons::BASKET),
        "basketball-hoop-outline" => Some(icons::BASKETBALL_HOOP_OUTLINE),
        "basketball-hoop" => Some(icons::BASKETBALL_HOOP),
        "basketball" => Some(icons::BASKETBALL),
        "bat" => Some(icons::BAT),
        "bathtub-outline" => Some(icons::BATHTUB_OUTLINE),
        "bathtub" => Some(icons::BATHTUB),
        "battery-10-bluetooth" => Some(icons::BATTERY_10_BLUETOOTH),
        "battery-10" => Some(icons::BATTERY_10),
        "battery-20-bluetooth" => Some(icons::BATTERY_20_BLUETOOTH),
        "battery-20" => Some(icons::BATTERY_20),
        "battery-30-bluetooth" => Some(icons::BATTERY_30_BLUETOOTH),
        "battery-30" => Some(icons::BATTERY_30),
        "battery-40-bluetooth" => Some(icons::BATTERY_40_BLUETOOTH),
        "battery-40" => Some(icons::BATTERY_40),
        "battery-50-bluetooth" => Some(icons::BATTERY_50_BLUETOOTH),
        _ => None,
    }
}
