// This file was generated. DO NOT EDIT.
use crate::{Icon, icons};

#[cfg(feature = "pyo3")]
use pyo3::exceptions::PyDeprecationWarning;

#[cfg(feature = "pyo3")]
use pyo3::prelude::*;

pub(super) fn find_part_27(#[cfg(feature = "pyo3")] py: Python, slug: &str) -> Option<Icon> {
    match slug {
        "power-socket-it" => Some(icons::POWER_SOCKET_IT),
        "power-socket-jp" => Some(icons::POWER_SOCKET_JP),
        "power-socket-uk" => Some(icons::POWER_SOCKET_UK),
        "power-socket-us" => Some(icons::POWER_SOCKET_US),
        "power-socket" => Some(icons::POWER_SOCKET),
        "power-standby" => Some(icons::POWER_STANDBY),
        "power" => Some(icons::POWER),
        "powershell" => Some(icons::POWERSHELL),
        "prescription" => Some(icons::PRESCRIPTION),
        "presentation-play" => Some(icons::PRESENTATION_PLAY),
        "presentation" => Some(icons::PRESENTATION),
        "pretzel" => Some(icons::PRETZEL),
        "printer-3d-nozzle-alert-outline" => Some(icons::PRINTER_3D_NOZZLE_ALERT_OUTLINE),
        "printer-3d-nozzle-alert" => Some(icons::PRINTER_3D_NOZZLE_ALERT),
        "printer-3d-nozzle-heat-outline" => Some(icons::PRINTER_3D_NOZZLE_HEAT_OUTLINE),
        "printer-3d-nozzle-heat" => Some(icons::PRINTER_3D_NOZZLE_HEAT),
        "printer-3d-nozzle-off-outline" => Some(icons::PRINTER_3D_NOZZLE_OFF_OUTLINE),
        "printer-3d-nozzle-off" => Some(icons::PRINTER_3D_NOZZLE_OFF),
        "printer-3d-nozzle-outline" => Some(icons::PRINTER_3D_NOZZLE_OUTLINE),
        "printer-3d-nozzle" => Some(icons::PRINTER_3D_NOZZLE),
        "printer-3d-off" => Some(icons::PRINTER_3D_OFF),
        "printer-3d" => Some(icons::PRINTER_3D),
        "printer-alert" => Some(icons::PRINTER_ALERT),
        "printer-check" => Some(icons::PRINTER_CHECK),
        "printer-eye" => Some(icons::PRINTER_EYE),
        "printer-off-outline" => Some(icons::PRINTER_OFF_OUTLINE),
        "printer-off" => Some(icons::PRINTER_OFF),
        "printer-outline" => Some(icons::PRINTER_OUTLINE),
        "printer-pos-alert-outline" => Some(icons::PRINTER_POS_ALERT_OUTLINE),
        "printer-pos-alert" => Some(icons::PRINTER_POS_ALERT),
        "printer-pos-cancel-outline" => Some(icons::PRINTER_POS_CANCEL_OUTLINE),
        "printer-pos-cancel" => Some(icons::PRINTER_POS_CANCEL),
        "printer-pos-check-outline" => Some(icons::PRINTER_POS_CHECK_OUTLINE),
        "printer-pos-check" => Some(icons::PRINTER_POS_CHECK),
        "printer-pos-cog-outline" => Some(icons::PRINTER_POS_COG_OUTLINE),
        "printer-pos-cog" => Some(icons::PRINTER_POS_COG),
        "printer-pos-edit-outline" => Some(icons::PRINTER_POS_EDIT_OUTLINE),
        "printer-pos-edit" => Some(icons::PRINTER_POS_EDIT),
        "printer-pos-minus-outline" => Some(icons::PRINTER_POS_MINUS_OUTLINE),
        "printer-pos-minus" => Some(icons::PRINTER_POS_MINUS),
        "printer-pos-network-outline" => Some(icons::PRINTER_POS_NETWORK_OUTLINE),
        "printer-pos-network" => Some(icons::PRINTER_POS_NETWORK),
        "printer-pos-off-outline" => Some(icons::PRINTER_POS_OFF_OUTLINE),
        "printer-pos-off" => Some(icons::PRINTER_POS_OFF),
        "printer-pos-outline" => Some(icons::PRINTER_POS_OUTLINE),
        "printer-pos-pause-outline" => Some(icons::PRINTER_POS_PAUSE_OUTLINE),
        "printer-pos-pause" => Some(icons::PRINTER_POS_PAUSE),
        "printer-pos-play-outline" => Some(icons::PRINTER_POS_PLAY_OUTLINE),
        "printer-pos-play" => Some(icons::PRINTER_POS_PLAY),
        "printer-pos-plus-outline" => Some(icons::PRINTER_POS_PLUS_OUTLINE),
        "printer-pos-plus" => Some(icons::PRINTER_POS_PLUS),
        "printer-pos-refresh-outline" => Some(icons::PRINTER_POS_REFRESH_OUTLINE),
        "printer-pos-refresh" => Some(icons::PRINTER_POS_REFRESH),
        "printer-pos-remove-outline" => Some(icons::PRINTER_POS_REMOVE_OUTLINE),
        "printer-pos-remove" => Some(icons::PRINTER_POS_REMOVE),
        "printer-pos-star-outline" => Some(icons::PRINTER_POS_STAR_OUTLINE),
        "printer-pos-star" => Some(icons::PRINTER_POS_STAR),
        "printer-pos-stop-outline" => Some(icons::PRINTER_POS_STOP_OUTLINE),
        "printer-pos-stop" => Some(icons::PRINTER_POS_STOP),
        "printer-pos-sync-outline" => Some(icons::PRINTER_POS_SYNC_OUTLINE),
        "printer-pos-sync" => Some(icons::PRINTER_POS_SYNC),
        "printer-pos-wrench-outline" => Some(icons::PRINTER_POS_WRENCH_OUTLINE),
        "printer-pos-wrench" => Some(icons::PRINTER_POS_WRENCH),
        "printer-pos" => Some(icons::PRINTER_POS),
        "printer-search" => Some(icons::PRINTER_SEARCH),
        "printer-settings" => Some(icons::PRINTER_SETTINGS),
        "printer-wireless" => Some(icons::PRINTER_WIRELESS),
        "printer" => Some(icons::PRINTER),
        "priority-high" => Some(icons::PRIORITY_HIGH),
        "priority-low" => Some(icons::PRIORITY_LOW),
        "professional-hexagon" => Some(icons::PROFESSIONAL_HEXAGON),
        "progress-alert" => Some(icons::PROGRESS_ALERT),
        "progress-check" => Some(icons::PROGRESS_CHECK),
        "progress-clock" => Some(icons::PROGRESS_CLOCK),
        "progress-close" => Some(icons::PROGRESS_CLOSE),
        "progress-download" => Some(icons::PROGRESS_DOWNLOAD),
        "progress-helper" => Some(icons::PROGRESS_HELPER),
        "progress-pencil" => Some(icons::PROGRESS_PENCIL),
        "progress-question" => Some(icons::PROGRESS_QUESTION),
        "progress-star-four-points" => Some(icons::PROGRESS_STAR_FOUR_POINTS),
        "progress-star" => Some(icons::PROGRESS_STAR),
        "progress-tag" => Some(icons::PROGRESS_TAG),
        "progress-upload" => Some(icons::PROGRESS_UPLOAD),
        "progress-wrench" => Some(icons::PROGRESS_WRENCH),
        "projector-off" => Some(icons::PROJECTOR_OFF),
        "projector-screen-off-outline" => Some(icons::PROJECTOR_SCREEN_OFF_OUTLINE),
        "projector-screen-off" => Some(icons::PROJECTOR_SCREEN_OFF),
        "projector-screen-outline" => Some(icons::PROJECTOR_SCREEN_OUTLINE),
        "projector-screen-variant-off-outline" => Some(icons::PROJECTOR_SCREEN_VARIANT_OFF_OUTLINE),
        "projector-screen-variant-off" => Some(icons::PROJECTOR_SCREEN_VARIANT_OFF),
        "projector-screen-variant-outline" => Some(icons::PROJECTOR_SCREEN_VARIANT_OUTLINE),
        "projector-screen-variant" => Some(icons::PROJECTOR_SCREEN_VARIANT),
        "projector-screen" => Some(icons::PROJECTOR_SCREEN),
        "projector" => Some(icons::PROJECTOR),
        "propane-tank-outline" => Some(icons::PROPANE_TANK_OUTLINE),
        "propane-tank" => Some(icons::PROPANE_TANK),
        "protocol" => Some(icons::PROTOCOL),
        "publish-off" => Some(icons::PUBLISH_OFF),
        "publish" => Some(icons::PUBLISH),
        "pulse" => Some(icons::PULSE),
        "pump-off" => Some(icons::PUMP_OFF),
        "pump" => Some(icons::PUMP),
        "pumpkin" => Some(icons::PUMPKIN),
        "purse-outline" => Some(icons::PURSE_OUTLINE),
        "purse" => Some(icons::PURSE),
        "puzzle-check-outline" => Some(icons::PUZZLE_CHECK_OUTLINE),
        "puzzle-check" => Some(icons::PUZZLE_CHECK),
        "puzzle-edit-outline" => Some(icons::PUZZLE_EDIT_OUTLINE),
        "puzzle-edit" => Some(icons::PUZZLE_EDIT),
        "puzzle-heart-outline" => Some(icons::PUZZLE_HEART_OUTLINE),
        "puzzle-heart" => Some(icons::PUZZLE_HEART),
        "puzzle-minus-outline" => Some(icons::PUZZLE_MINUS_OUTLINE),
        "puzzle-minus" => Some(icons::PUZZLE_MINUS),
        "puzzle-outline" => Some(icons::PUZZLE_OUTLINE),
        "puzzle-plus-outline" => Some(icons::PUZZLE_PLUS_OUTLINE),
        "puzzle-plus" => Some(icons::PUZZLE_PLUS),
        "puzzle-remove-outline" => Some(icons::PUZZLE_REMOVE_OUTLINE),
        "puzzle-remove" => Some(icons::PUZZLE_REMOVE),
        "puzzle-star-outline" => Some(icons::PUZZLE_STAR_OUTLINE),
        "puzzle-star" => Some(icons::PUZZLE_STAR),
        "puzzle" => Some(icons::PUZZLE),
        "pyramid-off" => Some(icons::PYRAMID_OFF),
        "pyramid" => Some(icons::PYRAMID),
        #[allow(deprecated)]
        "qi" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'qi' is deprecated.").print(py);
            }
            Some(icons::QI)
        }
        #[allow(deprecated)]
        "qqchat" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'qqchat' is deprecated.").print(py);
            }
            Some(icons::QQCHAT)
        }
        "qrcode-edit" => Some(icons::QRCODE_EDIT),
        "qrcode-minus" => Some(icons::QRCODE_MINUS),
        "qrcode-plus" => Some(icons::QRCODE_PLUS),
        "qrcode-remove" => Some(icons::QRCODE_REMOVE),
        "qrcode-scan" => Some(icons::QRCODE_SCAN),
        "qrcode" => Some(icons::QRCODE),
        "quadcopter" => Some(icons::QUADCOPTER),
        "quality-high" => Some(icons::QUALITY_HIGH),
        "quality-low" => Some(icons::QUALITY_LOW),
        "quality-medium" => Some(icons::QUALITY_MEDIUM),
        "queue-first-in-last-out" => Some(icons::QUEUE_FIRST_IN_LAST_OUT),
        #[allow(deprecated)]
        "quora" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'quora' is deprecated.").print(py);
            }
            Some(icons::QUORA)
        }
        "rabbit-variant-outline" => Some(icons::RABBIT_VARIANT_OUTLINE),
        "rabbit-variant" => Some(icons::RABBIT_VARIANT),
        "rabbit" => Some(icons::RABBIT),
        "racing-helmet" => Some(icons::RACING_HELMET),
        "racquetball" => Some(icons::RACQUETBALL),
        "radar" => Some(icons::RADAR),
        "radiator-disabled" => Some(icons::RADIATOR_DISABLED),
        "radiator-off" => Some(icons::RADIATOR_OFF),
        "radiator" => Some(icons::RADIATOR),
        "radio-am" => Some(icons::RADIO_AM),
        "radio-fm" => Some(icons::RADIO_FM),
        "radio-handheld" => Some(icons::RADIO_HANDHELD),
        "radio-off" => Some(icons::RADIO_OFF),
        "radio-tower" => Some(icons::RADIO_TOWER),
        "radio" => Some(icons::RADIO),
        "radioactive-circle-outline" => Some(icons::RADIOACTIVE_CIRCLE_OUTLINE),
        "radioactive-circle" => Some(icons::RADIOACTIVE_CIRCLE),
        "radioactive-off" => Some(icons::RADIOACTIVE_OFF),
        "radioactive" => Some(icons::RADIOACTIVE),
        "radiobox-blank" => Some(icons::RADIOBOX_BLANK),
        "radiobox-indeterminate-variant" => Some(icons::RADIOBOX_INDETERMINATE_VARIANT),
        "radiobox-marked" => Some(icons::RADIOBOX_MARKED),
        "radiology-box-outline" => Some(icons::RADIOLOGY_BOX_OUTLINE),
        "radiology-box" => Some(icons::RADIOLOGY_BOX),
        "radius-outline" => Some(icons::RADIUS_OUTLINE),
        "radius" => Some(icons::RADIUS),
        "railroad-light" => Some(icons::RAILROAD_LIGHT),
        "rake" => Some(icons::RAKE),
        "raspberry-pi" => Some(icons::RASPBERRY_PI),
        "raw-off" => Some(icons::RAW_OFF),
        "raw" => Some(icons::RAW),
        "ray-end-arrow" => Some(icons::RAY_END_ARROW),
        "ray-end" => Some(icons::RAY_END),
        "ray-start-arrow" => Some(icons::RAY_START_ARROW),
        "ray-start-end" => Some(icons::RAY_START_END),
        "ray-start-vertex-end" => Some(icons::RAY_START_VERTEX_END),
        "ray-start" => Some(icons::RAY_START),
        "ray-vertex" => Some(icons::RAY_VERTEX),
        "razor-double-edge" => Some(icons::RAZOR_DOUBLE_EDGE),
        "razor-single-edge" => Some(icons::RAZOR_SINGLE_EDGE),
        #[allow(deprecated)]
        "react" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'react' is deprecated.").print(py);
            }
            Some(icons::REACT)
        }
        "read" => Some(icons::READ),
        "receipt-clock-outline" => Some(icons::RECEIPT_CLOCK_OUTLINE),
        "receipt-clock" => Some(icons::RECEIPT_CLOCK),
        "receipt-outline" => Some(icons::RECEIPT_OUTLINE),
        "receipt-send-outline" => Some(icons::RECEIPT_SEND_OUTLINE),
        "receipt-send" => Some(icons::RECEIPT_SEND),
        "receipt-text-arrow-left-outline" => Some(icons::RECEIPT_TEXT_ARROW_LEFT_OUTLINE),
        "receipt-text-arrow-left" => Some(icons::RECEIPT_TEXT_ARROW_LEFT),
        "receipt-text-arrow-right-outline" => Some(icons::RECEIPT_TEXT_ARROW_RIGHT_OUTLINE),
        "receipt-text-arrow-right" => Some(icons::RECEIPT_TEXT_ARROW_RIGHT),
        "receipt-text-check-outline" => Some(icons::RECEIPT_TEXT_CHECK_OUTLINE),
        "receipt-text-check" => Some(icons::RECEIPT_TEXT_CHECK),
        "receipt-text-clock-outline" => Some(icons::RECEIPT_TEXT_CLOCK_OUTLINE),
        "receipt-text-clock" => Some(icons::RECEIPT_TEXT_CLOCK),
        "receipt-text-edit-outline" => Some(icons::RECEIPT_TEXT_EDIT_OUTLINE),
        "receipt-text-edit" => Some(icons::RECEIPT_TEXT_EDIT),
        "receipt-text-minus-outline" => Some(icons::RECEIPT_TEXT_MINUS_OUTLINE),
        "receipt-text-minus" => Some(icons::RECEIPT_TEXT_MINUS),
        "receipt-text-outline" => Some(icons::RECEIPT_TEXT_OUTLINE),
        "receipt-text-plus-outline" => Some(icons::RECEIPT_TEXT_PLUS_OUTLINE),
        "receipt-text-plus" => Some(icons::RECEIPT_TEXT_PLUS),
        "receipt-text-remove-outline" => Some(icons::RECEIPT_TEXT_REMOVE_OUTLINE),
        _ => None,
    }
}
