# coding: utf-8

"""
    QAnswer: Api Documentation

    APIs provided by QAnswer

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qanswer-sdk.models.applied_metadata_filter import AppliedMetadataFilter

class TestAppliedMetadataFilter(unittest.TestCase):
    """AppliedMetadataFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppliedMetadataFilter:
        """Test AppliedMetadataFilter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppliedMetadataFilter`
        """
        model = AppliedMetadataFilter()
        if include_optional:
            return AppliedMetadataFilter(
                key = '',
                value = qanswer-sdk.models.value.value(),
                type = 'auto_filter'
            )
        else:
            return AppliedMetadataFilter(
                key = '',
                value = qanswer-sdk.models.value.value(),
                type = 'auto_filter',
        )
        """

    def testAppliedMetadataFilter(self):
        """Test AppliedMetadataFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
