
#                     !!! WARNING !!!
#             This is an auto-generated file!
#                 Generated by [Builder].
# Any manual modifications will be lost upon regeneration.
#             DO NOT EDIT THIS FILE DIRECTLY.

from typing import TYPE_CHECKING
from ....gadgets.tlobject import TLRequest
from ....gadgets.byteutils import Writer
from ...types.payments.stars_status import TypePaymentsStarsStatus


if TYPE_CHECKING:
    from ...types.input_peer import TypeInputPeer


class GetStarsStatus(TLRequest[TypePaymentsStarsStatus]):
    """
    Get the current [Telegram Stars balance](https://core.telegram.org/api/stars) of the current account (with peer= [inputPeerSelf](https://core.telegram.org/constructor/inputPeerSelf)), or the stars balance of the bot specified in peer.

    Raises:
        `400`PeerIdInvalidError: The provided peer id is invalid.

    """

    _id = 0X104FCFA7
    _result_id = 0XC88B272F

    def __init__(
        self,
        peer: 'TypeInputPeer'
    ):

        """
        Get the current [Telegram Stars balance](https://core.telegram.org/api/stars) of the current account (with peer= [inputPeerSelf](https://core.telegram.org/constructor/inputPeerSelf)), or the stars balance of the bot specified in peer.

        Args:
            peer ('TypeInputPeer'): Peer of which to get the balance.
        """

        self.peer = peer

    def to_bytes(self, boxed: bool=True):
        with Writer(b'\xa7\xcfO\x10' if boxed else b'') as writer:
            writer.object(
                self.peer,
                group_id=0X995DB9DF
            )

            return writer.getvalue()